### ISSUE TITLE
ANOVA debugging

### ISSUE THREAD

**Issue by 0todd0000** [0todd0000/spm1dmatlab#1]
To debug **spm1d** ANOVA errors try the following:

(1)  Run the 0D examples.
Example  (two-way repeated measures ANOVA)
./spm1d03/examples/stats0d/ex_anova2rm.m

(2)  Check the original examples on the web using the "www" field of the example datasets
Example:
```
>>  dataset = spm1d.data.uv0d.anova2rm.Antidepressant();
>>  dataset.www
http://www.pc.rhul.ac.uk/staff/J.Larsson/teaching/pdfs/repeatedmeasures.pdf
```

(3)  Organize the inputs to **spm1d.stats.anova2rm** following the example datasets.
Example  (two-way repeated measures ANOVA)
Y:   J x Q array  (dependent variable)
A:  J x 1 array  (Factor A integer labels)
B:  J x 1 array  (Factor B integer labels)
SUBJ:   J x 1 array (Subject integer labels)  

Todd

**Comment by ellenmaas** [comment]
Hi Todd,

I've followed the above instructions and organized my data in the following way: A = 100x1 array containing factor A (group) numbers, B = 100x1 array containing factor B (time) numbers, SUBJ = 100x1 array containing subject numbers, y = 100x101 array containing the dependent variable. 

However, I still get the following error: 

Error in Solver>Solver.compute_test_statistic_rm (line 64)
           [C,CE]    = contrast.get_compound_matrices();

Error using spm1d.stats.anova.solvers.Solver/compute_test_statistic_rm
Output argument "SPM" (and maybe others) not assigned during call to
"C:\Users\u0086689\Documents\SPM\+spm1d\+stats\+anova\+solvers\Solver.m>Solver.compute_test_statistic_rm".

Error in spm1d.stats.anova.solvers.Solver/compute_test_statistics (line 83)
                   SPM{i} = self.compute_test_statistic_rm( contrasts{i} );

Error in spm1d.stats.anova2rm (line 6)
SPM    = solver.compute_test_statistics(CC);

Error in ex_anova2rm (line 22)
spm  = spm1d.stats.anova2rm(y, A, B, SUBJ);

Any ideas?

Thanks in advance,

Ellen

**Comment by 0todd0000** [comment]
Hi Ellen,

Does the 0D example run without errors?
./spm1d03/examples/stats0d/ex_anova2rm.m

If that runs OK then the problem is most likely in the A, B and/or SUBJ arrays.

Could you either:

(a)  Plot the three arrays and attach the figure:
```
plot(A)
hold on
plot(B)
plot(SUBJ)
```

or

(b)  Paste the three arrays into your reply?
e.g.
A = [1 1 1 1 1 1 2 2 2 2 2 2...] 
B = [1 1 1 2 2 2 1 1 1 2 2 2...] 
SUBJ = [1 2 3 4 5 1 2 3 4 5...] 

Todd

**Comment by ellenmaas** [comment]
Hi Todd,

The 0d example runs with just an error regarding the plots. 

![spmarrays](https://cloud.githubusercontent.com/assets/13256591/8599248/a716551c-265f-11e5-8e28-1ce548be87cf.png)

Ellen

**Comment by 0todd0000** [comment]
Hi Ellen,
I think I see the problem.  The design appears to be a bit too complex. A two-way repeated-measures ANOVA requires all subjects to perform all conditions, but in this case it appears that different subjects perform conditions A1 and A2.  This means that only Factor B is a repeated-measures factor, and that the design could be described as "two-way ANOVA with one repeated-measures factor".

Please check the example datasets and results here:
./examples/stats0d/ex_anova2onerm.m
and try using the function:
**spm1d.stats.anova2onerm**

Todd

**Comment by ellenmaas** [comment]
Thanks for the suggestion, I think that the two-way ANOVA with one repeated measures factor is indeed more appropriate. Unfortunately, I get exactly the same error using this function. 

Ellen

**Comment by 0todd0000** [comment]
Hi Ellen,

I found the source of the problem and have fixed it.

To fix the problem on your computer please either:

(a) Download the latest source code (version 0.3.0.1)

OR

(b) Download only the following file and replace the existing file on your computer:   **+spm1d/+stats/+anova/+solvers/Solver.m**
You can get to this file from the link below:
https://github.com/0todd0000/spm1dmatlab/tree/master/%2Bspm1d/%2Bstats/%2Banova/%2Bsolvers

Please let me know if that doesn't fix the problem.
Thank you very much for reporting the problem and also for your patience.

Todd

**Comment by ellenmaas** [comment]
Thank you, it seems to work now! 

FYI, I still get this error:
In an assignment  A(I) = B, the number of elements in B and I must be the same.

Error in spm1d.stats.spm.SPMiList/disp_summ (line 43)
                F(i)  = spm.z;

Error in ex_anova2onerm (line 23)
disp_summ(spmi)

But I guess this is just for displaying a summary of the results?

Ellen

**Comment by 0todd0000** [comment]
Great, I'm glad it's working, and I'm sorry once again for the bug.

Regarding the error in **display_summ**::
This function is meant to be used only for 0D analysis. It displays the results similar to an ANOVA table summary. Since it's obviously not possible to display 1D results in a table, please avoid that function for 1D results.

I'll add an more informative error message to the **display_summ** function so that its intended use will be clearer.

Thanks again for reporting these issues.
Todd

**Comment by ellenmaas** [comment]
Ok, thanks for the clarification.

I still get an error on some of my variables, but not all of them (although they are organized in exactly the same way): 

Improper assignment with rectangular empty matrix.

Error in spm1d.geom.cluster_geom (line 9)
    heights(i) = min( z(L==i) );

Error in spm1d.stats.spm.SPM/inference (line 64)
            [extents,heights] = spm1d.geom.cluster_geom(self.z, zstar);

Error in spm1d.stats.spm.SPMList/inference (line 21)
               spmi = spm.inference(alpha, varargin{:});

Error in ex_anova2onerm (line 22)
spmi = spm.inference(0.05);
 
Ellen

**Comment by 0todd0000** [comment]
Hi Ellen,
Thanks for reporting the inference problem.
I'm going to open this as a new issue (issue https://github.com/0todd0000/spm1dmatlab/issues/3)
Todd

**Comment by 0todd0000** [comment]
Hi Ellen,  this is a brief follow-up:
The new version of the code (version 0.3.1, released today) now supports repeated-measures ANOVA with different numbers of subjects. This is applicable to the following designs:
* anova2onerm
* anova3onerm
* anova3tworm

For anova2rm and anova3rm the same number of subjects is still needed for all conditions.

Two new datasets can be used to test this out:

```
dataset = spm1d.data.uv0d.anova2onerm.Santa23UnequalSampleSizes();
dataset = spm1d.data.uv0d.anova2onerm.Southampton2onermUnequalSampleSizes();

[y,A,B,SUBJ] = deal(dataset.Y, dataset.A, dataset.B, dataset.SUBJ);
disp(dataset)

spm  = spm1d.stats.anova2onerm(y, A, B, SUBJ);
spmi = spm.inference(0.05);
disp_summ(spmi)
```

Cheers,
Todd

**Comment by Lilalol** [comment]
Hy Todd, Thanks for all your work. I have a question though:
I try to do the spm.inference (0.05) while using the following script:

Y = Datamis.KnieG; (27x101)
A = Convmis; (27x1)
SUBJ = PPvmis; (27x1)


F  = spm1d.stats.anova1rm( Y, A, SUBJ);
Fi = F.inference(0.05)
Fi.plot()

However I get the following error when trying tor run F.inference(0.05):

In an assignment  A(:) = B, the number of elements in A and B must be the same.

Error in spm1d.stats.spm.SPM/get_p_values (line 108)
                p(i) = self.get_p_value(kk(i), uu(i), two_tailed);

Error in spm1d.stats.spm.SPM/inference (line 72)
            p           = self.get_p_values(extentsR, heights, two_tailed);

I tried some thing already but nothing works ou. Could u please help me?

Best regards
Lotte

**Comment by 0todd0000** [comment]
Hi Lotte,
Thank you for reporting the problem, and apologies for the inconvenience.
Since this problem is slightly different than the bud Ellen discovered I've moved it to a new issue: #7. 
Todd
