### ISSUE TITLE
spm_u

### ISSUE THREAD

**Issue by ChrisWeich** [0todd0000/spm1dmatlab#100]
Hallo,
when I started to run an example for a 3D analysis (./spm1d/examples/ex_hotellings* ), MATLAB responded: Output argument "u" (and maybe others) not assigned during call to "spm_u". 
It would really appreciate your help.
Thanks 
Christian

**Comment by 0todd0000** [comment]
Thank you for reporting this bug!  Please provide the following additional information:

1. Matlab version
2. spm1d version (available in ./spm1d/VERSION.txt)
3. Did you install using subfolders according to the following link? http://www.spm1d.org/install/InstallationMatlab.html#label-installationmatlab
4. Have you installed a different version of SPM like SPM8 or SPM12? (https://www.fil.ion.ucl.ac.uk/spm/software/)
5. Which Hotelling's script are you using, with which dataset?
6. Please copy and paste the full error message. 

Thanks!
