### ISSUE TITLE
How to arrange a 3D dataset?

### ISSUE THREAD

**Issue by ChrisWeich** [0todd0000/spm1dmatlab#101]
Hallo everyone,
looking at your examples for 3D analyses like Besier2009muscleforces.mat, the data structure is 
...x...x... -> meaning 3 times double. I have also files containing 3 D acceleration data: multiple persons / trials with 3 axes (x,y,z) for each, the left and right foot. How should I arrange my dataset if I want to compare for example the first, a mid and the last minute of a run versus the same time points of another athlete. Each minute contains the following sizes: 500 datapoints for each axis (6 = x,y,z for L and R foot) over 3x 1 minute. 

Thank you very much! I really appreciate your help
Christian

**Comment by 0todd0000** [comment]
Let's assume that there are 30 trials of (500 x 6) data, and that you can load each of the 30 trials into MATLAB using a custom function **load_trial** like this:  

```matlab
>> a1 = load_trial(filename1);   % a (500 x 6) array (Trial 1)
>> a2 = load_trial(filename2);   % a (500 x 6) array (Trial 2)
etc.
```

The easiest way to assemble these data into the format **spm1d* requires is to initialize an array of zeros, then sequentially assign each 2D array to a certain slice like this:
 
```matlab
>> A = zeros(30, 500, 6);
>> A(1,:,:) = a1;
>> A(2,:,:) = a2;
etc.
```

Another option would be to use MATLAB's built-in **cat** function:
https://www.mathworks.com/help/matlab/ref/cat.html
