### ISSUE TITLE
Data length 

### ISSUE THREAD

**Issue by ChrisWeich** [0todd0000/spm1dmatlab#102]
Refering to the issues #100 and #101, do the data have to have the same length? 

Thank you

**Comment by 0todd0000** [comment]
Yes, **spm1d** requires that data are [registered](https://rss.onlinelibrary.wiley.com/doi/abs/10.1111/1467-9868.00129). If *J* is the number of observations, *Q* is the number of continuum (time) nodes, and *I* is the number of vector components, the data must be stored in arrays as follows:

* Univariate 0D data:  (J x 1) array
* Multivariate 0D data:  (J x I) array
* Univariate 1D data:  (J x Q) array
* Multivariate 1D data:  (J x Q x I) array

Where "univariate" and "multivariate" mean "scalar" and "vector", respectively. **spm1d** accepts data only in the format above, and infers the data type from the selected test or procedure.

"Registration" implies that the data are aligned, in a presumably homologous manner. This assumption of homology is common to all data analyses in all fields, irrespective of data complexity.  When the data are univariate or multivariate 1D continua, there are many options for registration including linear registration (which is usually done in Biomechanics), and [nonlinear registration](https://www.researchgate.net/publication/10715586_Continuous_curve_registration_as_an_intertrial_gait_variability_reduction_technique). The selected registration procedure and its parameters, like data smoothing algorithms and their parameters, can affect the final statistical results so should be regarded as a possible source of variability in analyses.
