### ISSUE TITLE
Output 3D plotting

### ISSUE THREAD

**Issue by ChrisWeich** [0todd0000/spm1dmatlab#103]
After applying your suggestions in #100 and #101 I finally got a statistical result. In earlier applications of the SPM method I got (performing a T Test) a nice red-black graph to compare the two datasets with their SD graphically. Is this plotting also possible for the 3D Version I applied as described above in #101 .

Thank you !

**Comment by 0todd0000** [comment]
Hi, in **spm1d** there are no automated plotting options for multivariate (vector) data. One way to view these data is to plot each component independently. So if the data array "A" is (20 x 101 x 3), for example, you can get the individual components like this:

```matlab
>> a1 = A(:,:,1);
>> a2 = A(:,:,2);
>> a3 = A(:,:,3);
```

then plot each component separately using **spm1d.plot.plot_meanSD**, or using built-in MATLAB commands like:

```
>> plot(a1')
```
