### ISSUE TITLE
2 way Repeated Measures ANOVA on 2 factors Capabilities

### ISSUE THREAD

**Issue by nray11** [0todd0000/spm1dmatlab#104]
Good morning,

I have a study design that lends itself well to a 2 way repeated measures ANOVA on 2 factors. Is this capability in the works for the Matlab package? If not, do you have suggestions to work around this issue with your plug-in? Thank you!

Best,
Nicole

**Comment by 0todd0000** [comment]
Hi Nicole,

Yes, **spm1d** currently supports two repeated measures designs:

* spm1d.stats.anova2rm
* spm1d.stats.anova2onerm

See the following scripts:
./spm1d/examples/stats0d/ex_anova2onerm.m
./spm1d/examples/stats0d/ex_anova2rm.m

 and see the dataset descriptions and links for detailed descriptions of these designs.

Todd
