### ISSUE TITLE
Unexpected results and effect size

### ISSUE THREAD

**Issue by ChrisWeich** [0todd0000/spm1dmatlab#105]
Hi Todd,

thanks for your help. I used the Hotellings code to analyze my data: 

1. Comparison of two 60 min runs of the same person -> expected to be not different

2. Comparison of two 60 min runs of two differnt persons -> expected to be different

So I arranged both as 60x400x6 multivariate datasets (minutes x datapoints on the attractor x dimensions (3D for each foot)).

For 1. I used Hotellings paired because it is the same person running, just on different days; whereas for 2. I have two different persons running. Thus I chose Hotellings2.    

Find attached the statistical outcome for case 1 and 2. 

![hotellings att data](https://user-images.githubusercontent.com/47910758/53863199-daa9c600-3fe9-11e9-9283-31b10a57a6cf.jpg)
![case 2 - two different subjects](https://user-images.githubusercontent.com/47910758/53863448-89e69d00-3fea-11e9-88f8-3f95ee8711e7.jpg)

Thanks again for your great help! 
I really appreciate it

**Comment by ChrisWeich** [comment]
And one further question...Is it possible to get also the effect size afterwards?

**Comment by 0todd0000** [comment]
OK, let's check the first case, and maybe that will help solve the second case.  Please create six figures (or one figure with six sub-panels). In each figure or sub-panel, plot the data for one of the six components, color-coding according to trial.  If *YA* and *YB* contain the (60x400x6) data for trials 1 and 2, respectively, then you could plot component 1 like this:

```matlab
>>  component = 1;
>>  yA = YA(:,:,component);  %
>>  yB = YB(:,:,component);

>>  plot(yA', 'k');  %trial1: black
>>  hold on
>>  plot(yB', 'r');  %trial2: red
```

Alternatively you could use **spm1d** to plot the means and standard deviations like this:

```matlab
>>  spm1d.plot.plot_meanSD(yA, 'color', 'k');
>>  hold on
>>  spm1d.plot.plot_meanSD(yB, 'color', 'r');
```

By plotting the individual components like this it might be possible to figure out why there is such a big difference.

**Comment by ChrisWeich** [comment]
Todd, 
please find attached three examples, two for case 1 and one for case 2


![case 1_carmen day 1 vs day2](https://user-images.githubusercontent.com/47910758/53878070-359fe500-400b-11e9-89f5-264ce25467d8.jpg)
![case 1_chris day 1 vs day2](https://user-images.githubusercontent.com/47910758/53878071-359fe500-400b-11e9-95d4-e3b764e20e14.jpg)
![case 2_chris vs carmen day 1](https://user-images.githubusercontent.com/47910758/53878073-36387b80-400b-11e9-928c-10bcc09520a1.jpg)

**Comment by 0todd0000** [comment]
Sorry, I just noticed your question regarding effect sizes. There have been a few discussions regarding effect size in this forum and also in **spm1d**'s Python forum here:
https://github.com/0todd0000/spm1d/issues
To summarize: effect size calculation is not yet supported in **spm1d**, and if you calculate effect sizes for 1D data be aware that their probabilistic meaning and interpretation can be different from the usual 0D case.


In the data you sent there are some very large differences. For example, the bottom center panel suggests very large differences in the windows 100-200 and about 250-350.  For some variables like the bottom right panel it would appear that that temporal differences may be larger than amplitude differences. Temporal differences can be minimized using nonlinear registration, but nonlinear registration would only be appropriate if your hypothesis explicitly pertains to only amplitude differences and not to temporal ones.

If you were to re-run the analyses using only similar variables (e.g. the three variables in the top row) you will likely find that the T2 values reduce substantially.

**Comment by ChrisWeich** [comment]
Hi! 
Thanks for your reply. Please consider that the third series is between two persons. Here I expect a big difference. 
But in contrast to this set, see the other two sets, especially the first  (the one with the headers). They are almost superposing but still they are overall highly significant different. Or is this due to the huge amount of data? 
Thanks

**Comment by 0todd0000** [comment]
I see what you mean. The differences are definitely less noticeable in the first Case 1 plot. I think the differences, even though apparently small, are still large relative to the variance. For example, in "z axis left foot" there appear to be relatively large effects near both time=200 and time=300.  Here are two ways to check more thoroughly:

* [Informal check]:  Plot the (mean difference) / (standard deviation) ratio. This is approximately the same as the t statistic (and effect size), but is somewhat easier to interpret;  when the ratio is 3, for example, it implies a large effect, a mean difference three times greater than the SD. 

* [Formal check]:  Conduct *post hoc* two-sample t tests on individual components using **spm1d.stats.ttest2** and a correction for multiple comparisons. You will likely find large t values in "z axis left foot", and probably in other variables / components. Note that **spm1d** does not yet explicitly support *post hoc* analyses. Please search the **spm1d** forums for "post hoc" to find  relevant discussions.

**Comment by ChrisWeich** [comment]
Hi Todd,
I grouped the attractors so that I got 10min blocks. 

Analyzed them as discussed and got this result. Does it look reasonable?
Why is p_set at NaN? 
Does p: [ ] mean that there is no sig. difference / that p is > 0.05 ? 

Thanks

![result grouping](https://user-images.githubusercontent.com/47910758/54232899-107c0c80-450c-11e9-8cbf-2feebad9abe3.jpg)

**Comment by 0todd0000** [comment]
Apologies for the delay.  p_set is NaN because the critical threshold is not exceeded, so it is undefined. Set- and cluster-level probabilities require the threshold to be exceeded.

The very large critical T2 value in this case implies that there are far too few observations (8, I believe?) relative to the number of variables (6).  For the univariate case (i.e., a single variable) approximately 8 - 10 observations are required for stable standard deviation estimates. For multivariate data (i.e., multiple variables), the required number of observations increases substantially. I would be hesitant to conclude anything from these results because there are too few observations.
