### ISSUE TITLE
Flattened 3D foot meshes

### ISSUE THREAD

**Issue by Little-Foot-Shapes** [0todd0000/spm1dmatlab#107]
Hello, 

I have flat surfaces extracted from a 3D shape (3D foot scans), where I have coordinates (x,y) and data (d) for each vertex. I would like to use SPM to compare 3 different age groups, with 5 feet in each. 
There was a mention that SPM12 can be used for 2D1D analysis. I was wondering how one would get started with this? I have the surfaces in point clouds in Matlab, with z (vertical component set to 1).  Obviously the 3 age groups' feet are different in size and shape. How do I apply the SPM12 to this type of data to make sure that the stats are going to compare the corresponding vertices' data?

Thank you.

Best Regards
Mat

**Comment by 0todd0000** [comment]
Hi Mat,

This type of analysis would indeed be possible using SPM, and to get started you'd need to conduct registration (i.e., spatial alignment) so that meaningful mean (and variance) point clouds can be computed. SPM12 offers powerful registration options, but it might take a fair bit of effort to adapt the point cloud data to a format that SPM12 supports. Another good option for registration is the [Insight Toolkit](https://itk.org). A variety of other software environments also support automatic image registration, including Matlab and scipy. Manual image registration is also possible. 

Following registration, statistical tests can be conducted, and this can indeed be done in SPM12, but it would probably be easier to use **spm1d**. Only relatively minor tweaks to existing example scripts would be needed.

While we can't support 2D registration in this forum (because **spm1d** does not offer it), if you are able to get the images registered feel free to post again.

Todd

**Comment by Little-Foot-Shapes** [comment]
Hi Todd, 

Thank you. 
So if I had registered greyscale images (greyscale value is actually the data I want to analyse)  for each foot surface, I could use  spm1d to compare age groups? I guess they have to have the same number of pixels across age groups?

Thank you. 

Best regards 

Mat

**Comment by 0todd0000** [comment]
Yes, that's correct. The registration procedure should ensure that each foot image has the same number of pixels.  Although **spm1d** only supports nonparametric analysis of 2D greyscale data, in practice parametric and nonparametric results are often quite similar.

**Comment by Little-Foot-Shapes** [comment]
Hi Todd,

Thank you again. Did you use spm1d in your study on plantar pressure analysis (J Biomech.<https://www.ncbi.nlm.nih.gov/pubmed/18555256> 2008 Jul 19;41(10):2136-43. doi: 10.1016/j.jbiomech.2008.04.034. Epub 2008 Jun 13. Pedobarographic statistical parametric mapping (pSPM): a pixel-level approach to foot pressure image analysis.)?

Thank you.

Best Regards

Matyas Varga M.P.Ed
PhD Student
University of Brighton
Aldro Building, 49 Darley Road
Eastbourne, BN20 7UR
Email: M.Varga@Brighton.ac.uk<mailto:M.Varga@Brighton.ac.uk<mailto:M.Varga@Brighton.ac.uk%3cmailto:M.Varga@Brighton.ac.uk>>

**Comment by 0todd0000** [comment]
I used custom software, an adaption of [SPM5](https://www.fil.ion.ucl.ac.uk/spm/software/spm5/). That software was hacked together and is unsuitable for general analysis, but in the next few years I hope to release a software package that supports 2D analysis.

**Comment by Little-Foot-Shapes** [comment]
Hi Todd,

Thank you.

At the moment I have the same number of pixels in the images after registration, but the number of pixels that actually make up the surface within the image (the ones with a value not equalling 1) is not the same as in the source image. Is that a problem for SPM?

Thank you.

Matyas Varga M.P.Ed
PhD Student
University of Brighton
Aldro Building, 49 Darley Road
Eastbourne, BN20 7UR
Email: M.Varga@Brighton.ac.uk<mailto:M.Varga@Brighton.ac.uk<mailto:M.Varga@Brighton.ac.uk%3cmailto:M.Varga@Brighton.ac.uk>>


___________________________________________________________
This email has been scanned by MessageLabs' Email Security System
on behalf of the University of Brighton. For more information see:
https://staff.brighton.ac.uk/is/computing/Pages/Email/spam.aspx

**Comment by 0todd0000** [comment]
That could be a problem, but there is an easy way around the problem:
Threshold all images (at a value of 10 kPa, for example). This should ensure non-zero pixel values.

Consider the following example:
A specific pixel has zero pressure in 19 images, and a value of 50 kPa in the 20th image. For this case means and standard deviations would be misleading, and test statistics may be undefined. However, this pixel likely has no scientific meaning, so can be safely ignored via thresholding.

In general, registration is always imperfect. It can often be useful to conduct sensitivity analyses, by systematically varying registration parameters, and checking for (mis)registration-related effects.

Todd

**Comment by Little-Foot-Shapes** [comment]
Hi Todd,

Thank you for that, useful.
I am not sure about the thresholding though…
Can I just set the pixels to 1 where the number of actual data is very low?
So in your example, one would find the rows in the set of flattened images where the number of pixels with 0 pressure is too high (18-19) and set all the other values to 0 too?

In my data, I have curvedness, most of the values are between 0 and 0.2 and the rest of the pixels are 1.
I have 12325 rows for each flattened image, 15 images. 3 groups: rows 1:5, 6:10, 11:15.
So as an example in the below matrix I should set all rows to 1 in column 4654 and 4671?


[cid:image002.png@01D4F144.CE1AA5B0]

[cid:image003.jpg@01D4F147.F9817550]

Thank you.

Best Regards

Mat

Matyas Varga M.P.Ed
PhD Student
University of Brighton
Aldro Building, 49 Darley Road
Eastbourne, BN20 7UR
Email: M.Varga@Brighton.ac.uk<mailto:M.Varga@Brighton.ac.uk<mailto:M.Varga@Brighton.ac.uk%3cmailto:M.Varga@Brighton.ac.uk>>

___________________________________________________________
This email has been scanned by MessageLabs' Email Security System
on behalf of the University of Brighton. For more information see:
https://staff.brighton.ac.uk/is/computing/Pages/Email/spam.aspx

**Comment by 0todd0000** [comment]
> Can I just set the pixels to 1 where the number of actual data is very low?

I'm not sure I see an advantage to setting pixel values to 1 vs. 0.

> So in your example, one would find the rows in the set of flattened images where the number of pixels with 0 pressure is too high (18-19) and set all the other values to 0 too?

Just threshold the image using the inequality: image > scalar_threshold

(The images don't appear in the forum so I can't respond to the last question.)

**Comment by 0todd0000** [comment]
Preliminary support for 2D data analysis has been added to **spm1d**!
[Example 2D analysis (Python)](http://www.spm1d.org/doc/Stats2D/ex2d.html)
[Example 2D analysis (MATLAB)](http://www.spm1d.org/doc/Stats2D/ex2d_matlab.html)
