### ISSUE TITLE
I did SPM paired t-test and SPM ANOVA in Matlab. For SPM ANOVA, I can get the F-value and p-value in the figure, but in the the paired t-test, I can not get this information. 

### ISSUE THREAD

**Issue by Mahaki67** [0todd0000/spm1dmatlab#109]
Hi 
I did SPM paired t-test and SPM ANOVA in Matlab. For SPM ANOVA, I can get the F-value and p-value in the figure, but in the the paired t-test, I can not get this information (see below figures, please. Top one is related to SPM paired t-test without F and P-values in the figure and subsequent figures are related to SPM ANOVA test in which one can see the related F and P-values (red numbers)). 
Is there any way to have the t-value and p-valute for SPM paired t-test in the figure as well? 

![Fig 5](https://user-images.githubusercontent.com/36861081/56222685-c0451c80-606c-11e9-8ebe-426d5f6de6d2.jpg)

![Fig 7](https://user-images.githubusercontent.com/36861081/56222798-ebc80700-606c-11e9-9af4-92657dcf2137.jpg)

**Comment by 0todd0000** [comment]
Hello, thank you for reporting this problem.
* For the t results, did you call the "plot_threshold_label" function?
* For the t results, please check whether the threshold is available in the results as shown below.

```matlab
spm  = spm1d.stats.ttest_paired(yA, yB);
spmi = spm.inference(0.05);
disp(spmi)
```

You should be able to see the threshold in the *zstar* field of the *spmi* structure.

**Comment by Mahaki67** [comment]
Thank you for your email.

I am able to see the t value of threshold in the zstar, but how can I find
the p-value?

Best,
Mohammad

**Comment by 0todd0000** [comment]
The p value should be listed in the "inference" section when displaying the *spmi* structure using ```disp(spmi)```. To display the p value on the plot use the ```spmi.plot_p_values``` method. In this case, the suprathreshold cluster is very large, so the p value will be very small (<0.001).

**Comment by 0todd0000** [comment]
Sorry, I just realized that I didn't reply to your question regarding ```plot_threshold_label```.  This simply plots the label "alpha = 0.05,  F* = 11.711" in a default location.  If this produces a result that it not acceptable, please add a custom label using [Matlab's ```text``` function](https://www.mathworks.com/help/matlab/ref/text.html).
