### ISSUE TITLE
•spm1d.stats.anova2onerm — two-way ANOVA with repeated measures on one factor

### ISSUE THREAD

**Issue by SiskaBossuyt** [0todd0000/spm1dmatlab#110]
Hi,

Regarding two-way ANOVA with repeated measures on one factor. I want to conduct this analysis to assess differences across time (pre and post fatigue), between groups (fatigued and not fatigue) and to define interaction effects for each of the discrete variables. I assume the design itself can identify which factor is the repeated measures?
To problem is that if I try to do the analysis, I receive the following error:
"
Error using spm1d.stats.anova.designs.ANOVA2onerm/check_balanced (line 69)
Design must be balanced.
Error in spm1d.stats.anova.designs.ANOVA2onerm (line 23)
            self.check_balanced()
Error in spm1d.stats.anova2onerm (line 9)
design = spm1d.stats.anova.designs.ANOVA2onerm(A, B, SUBJ);
"
Might this be caused by the fact that the amount of persons in each group is not consistent (there are 16 persons in the fatigued group and 18 in the not fatigued)?

Many thanks in advance for your support.
Kind regards,
Siska

**Comment by m-a-robinson** [comment]
Hi Siska,
Yes, because there is a repeated measures factor the design needs to be balanced (contain the same number of participants).

Also see here https://github.com/0todd0000/spm1dmatlab/issues/81#issuecomment-394540065

Best wishes,
Mark

**Comment by SiskaBossuyt** [comment]
Hi Mark,

Many thanks for your very fast response and clarification!
Sorry I missed the previous comment about this issue, I must have missed it.

Best wishes,
Siska
