### ISSUE TITLE
Apply spm1d.stats.anova1d and spm1d.stats.hotellings_paired (vector field) without average observations

### ISSUE THREAD

**Issue by andriacapai** [0todd0000/spm1dmatlab#112]
Hi everybody,

I was wondering if statistically speaking according to my experimentation (3 conditions , 100 trials for each condition)  spm1d.stats.anova1d and spm1d.stats.hotellings_paired functions are "built" to compare observations (n=100) subject by subject without average . 

Thank you,

Best regards,
Andria

**Comment by 0todd0000** [comment]
Hi Andria,
In paired tests and one-way ANOVA, each observation represents one individual from the population of interest.  So if there are N=10 individuals, with 20 trials each, and you used all 200 trials, these tests would interpret that as 200 separate individuals. This would lead to incorrect results. When using these tests you must first compute within-subject (and within condition) means.
Todd

**Comment by andriacapai** [comment]
Hi todd, 
thanks for the quick reply!
Actually, we would like to compare each individual to himself by using the 100 observations of this particular subject in one condition to the 100 observations of the same subject in another condition. 
Would it be coherent with the SPM philosophy to analyze the data on a single subject basis? 
Thanks a lot!
Andria

**Comment by andriacapai** [comment]
Hello Todd,

Sorry to disturb you again with this topic. I would like to reword my question . Based on your example : N=10 subjects with 20 trials each, here is my dataset  only 1 subject with 20 trials per condition (ex: 2 conditions) (see picture below).
How would you manage to compare several trials of the same subject for different conditions using SPM ?  (Taking into account that we can't use spm1d.anova1rm)
![Data_Y](https://user-images.githubusercontent.com/45765175/57125770-e10ab300-6d8a-11e9-8ea7-dbc93e53e4f4.PNG)

Maybe you already managed this issue with someonelse ?

Thanks a lot.
Best,

Andria

**Comment by 0todd0000** [comment]
Hi Andria,

Sorry for my delayed reply. 

If the data are univariate 1D, I'd use a two-sample t test (**spm1d.stats.ttest2**).

If the data are multivariate 1D, I'd use a two-sample Hotellings T2 test (**spm1d.stats.hotellings2**).

`Would it be coherent with the SPM philosophy to analyze the data on a single subject basis?`

Yes, in general, but it depends on the purpose of your experiment. SPM is simply a generalization of classical hypothesis testing to nD data. So if the data were 0D (e.g. maximum force), then the same question could be posed. In your experiment, if it would be suitable to analyze 0D maximum force data on a single-subject basis, then it would also be suitable to analyze univariate or multivariate nD data on a single-subject basis.

Todd

**Comment by andriacapai** [comment]
Hello Todd,

Thank you very much for your answer. 
I now understand better , thanks again Todd.

Best regards ,
Andria
