### ISSUE TITLE
ANOVA2onerm for multicomponent data

### ISSUE THREAD

**Issue by adrianrivadulla** [0todd0000/spm1dmatlab#113]
Hi Todd and Mark,

Something similar to #97 but slightly different:

We have two groups that completed pre, post, retention and transfer tests each and we've collected bar trajectories (weightlifting). We'd like to test for an interaction effect of Group x Test on BARxy. What test would be analogous to an ANOVA2onerm for our 2-component case? Or should we just use a MANOVA? If MANOVA, is there a MANOVA2onerm? Is it possible in spm1dmatlab?

Thank you for attention.

Kind regards,

Adrian

**Comment by m-a-robinson** [comment]
Hello Adrian,

This also sounds like #89. As per Todd's comment, RM-MANOVA is possible but not yet implemented in spm1d.

You could perhaps investigate your group effect using the Hotelling's T2 test (which accounts for the multi-component data) but this would have to be done separately for each test.

Regards
Mark

**Comment by adrianrivadulla** [comment]
Hi Mark,

Thanks for your answer.

Since Hotelling's T2 is analogous to a t-test, would it be possible to compare the four conditions in pairs using an alpha level corrected to the number of comparisons, just as you'd do when you use a Bonferroni correction for post hoc tests? Or is there anything in the underlying distribution and/or assumptions of the test that does not allow for this and I'm missing it out? I'm guessing that this would be done for each of the factors independently and no interaction effect could be identified but, could it be a possibility?

Cheers,

Adrian

**Comment by m-a-robinson** [comment]
Hi Adrian,
That seems reasonable to me, unfortunately it doesn't allow you to compare between the tests or the interaction so I guess this is worth considering if this allows you to answer your question.
Regards
Mark
