### ISSUE TITLE
Unbalanced one-way repeated measures ANOVA

### ISSUE THREAD

**Issue by AnnemieSmeets** [0todd0000/spm1dmatlab#114]
Hi, 

I want to perform a one-way repeated measures ANOVA on my data (measures at 3 different time points).  A few subjects dropped-out between sessions, so I don't have equal group sizes at the different time points (n1=21, n2=16, n3=14). 
I was doubting whether it is possible to run an unbalanced one-way repeated measures ANOVA in SPM? 
I found on the forum that it should be possible for one way ANOVA's? #81 But not for two-way ANOVA's? #110 

I tried to run the unbalanced one RM anova in Matlab but it did not work. Do I have to add something in the following line? 
spm  = spm1d.stats.anova1rm(Y,A,SUBJ);

Thanks in advance, 
Annemie

**Comment by m-a-robinson** [comment]
Hi Annemie,
I think this is more of a problem with using the Repeated Measures design because this does expects all subjects to be present for all repeated measurements. 
Regards
Mark

**Comment by AnnemieSmeets** [comment]
Hi Mark, 

Thank you for the quick response!

We had the idea to run 2 different repeated measures ANOVA's:
1. Only on the subjects that completed the 3 sessions 
2. On all data, meaning unequal groups at the different time points because of the drop outs

For the second comparison, we indeed do not have all repeated measurements for all subjects. 
Should I better use a normal one-way ANOVA with 3 levels to compare the time points for the second comparison?  

Regards, 
Annemie

**Comment by 0todd0000** [comment]
Hi Annemie, I'll add a comment here.

Solution 2 is RM with missing data;  **spm1d** currently does not support missing data, even for non-RM designs. From [this article](https://stats.stackexchange.com/questions/215197/dealing-with-missing-data-in-repeated-measures-anova#215198) and [this post](https://stats.stackexchange.com/questions/215197/dealing-with-missing-data-in-repeated-measures-anova#215198) you'll see that dealing with missing data in RM ANOVA can be rather complex, even for 0D data. Nevertheless, if it is justifiable to claim that the dropouts are random, then Solution 1 is also justified.

Presuming that no individual missed two sessions, and presuming that dropouts were random, I'd suggest the following:

Let *N* be the number of individuals who completed all sessions.

1. (your solution 1) Run RM-ANOVA on the *N* individuals.
2. If (1) reaches significance, run *post hoc* paired t tests on the *N* individuals.
3. If (1) reaches significance, also run *post hoc* paired t tests on the *N+n* individuals, where *N+n* is the number of individuals who completed both sessions in a specific session-pair. Report (3) as a type of sensitivity analysis, potentially as a supplementary result.

Todd
