### ISSUE TITLE
ANOVA in Matlab 

### ISSUE THREAD

**Issue by carliejonesh** [0todd0000/spm1dmatlab#116]
Hello! I am new to SPM and am having issues formatting an ANOVA analysis. An example of my code is below, I have two data sets that are 15x101, where each row is a subject, and I want to compare one set to the other. I followed the example given in the file, but I think I am just missing a step in my formatting.

load('DorsiConditionAverage.mat')
y = (1:15)';
[Y,A] = deal(ConditionAverage.Hoka, ConditionAverage.G19);

%(1) Conduct SPM analysis:
spm   = spm1d.stats.anova1(Y,A, y);  %between-subjects model
spmi      = spm.inference(0.05);

This is probably something simple, thank you in advance for any help!

**Comment by m-a-robinson** [comment]
Hello,

If you wish to compare one dataset to another you may only need to use a t-test but please re-post to clarify if I am incorrect. Assuming the two "sets" are independent of each other you could have the following.

YA  - a 15x101 matrix
YB - a 15x101 matrix

```
%(1) Conduct SPM analysis:
spm       = spm1d.stats.ttest2(YA, YB);
spmi      = spm.inference(0.05, 'two_tailed',true, 'interp',true);
disp(spmi)

%(2) Plot:
close all
spmi.plot();
spmi.plot_threshold_label();
spmi.plot_p_values();
```

For an anova1 analysis all your experimental data should be stacked into the Y variable (e.g. 45x101 if three groups) and the A variable would be a 45x1 array of group labels e.g. [1,1,1,1,...2,2,2,2,....3,3,3,3]';

Mark
