### ISSUE TITLE
Calculate r-values from t-values obtained with spm1d

### ISSUE THREAD

**Issue by tramarobin** [0todd0000/spm1dmatlab#118]
Hi Todd,

First, thank you for this package, it really helps me with my data and bring new sights on my field.

I am using spm1d.stats.nonparam.regress on Matlab with a 2D-1D matrices (I have flatten the continum to perform 1D analysis). This function gave me t-values, and I would like to report r-values as they are more employed in my field. 

I have calculated r-values from t-values as there is an equation to do it in 0D : t=r √(n-2)⁄(1- r² ).
But as I'm using non parametrical tests, I do not know if it is correct to do it, or if there is another way to do it.
However, I still use the t-values and the t-threshold (zstar) to determine significativity. 

Thank you for your help,
Robin

**Comment by 0todd0000** [comment]
Hi Robin,

Thank you for the feedback!

The easiest way to get r values is to access them from SPM objects like in the code snippet below. This snippet is from the `./examples/stats1d/ex_regress.m` file.

```matlab
dataset = spm1d.data.uv1d.regress.SpeedGRF();
[Y,x]   = deal(dataset.Y, dataset.x);
spm     = spm1d.stats.regress(Y, x);
r       = spm.r;
```

r will be a (1xQ) array, where Q is the number of nodes in the 1D domain. (Q=101 in this example)

Todd

**Comment by tramarobin** [comment]
Thank you for your quick answer.
 
This method give me the same results but works a bit faster. 

Thank you again, I close the issue.
