### ISSUE TITLE
3D point cloud SPM1D

### ISSUE THREAD

**Issue by Little-Foot-Shapes** [0todd0000/spm1dmatlab#119]
Hi Todd, 

I was wondering if I could use the principle (flattening the 2D data into 1D) you mentioned in one of the closed issues, for 3D point clouds\triangulated surfaces, where I have data for each point\vertex. The point clouds are registered. Can I simply flatten out my 3D data and perform spm1d  on the points?

Thank you.

Best Regards
Mat

**Comment by 0todd0000** [comment]
Hi Mat,
Yes, **spm1d** can indeed be used to analyze 3D (or nD) data in this manner. Like the 2D examples below (from #61), the analyses must be limited to only (a) nonparametric procedures, and (b) field-level inference (i.e., cluster-level p values should not be used).
[Example 2D analysis (Python)](http://www.spm1d.org/doc/Stats2D/ex2d.html)
[Example 2D analysis (MATLAB)](http://www.spm1d.org/doc/Stats2D/ex2d_matlab.html)
Todd

**Comment by Little-Foot-Shapes** [comment]
Thank you. That is great!

**Comment by Little-Foot-Shapes** [comment]
Hi Todd, 

How do you think I should account for the multiple comparison problem, or is it already in the SPM1D? If yes, which one is used?

Thank you.

Best Regards
Mat

**Comment by 0todd0000** [comment]
This reply is more than one year late!  Sorry about this, I didn't see your follow-up question before now.
Nonparametric inference in **spm1d** handles the multiple comparison problem implicitly, by using the permutation distribution of the field-wide maximum. If this is unclear, please feel free to continue this discussion.
