### ISSUE TITLE
data2d.mat

### ISSUE THREAD

**Issue by gillianweir** [0todd0000/spm1dmatlab#120]
Hi Todd,
I hope you are well!
I am just following your 2D spm example and have downloaded the latest code from spm1d.org but I can't seem to find/load the 'data2d.mat' file. Is that online somewhere?
Thanks!
Gill

**Comment by 0todd0000** [comment]
Oops! Thanks for reporting the problem!
The MAT file was accidentally buried in an obscure folder in the spm1d.org website.
I've copied the data file to:
`./spm1dmatlab/examples/stats2d/data2d.mat`
Todd

**Comment by gillianweir** [comment]
Awesome! Thanks Todd!

 

Gillian Weir, PhD

Post-Doctoral Fellow (Biomechanics)

Department of Kinesiology | UMass Amherst

155 Totman Building | 30 Eastman Lane | Amherst, MA 01003-9258

M: (413) 588-8253  |  E:  <mailto:gweir@umass.edu> gweir@umass.edu |  @gillian_weir_
