### ISSUE TITLE
ROI needs zeros/ones vector instead of bool

### ISSUE THREAD

**Issue by pariterre** [0todd0000/spm1dmatlab#122]
Hello!

When using the nonparam anovas with the ROI tag, according to the example, we should send a vector of bool, while it actually needs vector of zeros and ones. I suggest that the examples are updated or the function accepts either zeros/ones or true/false values

Thanks!

**Comment by 0todd0000** [comment]
Hi, thank you for pointing out this problem!  And apologies for the confusion.

ROI analysis is actually not yet supported for nonparametric analysis (in the Matlab version of **spm1d**). I see now that the preliminary ROI parsers had not been properly cleaned up in the nonparametric ANOVA functions.  

I just updated the repository. Now the ANOVA functions should no longer allow the user to use the **'roi'** keyword.
