### ISSUE TITLE
Line Specifications for plot_meanSD

### ISSUE THREAD

**Issue by BDumphart** [0todd0000/spm1dmatlab#123]
Hi @0todd0000,

i am making some plots with spm1d.plot.plot_meanSD(...) and i thought about using different LineSpecs. Wouldn´t it be good to have different LineSpecs (for the mean as for the STD error Cloud? ) for example for colorblind people? Or is it already implemented and didn´t catch it? 
I, for myself, have changed your function in Matlab for LineSpecs but just wanted to give some input / feedback.

**Comment by 0todd0000** [comment]
Thank you for the feedback. I agree that it would be useful to have these features, and I've added this to the **spm1d** feature request list here:
https://github.com/0todd0000/spm1d/issues/45

If you've already changed the function, I'd love to add these changes to the repository. Please consider it uploading your edited  version as a [pull request](https://learn.co/lessons/github-pull-request-basics).
