### ISSUE TITLE
Error using examples

### ISSUE THREAD

**Issue by LaurenRWilliams** [0todd0000/spm1dmatlab#125]
Hi,
I am a novice MATLAB user and also new to SPM but eager to learn. I hope someone can help resolve the issue I am having. 

I downloaded the zip file from spm1d.org and tried to run the ex1d_ttest2.m example to check the installation. Every time I try to run it, I get this error:

Unrecognized function or variable 'spm_uc'.

Error in spm1d.rft1d.RFTCalculatorResels/isf (line 52)
            [u] = spm_uc(alpha, self.df, self.STAT, self.resels, self.n, self.Q);

Error in spm1d.rft1d.t.isf_resels (line 45)
            u = calc.isf(alpha);

Error in spm1d.stats.spm.SPM/get_critical_threshold (line 155)
                    zstar = spm1d.rft1d.t.isf_resels(a, v(2), res, 'withBonf',withBonf,
                    'nNodes',n);

Error in spm1d.stats.spm.SPM/inference (line 90)
            zstar        = self.get_critical_threshold(pstar, withBonf);

Error in ex1d_ttest2 (line 13)
spmi      = spm.inference(0.05, 'two_tailed',true, 'interp',true);

While this error is specific to this example, I get a similar error for all examples. I am using MATLAB R2020a and downloaded the most recent version of spm1d available as of 6/2/2020. Any help is greatly appreciated,
Lauren

**Comment by kernalnet** [comment]
Hi, 

Did you set that folder (and subfolders) to the MATLAB path?

Regards

**Comment by LaurenRWilliams** [comment]
Yes, I think so. Attached is an image showing my current folder. 
![folderpath](https://user-images.githubusercontent.com/66333351/83566680-a1f2e800-a4dd-11ea-9bef-ed243f8c5be6.PNG)

**Comment by kernalnet** [comment]
Have you tried this?
![image](https://user-images.githubusercontent.com/38867713/83567098-50c31280-a536-11ea-8caa-62bee510bde8.png)

**Comment by LaurenRWilliams** [comment]
That worked. Sorry for having such a simple issue. I greatly appreciate your help. Thank you!
