### ISSUE TITLE
Matlab 2020 Issue

### ISSUE THREAD

**Issue by Moh200jo** [0todd0000/spm1dmatlab#133]
Hi, 
I am new to the SPM1D although I enjoyed reading about it and I think it will be key analysis tool in biomechanics field. well done for this great work.
I have just started working with the examples on Matlab 2020 and I always get the following error for this line 
`spmi      = spm.inference(0.05, 'two_tailed', false, 'interp',true);`
**_Unrecognized function or variable 'spm_uc'._**

here is the spm:
`SPM{t}
         z: [1×101 double]
        df: [1 9]
      fwhm: 26.5475
    resels: [1 0.3390]`
Any idea why this error does present?

**Comment by 0todd0000** [comment]
Hello,
The `spm_uc.m` function is in the `./spm1dmatlab/spm8` folder, and this error means that Matlab can't find that function, and thus that the `spm8` folder has not been correctly added to the Matlab path. To solve this problem, use "add with subfolders" as described in the [installation instructions](https://spm1d.org/install/InstallationMatlab.html#label-installationmatlab).
