### ISSUE TITLE
SPM Parametric Paired ttest Error

### ISSUE THREAD

**Issue by sanam456** [0todd0000/spm1dmatlab#134]
Hi,
I have to run SPM analysis for parametric and non-parametric testing. I am getting accurate results with non parametric testing function but for parametric testing I am getting errors. Can you please tell what's the problem with parametric test?

rng(0)
alpha      = 0.05;
two_tailed = false;
iterations = 10000;
snpm       = spm1d.stats.nonparam.ttest_paired(yA, yB);
snpmi      = snpm.inference(alpha, 'two_tailed', two_tailed, 'iterations', iterations);

  spm       = spm1d.stats.ttest_paired(yA, yB);
  spmi       = spm.inference(alpha, 'two_tailed',two_tailed);                   #Problem here

Errors:
Unrecognized function or variable 'spm_uc'.

Error in spm1d.rft1d.RFTCalculatorResels/isf (line 52)
            [u] = spm_uc(alpha, self.df, self.STAT, self.resels, self.n, self.Q);

Error in spm1d.rft1d.t.isf_resels (line 45)
            u = calc.isf(alpha);

Error in spm1d.stats.spm.SPM/get_critical_threshold (line 155)
                    zstar = spm1d.rft1d.t.isf_resels(a, v(2), res, 'withBonf',withBonf, 'nNodes',n);

Error in spm1d.stats.spm.SPM/inference (line 90)
            zstar        = self.get_critical_threshold(pstar, withBonf);

Error in resultfigs_spm1d_Sana_Final (line 118)
  spmi       = spm.inference(alpha, 'two_tailed',two_tailed);

**Comment by 0todd0000** [comment]
Hello,

This error means that the Matlab path has not been set correctly, and that **spm1d** can not find the `spm_uc.m` function, which lies in the `./spm1dmatlab/spm8/` folder.

To solve the problem, you need to add the `./spm1dmatlab/spm8/` folder to the Matlab path. The easiest way to do this is: Set path.. Add with subfolders, then select `./spm1dmatlab/`, as described [in the Matlab installation document](https://spm1d.org/install/InstallationMatlab.html#label-installationmatlab).

Todd
