### ISSUE TITLE
Nonparametric Ttest twotailed

### ISSUE THREAD

**Issue by FraLau8** [0todd0000/spm1dmatlab#135]
Hello, 
I am trying to set up a nonparametric ttest for paired samples on my gait data.
somehow, it does not show two-tailed results, the ttest is only one-sided, although I looked it up in the examples.

can you tell me what the problem is? 
![SPM  ActiveKnee  abduction](https://user-images.githubusercontent.com/75481238/101161139-6a9df900-3630-11eb-981d-7e9e12032f8e.png)

Thank you very much.

Best regards, Laura

This is the code I used:

alpha      = 0.05;
two_tailed = false;
for ind_joint = 1:10
    for ind_dim = 1:3
        Frames = 300*(ind_joint-1)+100*(ind_dim-1)+(1:100);
        squeeze(All_vectors_of_int{ind_sub,ind_cond,ind_int}...
                 (:,Frames,ind_int))'; %>= 2 
        iterations = 1000;
        koppeleffekt       = spm1d.stats.nonparam.ttest_paired(Interval_1(:,Frames),Interval_2(:,Frames));
        koppeleffekti      = koppeleffekt.inference(alpha, 'two_tailed', two_tailed, 'iterations', iterations);
        disp(koppeleffekti)
        figure
        koppeleffekti.plot();
        koppeleffekti.plot_threshold_label();
        koppeleffekti.plot_p_values();
        title([Settings.JointNamesMirrod{UsedJoints(ind_joint)} '-' ...
            Settings.Dimensionsjoint{ind_dim}])
                export_fig(['results_Warm-Koppel' '\SPM' '  ' Settings.JointNamesMirrod{UsedJoints(ind_joint)} ...
                 '  ' Settings.Dimensionsjoint{ind_dim} '.png'])
   end
end

**Comment by 0todd0000** [comment]
If you change the second command to:

```matlab
two_tailed = true;
```

then the results should become two-tailed.

**Comment by FraLau8** [comment]
Thank you very much. I really should have seen this myself...
