### ISSUE TITLE
Plotting in both positive and negative directions 

### ISSUE THREAD

**Issue by jonnyireland83** [0todd0000/spm1dmatlab#138]
Hi Todd

Many thanks for the work on this.

I have been looking at the paired t-test example (spm1d.stats.ttest_paired) which has shows the difference in one direction. However, if i was to plot two loads for say velocity during countermovement jump at BW and 100%BW, is it possible to show differences in both directions ?

Kind regards

Jonny

**Comment by 0todd0000** [comment]
Hi Jonny,

Sorry for the delay.  I think a two-tailed test might be what you're looking for:

```matlab
spmi = spm.inference(0.05, 'two_tailed', true, 'interp', true);
```

(i.e., ensure that the `two_tailed` option is set to `true`)

Is this what you mean?  If not, could you attach a figure or two that describes the analysis goal?

Todd

**Comment by jonnyireland83** [comment]
Hi Dr Pataky

Thanks for the quick reply, it is highly appreciated.

Yes, this is what I was looking for. i managed to figure it out in the end

kind regards

Jonny
