### ISSUE TITLE
How to plot mean and 95% CI instead of Mean + SD

### ISSUE THREAD

**Issue by jonnyireland83** [0todd0000/spm1dmatlab#139]
Hi Todd

Many thanks for the work on this. I have been looking at the possibility of plotting mean and 95% CI instead of mean and SD on the paired t-test example (spm1d.stats.ttest_paired)

Is there a simpler way of plotting mean and 95% CI for both variableA and variableB?

<img width="713" alt="Screenshot 2021-02-15 at 10 56 46 PM" src="https://user-images.githubusercontent.com/78488004/107962460-f1ccfd00-6fe1-11eb-99ab-95000a0fba22.png">

I highly appreciate your time in advance

Regards

Jonny

**Comment by 0todd0000** [comment]
Hi Jonny,

The easiest way is to use one of the **spm1d.stats.ci_*** functions like this:

```matlab
alpha = 0.05;
ci    = spm1d.stats.ci_twosample(yA, yB, alpha);
ci.plot();
```

In the `./spm1dmatlab/examples/stats1d` folder please see these example scripts for more details including confidence interval options:

* `ex1d_ci_twosample.m`
* `ex1d_ci_onesample.m`
* `ex1d_ci_paired.m`

Todd

**Comment by jonnyireland83** [comment]
Hi Todd

Kind regards, thank you very much

Jonny

________________________________

**Comment by jonnyireland83** [comment]
Hi all

I am trying to change the colours of the shaded areas in the 95% CI on the c_paired test to black and grey for the purpose of submitting to a journal. Ive been trying, but I cant seem to be able to change the colours of the shaded area, although i can change the line color in the property inspector

any advice is much appreciated

Kind regards

Jonny

**Comment by 0todd0000** [comment]
I don't have Matlab with me write now, so can't confirm that this works, but I think you can use `color` (line color), `facecolor`  (cloud color) and `facealpha` (cloud transparency) to customize the plot like this:

```matlab
ci.plot('color', 'r', 'facecolor', 'b', 'facealpha', 0.5);
```

You could alternatively copy the source code into a new .m file to create a custom plotting function. Here is a quick modification of the `plot` function from `./+spm1d/+stats/+ci/CI1D.m`  (I've also not tested this code):

```matlab
function my_ci_plot(ci)
    y = ci.mean;
    h = ci.hstar;
    spm1d.plot.plot_errorcloud(y, h, 'facecolor', 'r', 'facealpha', 0.5);
    hold on
    plot(y, 'color','b', 'linewidth',3);
    if isscalar(ci.mu)
        plot([0 ci.Q-1], self.mu*[1 1], 'r--'); 
    else
        plot(0:ci.Q-1, ci.mu, 'r--'); 
    end
end
```
