### ISSUE TITLE
Plot mean + standard error instead of plot mean + standard deviation

### ISSUE THREAD

**Issue by ThomasBraeckevelt** [0todd0000/spm1dmatlab#141]
Dear Todd,

We have performed a kinematic analysis on 14 shoulders comparing a certain movement pattern in 5 different conditions on each shoulder.
Right now I've plotted the mean and standard deviation as shown in the picture below.
![image](https://user-images.githubusercontent.com/63154136/111319639-84ef6600-8666-11eb-9320-de463fbbb1f7.png)
Would there be a possibility to plot the mean and standard error instead? If so, how would I be able to use the code in my script?

I've searched the forum and your code examples but haven't found an answer. However, i'm only a matlab amateur trying to use your awesome work on SPM for orthopaedic research.

I was hoping if you could help me with this!

Thank you in advance!

**Comment by 0todd0000** [comment]
Hi, plotting standard errors is not directly supported in **spm1d**, but this can be done relatively easily using the `spm1d.plot.plot_errorcloud` function.

This is what the default `plot_meanSD` code looks like:

```matlab
m   = mean(Y,1);       % mean trajectory
s   = std(Y,1);        % standard deviation trajectory
x   = 0:numel(m)-1;    % continuum (time) points
h0  = plot(x, m, 'color','k', 'linewidth',2);    % plot mean trajectory
h1  = spm1d.plot.plot_errorcloud(m, s, 'facecolor','k', 'facealpha',0.25);  % plot SD trajectory
```

I recommend first trying the code above to ensure that you can replicate the results of `spm1d.plot.plot_meanSD`.

After that, you'd just need to calculate the standard error, then submit it to the `plot_errorcloud` function like this:

```matlab
m   = mean(Y,1);       % mean trajectory
s   = std(Y,1);        % standard deviation trajectory
n   = size(Y, 1);      % number of observations
se  = s / sqrt(n);     % standard error trajectory
x   = 0:numel(m)-1;    % continuum (time) points
h0  = plot(x, m, 'color','k', 'linewidth',2);    % plot mean trajectory
h1  = spm1d.plot.plot_errorcloud(m, se, 'facecolor','k', 'facealpha',0.25);   % plot SE trajectory
```

**Comment by ThomasBraeckevelt** [comment]
Thank you Todd!

It has been working perfectly!
