### ISSUE TITLE
3 Groups oneway ANOVA with matlab spm

### ISSUE THREAD

**Issue by jinhee615** [0todd0000/spm1dmatlab#142]
Hi todd. 
I'm a student studying Biomechanics, and trying to analyze my first experiment data with SPM.

I got data A, B, C with size of 15x101, 20x101, 14x101 .

To compare those variables, I made a code 

F=spm1d.stats.anova1(A,B,C);
Fi=spm.inference(0.05);
disp(Fi)

and substitution error occured..... 
Any Guideline for SPM anova? 

Thank you in advance

**Comment by 0todd0000** [comment]
Hello!

In MATLAB the only supported syntax for one-way ANOVA is:

```matlab
F = spm1d.stats.anova1(y, A);
```

where `y` and `A` are `(J,Q)` and `(J,1)` arrays, respectively. `y` is the data array, and `A` is an array of integer group labels.

`J` and `Q` are the numbers of observations and continuum nodes (time nodes), respectively, so in your case I believe `J=49` and `Q=101`.

To get it working try the following code:

```matlab
y          = [A; B; C];
[nA,nB,nC] = deal( size(A,1), size(B,1), size(C,1) );
group      = [ 1*ones(nA,1) ; 2*ones(nB,1) ; 3*ones(nC,1) ];

F          = spm1d.stats.anova1(y, group);
```

**Comment by jinhee615** [comment]
Thank you so much! Problem solved :) and one more question is, I want to know the exact point where SPM graph meets threshold line, and p-value of colored period. Would it be possible?

**Comment by 0todd0000** [comment]
Yes, this is possible through the `clusters` attribute of SPM inference objects. Here is some example code:

```
dataset = spm1d.data.uv1d.t1.Random();
[y,mu]  = deal(dataset.Y, dataset.mu);

spm       = spm1d.stats.ttest(Y - mu);
spmi      = spm.inference(0.05, 'two_tailed',false);

disp( spmi.clusters )
```

Output:

```
    [1×1 spm1d.geom.Cluster]
```

This indicates that there is one supra-threshold cluster. To see details regarding this cluster, enter the following:



```
disp( spmi.clusters{1} )
```

Output:

```
  Cluster with properties:

    endpoints: [15.0451 18.2800]
        csign: 1
    iswrapped: 0
       extent: 3.2348
      extentR: 0.2872
            h: 3.8213
           xy: [16.8650 3.8776]
            P: 0.0310
```

**Comment by jinhee615** [comment]
Thank You So much, Todd!! I learned a lot!
