### ISSUE TITLE
3x3 two way ANOVA

### ISSUE THREAD

**Issue by jinhee615** [0todd0000/spm1dmatlab#143]
Hello!

I'm trying to make sure a 3x3 two way ANOVA works.

I have three groups and three conditions. Group Is N, I, O, condition is same as N, I, O.
So I have 9 sets of data, called NN, NI, NO / IN, II, IO / ON, OI, OO each.

![image](https://user-images.githubusercontent.com/82136393/114120961-81c75d00-9928-11eb-9f93-bb580b8b76cf.png)

than in case 3x3, How many datasets are required? 
as far as I know spm anova2 requires 3 sets of data, but i wonder how can i adjust it in case 3x3.

Y1=[NN ; IN; ON]; 
Y2=[NI ; II ; OI];
Y3=[NO ; IO ; OO];
spm = spm1d.stats.anova2(Y1,Y2,Y3,B)  <-B is group data

Is it appropriate? 

Thanks in advance 👍

**Comment by 0todd0000** [comment]
The required syntax for two-way ANOVA is:

```
spm1d.stats.anova2(y, A, B);
```

where `y`, `A` and `B` are `(J,Q)`, `(J,1)` and `(J,1)` arrays, and where `J` and `Q` are the numbers of observations and continuum (time) nodes, respectively. `y` is the data array, and `A` and `B` contains integer labels which specify groups.

As an example, please refer to:
`./spm1dmatlab/examples/stats0d/ex_anova2.m`

where you will find code like this:

```
dataset = spm1d.data.uv0d.anova2.Satisfaction();
[y,A,B] = deal(dataset.Y, dataset.A, dataset.B);
F  = spm1d.stats.anova2(y, A, B);
```

This link in `dataset` is [http://faculty.webster.edu/woolflm/8canswer.html](http://faculty.webster.edu/woolflm/8canswer.html).

From this link and the `A` and `B` contents in the code snippet above, it should be clearer how `A` and `B` should be constructed for arbitrary datasets.

**Comment by jinhee615** [comment]
Should dataset same as SPSS form?

For example, I have 3 groups of 2,2,3 patients each.
Three Groups, Three Conditions. (3x3)
I wonder Dataset A, B is same as SPSS form like in this picture.
So Datasets A and B are 2*3+2*3+3*3=21 rows. Is this right?

![image](https://user-images.githubusercontent.com/82136393/114799946-c09b5e00-9dd3-11eb-9001-c620f2a6a606.png)

**Comment by 0todd0000** [comment]
> Should dataset same as SPSS form?

The data has to be arranged differently than in SPSS. The code in `ex_anova2.m` demonstrates how the data should be arranged. Is there a particular aspect of this example that is unclear?

> For example, I have 3 groups of 2,2,3 patients each.

There are two critical problems:

1. Sample sizes are too small. In general there should be about 5 or more patients in each group.
2. This is an unbalanced design. **spm1d** currently only supports balanced designs (in this case:  the same number of patients in each group).



> F=smd1d.stats.anova2(y, subj, condition) or F=smd1d.stats.anova2(y,condition,subj)
which one is correct?

These should yield equivalent results.

> I want to know where the significance appears. Where bold line meets threshold.
Like I could know using "disp(spmi.clusters{1})" when I using anova1.

I do not understand this question, can you please rephrase?

> I want to display plot with 1x3 subplot using ANOVA2. anova code manually makes 2x2 plot. how can I change it?

You can achieve this by plotting individual SPM objects like this:

```matlab
spmlist   = spm1d.stats.anova2(y, A, B);
spmilist  = spmlist.inference(0.05);

figure
set(gcf, 'Position',  [0, 0, 800, 200])
subplot(131);  plot( spmilist(1) )
subplot(132);  plot( spmilist(2) )
subplot(133);  plot( spmilist(3) )
```

**Comment by jinhee615** [comment]
Sorry that I confuse you, and Thank you for your kind answer 👍 

I mean, I want to know the point where the significance appears. The exact point where SPM line meet its threshold.
in one-way ANOVA, I could confirm it with disp(spmi.clusters{1}). 
Now I'm trying to run two-way ANOVA, so I wonder Is there any way to find it out.
In case you couldn't understand(because I'm not used to writing in English), I added a picture.

![image](https://user-images.githubusercontent.com/82136393/114858161-126bd480-9e24-11eb-80f8-058ff2b65144.png)

**Comment by 0todd0000** [comment]
You can get cluster details, including the endpoints, by accessing the `clusters` property of an **individual** SPM object. Note that ANOVA procedures return multiple SPM objects (one for each main effect, and one for each interaction effect). You must access a single SPM object to get its cluster details. For example:

```matlab
spmi = spmilist(2);
x    = spmi.clusters{1}.endpoints;
```

**Comment by jinhee615** [comment]
Thanks a lot! I can find it now 👍
