### ISSUE TITLE
unbalanced repeated measures anova

### ISSUE THREAD

**Issue by dbeeler90** [0todd0000/spm1dmatlab#145]
Is there MATLAB code for a repeated measures anova design with a between subjects factor (and interaction)? I have 101 point time series normalized data for several variables in two unequal groups across three time points. Is this possible to analyze in MATLAB? I am getting an unbalanced error code. (I'm relatively new to matlab and SPM in general). Any thoughts are appreciated. Thanks.

**Comment by 0todd0000** [comment]
Yes, I think `spm1d.stats.anova2onerm` would be appropriate. This models just one RM factor, which sounds like the design you describe.

Regarding the error: unbalanced designs are currently not supported in **spm1d**. In this case the error means that there must be the same number of subjects in each group. There are nevertheless ways to impose balance and retain robust analysis.  Please refer to previous forum discussions regarding unbalanced designs here:

* https://github.com/0todd0000/spm1dmatlab/issues?q=unbalanced
* https://github.com/0todd0000/spm1d/issues?q=unbalanced

**Comment by dbeeler90** [comment]
Thank you for your quick response. I will explore these options for my analysis. From what I gather, there does not appear to be an acceptable approach for post-hoc testing using spm1d, is that correct? The only approach I can see on spm1d.org is for one-way ANOVA. This is very interesting stuff, I appreciate you and your team!

**Comment by 0todd0000** [comment]
Thank you for the feedback!

Bonferroni corrections are acceptable (and valid) for *post hoc* testing, including *n*-way ANOVA. The only problem is that using a simple Bonferroni approach may not produce results that completely agree with the original ANOVA results.

Please regard ANOVA results as the main results, and *post hoc* results as complimentary results whose main purpose is to explain the ANOVA results.

**Comment by dbeeler90** [comment]
Hi Todd,

In attempting to balance the between-subjects factor in my analysis, I thought I would be able to use the anova2onerm method. The control and experimental group are the same n size; however, only the experimental group has repeated-measures (three data analysis points). I'm getting unbalanced design errors, regardless of how I code the groups. Would having only one group with repeated-measures prevent this analysis from executing properly?

**Comment by 0todd0000** [comment]
Yes, you might want to try a one-way repeated measures ANOVA ( `spm1d.stats.anova1rm` ) on just the experimental group. If the goal of the experiment is to determine effects related to the three time points, then this one-way ANOVA should be sufficient, without the need for the control group.
