### ISSUE TITLE
parametric and non parametric approach

### ISSUE THREAD

**Issue by jinhee615** [0todd0000/spm1dmatlab#147]
Hi. I have 3x3 two way repeated ANOVA design, I ran spm1d.stats.anova2onerm.

As you recommended in last questions #144 , I ran spm1d with fctSPM.

But spm1d interaction clusters and fctSPM posthoc graph showed different answer. As two code suggest different section of interaction, fct forum suggested that it is because spm1d is parametric, and fctSPM is non-parametric approach.

![image](https://user-images.githubusercontent.com/82136393/117238366-b0711e80-ae67-11eb-9640-beadbe43edf4.png)
(spm1d showed 0-14, 18.7-28, 85-88, 96-100% interaction, But above image(fctSPM) showed difference.) 

My data is continuous, and following timeseries, have enough patients. In this case, can I use spm1d and fctSPM both or do I have to choose between them?

**Comment by 0todd0000** [comment]
Here are a few points to consider...

Parametric and non-parametric analyses:
- **spm1d** supports both parametric and nonparametric analyses
- **fctSPM** supports only nonparametric analysis
- **fctSPM**'s probability calculations are performed in **spm1d** (i.e., **fctSPM** provides a high-level interface to **spm1d** for automating complex analyses)
- Parametric and nonparametric analyses are complimentary but can usually not be directly compared

*Post hoc* analyses:
- There are generally no procedures for obtaining perfect agreement between *post hoc* analyses and main tests
- **fctSPM** automates *post hoc* analyses, but does not guarantee perfect agreement between main tests and *post hoc* results, even when all analyses are nonparametric

General SPM results interpretation:
- The main results of SPM analyses do not pertain to a specific point in time
- While it is tempting to interpret "time = 0-14%" and "time=15-100%", for example, as "significant" and "non-significant" respectively, this interpretation is not strictly consistent with what SPM is actually testing
- In the case of a two-sample test, SPM tests the hypothesis H0: mean_A = mean_B, where mean_A and mean_B are mean continua, and where the hypothesis testing results pertain directly only to this hypothesis (and not a hypothesis about time=0-14%, for example).

Overall recommendations:
- Please do not expect to achieve perfect correspondence between *post hoc* results and main tests
- Please regard SPM results as testing hypotheses regarding whole continua, and not specific portions of those continua

<br>
<br>
<br>

>  In this case, can I use spm1d and fctSPM both or do I have to choose between them?

- In general I would always recommend: (1) conduct both parametric and non-parametric analyses, and (2) explain any qualitative differences that arise in parametric vs. parametric results
- In this case I'd suggest running all of: parametric analysis in **spm1d**, non-parametric analysis in **spm1d**, and non-parametric analysis in **fctSPM**.  If there is general qualitative agreement amongst all results, then great!  This means you can report any one of the results, or all of the results, and it will not affect the interpretation of those results.  If, however, there is disagreement amongst the results, you should explain why.
- "Disagreement amongst the results" does not pertain to specific time points (e.g. "0-14%" vs. "0-19%");  instead it pertains to hypothesis rejection decisions, as these are the main results.  This type of disagreement would be expected to occur only in cases of (i) relatively strong non-normality, and/or (ii) small sample sizes.

**Comment by jinhee615** [comment]
Thank you so much. I understood.

Does SPM1d conduct Normality test automatically? ( i use anova2onerm code. )
with 3x3 two way ANOVA, How many sample size are needed? 

> * In the case of a two-sample test
How about in 3x3 two-way ANOVA SPM1d ?
-If Main Effect was observed : dependent variable is affected by Its each Group(or Condition). is right?

**Comment by 0todd0000** [comment]
> Does SPM1d conduct Normality test automatically? (

No, you must use the procedures in `spm1d.stats.normality` for testing normality.

<br>
<br>

> How many sample size are needed?

An hypothesized effect size is needed to answer this question. Please refer to the following resources:

- [Sample size estimation for biomechanical waveforms: Current practice, recommendations and a comparison to discrete power analysis](https://doi.org/10.1016/j.jbiomech.2021.110451)
- [Sample size calculations in power1d](https://spm1d.org/power1d/Examples/SampleSize.html)

<br>
<br>

> If Main Effect was observed : dependent variable is affected by Its each Group(or Condition). is right?

Yes, this is correct. *Post hoc* analyses are needed to determine which groups' differences produce this main effect.
