### ISSUE TITLE
Spatial autocorrelation

### ISSUE THREAD

**Issue by Little-Foot-Shapes** [0todd0000/spm1dmatlab#149]
Hi Todd, 

I was wondering if there was a way to perform autocorrelation in SPM1D. I have my 3D foot scans with shape data at each point and wanted to see if there was a relationship between shapes of different areas of the foot.
Any suggestions as to how to get started with this?

Thank you.
Mat

**Comment by 0todd0000** [comment]
This is indeed possible in SPM in general, but this is unfortunately not implemented in **spm1d**.  In the Neuroimaging literature this is referred to as "connectivity analysis". If you're interested in the details and/or implementing it, a good review article is Friston (2011).

Friston, K. J. (2011). Functional and effective connectivity: a review. Brain Connectivity, 1(1), 13-36.

**Comment by Little-Foot-Shapes** [comment]
Thank you!
