### ISSUE TITLE
Bonferroni Correction Implementation for Post Hoc Tests

### ISSUE THREAD

**Issue by jrwud** [0todd0000/spm1dmatlab#150]
Hello,

I've run into some confusion about how to properly implement a Bonferroni correction for post hoc tests and was wondering if someone could clarify! Specifically, after running an ANOVA, I am doing 5 post hoc tests, thus I adjusted the critical p-value using the following:

alpha = 0.05;
nTests = 5;
p_critical = spm1d.util.p_critical_bonf(alpha,nTests);

My confusion comes from https://spm1d.org/doc/PostHoc/anova.html which seems to imply that after I adjust the critical p-value using the above lines of code, I would need to also adjust the p-values from the resulting suprathreshold clusters for each test. Am I interpreting this correctly? Or should I only do one or the other (aka either the above lines of code or keeping alpha at 0.05 but adjusting the p-values to be relative to that)? If I do both some of these p-values would exceed the newly adjusted alpha level (aka p_critical = 0.01 and p = 0.023), should I then state that the reported p-values are relative to the alpha level of 0.05 across all the tests?

Thanks, 
Jack

**Comment by 0todd0000** [comment]
You confusion is understandable!  I'd say: yes, both (a) a critical threshold correction and (b) individual p values are necessary, but (a) is much more important than (b).

Consider the following case:

- Two independent tests
- A Bonferroni correction is used to adjust the critical p value to about 0.025
- After applying the adjust threshold, one (uncorrected) p value of 0.024 remains

In this case, the p value lies just below the critical threshold. It would be best to correct the p value (to about 0.048) to emphasize this p value's relation to the original threshold of alpha=0.05.

From a null hypothesis rejection perspective, the hypothesis is rejected regardless of whether the p value is corrected. Thus the only real danger of not correcting p values, is that they appear small to readers who wish to interpret them relative to alpha=0.05.

In many software packages (like SPSS), both critical threshold corrections and p corrections are automated, allowing the user to interpret the (corrected) p values relative to alpha.

**Comment by jrwud** [comment]
Ah that makes sense! Thank you!
