### ISSUE TITLE
ANOVA and adjusting for variable (gait speed)

### ISSUE THREAD

**Issue by ArjS21** [0todd0000/spm1dmatlab#152]
Hi, 

I am assessing differences in joint angles and moments during gait between timepoints using a one way ANOVA. 
(https://spm1d.org/doc/Stats1D/anova.html#one-way-anova).

I would like to correct for gait speed for each participant. How can I go about this?

Thankyou very much,
A

**Comment by 0todd0000** [comment]
One way to do this is using the **spm1d.stats.glm** function:
https://spm1d.org/doc/Stats1D/onetwosample.html#general-linear-model-glm

You can model an arbitrary number of continuous and categorical variables. Using gait speed as one of the continuous variables will effectively remove speed-related effects from the other factors.

Notes:
- **spm1d.stats.glm** currently supports only t contrasts (i.e., vector contrasts), which are analogous to *post hoc* tests for ANOVA;  see the link above for an example of a t contrast.
- The normal contrasts for ANOVA are F contrasts (i.e., matrix contrasts), but these are unsupported in the current version of **spm1d**.
- You will need to correct for multiple comparisons across the *post hoc* tests. The easiest way to do this is to adjust α using α / *n* , where *n* is the number of *post hoc* tests.

Please find more details relevant to **spm1d.stats.glm** in the following discussions:
- #39
- #20
- #15

**Comment by ArjS21** [comment]
Hi Todd, 

Thankyou for your swift response! The information here was very useful and I've managed to run my analysis with the GLM. 

A question regarding correcting for multiple comparisons. I understand that the GLM looks at correlations between all modeled variables. To analyse regions of significant difference in a particular measure (e.g hip flexion, hip flexion moment) between two time points, I have separate models for each measure to compare them directly. If I am including the gait speed as a covariate, is this considered another test I must correct for?

**Comment by 0todd0000** [comment]
Good! I'm glad that the GLM approach is working.

If the tests are not *post hoc* tests, then:
- Every call to an **spm1d.stats** procedure should be regarded as a separate test.
- If using **spm1d.stats.glm**, each contrast should be regarded as a separate test. 

It is advisable to correct for multiple comparisons across those tests.

**Comment by ArjS21** [comment]
I see, thankyou. Just to clarify, does this include the intercept, as it's included in the contrast vector?

**Comment by 0todd0000** [comment]
If an intercept is modeled in the design matrix (i.e., usually as a column of constants), then it represents an experimental design variable just like every other column. Since a contrast vector represents a null hypothesis, the intercept (like other design variables) can be included or excluded from that hypothesis.

**Comment by ArjS21** [comment]
Okay, thankyou for clearing that up. I appreciate your help!
