### ISSUE TITLE
paired_ttest - MATLAB

### ISSUE THREAD

**Issue by rude10** [0todd0000/spm1dmatlab#153]
Hi

I am new to this toolbox and just confirming...  I am doing a paired sample t-test for some continuous treadmill data I have (pre and post) for 10 persons. The intention is to check normality, complete the ttest followed by cohen's d. 

For normality do I use:

spmi1  = spm1d.stats.normality.ttest_paired(YA, YB).inference(alpha);
spmi2  = spm1d.stats.normality.ttest_paired(YA, YB).inference(alpha);

### **OR**

spm1d.stats.normality.sw (y, x);

Then a paired t-test using:

%paired t-test
% spm=spm1d.stats.ttest_paired(Y1,Y2);
% spmi=spm.inference(0.05,'two_tailed',true,'interp',true);

I would like to confirm that the normality uses the difference between the pair of data means as the testing variable. So for example s1 represents mean steps before intervention and s2 represents mean steps post-intervention. Normality test (s2-s1)

For paired t-test is it just the means being evaluated? pairedtest (s1,s2)
Also is there is a cohen's d in this toolbox that can be utilized?

**Comment by 0todd0000** [comment]
I'd suggest using just:

```octave
spmi = spm1d.stats.normality.ttest_paired(YA, YB).inference(alpha);
```

In **spm1d**, calls to all normality tests are the same as the call to the test itself, so if the test name is `ttest_paired`, then the test itself can be run as:

```octave
spmi = spm1d.stats.ttest_paired(YA, YB).inference(alpha);
```

and you just need to add `normality` after `spm1d.stats` to run the normality test. 

<br>
<br>

> I would like to confirm that the normality uses the difference between the pair of data means as the testing variable. So for example s1 represents mean steps before intervention and s2 represents mean steps post-intervention. Normality test (s2-s1)

All normality tests consider only the residuals. For t tests the residuals are the differences from the means. For a paired t test: first the A-B difference is calculated for the `i`th subject as `d_i = YA_i - YB_i` , then the residuals are calculated for each subject as `r_i = d_i - mean_d`, where `mean_d` is the mean difference across subjects.

<br>
<br>

> Also is there is a cohen's d in this toolbox that can be utilized?

No, there is not yet any direct support for effect sizes in **spm1d** because effect size interpretations for 1D data are different than for simple scalar data. An effect that would be interpreted as "large" for simple scalar data may only be interpreted as "medium" or "small" for 1D data. The reason for this can be stated most concisely as "isoprobability", or slightly less concisely as: "probabilistically equivalent effect size thresholds". We are currently preparing a paper which considers this issue in detail, and future versions of **spm1d** will support effect size calculations.

**Comment by rude10** [comment]
Hi thanks for response. So you are saying that for:


"All normality tests consider only the residuals. For t tests the residuals
are the differences from the means. For a paired t test: first the A-B
difference is calculated for the ith subject as d_i = YA_i - YB_i , then
the residuals are calculated for each subject as r_i = d_i - mean_d, where
mean_d is the mean difference across subjects."

I'd just need to use the below provided that column lengths are even if
normalized to 101 data points? Or does it take the data as 101 columns also
and I'd need to invert in Matlab? Note currently each column of data in s1
or s2 would represent data for each TD event normalized so even amount of
rows.

spmi = spm1d.stats.normality.ttest_paired(s1, s2).inference(alpha);


Regards,

Rudy

**Comment by 0todd0000** [comment]
`s1` and `s2` must both be `(J,Q)` arrays, where `J` is the number of observations, and `Q` is the number of time nodes. In your case it sounds like `J=10` and `Q=101`.

I'm not sure what you mean by "invert in Matlab"?

**Comment by rude10** [comment]
Hi Todd

Thanks, I meant I'd need to invert in array in Matlab since the default
after normalization is to have 101 rows but you answered the query.

Appreciate it.

Regards,

Rudy

**Comment by rude10** [comment]
Hi Todd

I am getting the following error messages when I try to run two data sets
in SPM from Matlab. It is looking at vGRF (normalized) and it is 10*1001
normalized data. is there  troubleshooting manual online also?

Warning: Returning NaN for out of range arguments
> In spm_invGcdf (line 90)
  In spm_invXcdf (line 57)
  In spm_u (line 41)
  In spm_uc_RF (line 30)
  In spm_uc (line 39)
  In spm1d.rft1d.RFTCalculatorResels/isf (line 52)
  In spm1d.rft1d.chi2.isf_resels (line 44)
  In spm1d.stats.spm.SPM/get_critical_threshold (line 157)
  In spm1d.stats.spm.SPM/inference (line 90)
  In test10vRH_GlobalStride (line 430)
Index exceeds matrix dimensions.

Error in toeplitz (line 26)
  c(1) = conj(c(1));                    % set up for Hermitian Toeplitz

Error in spm_P_RF (line 77)
P       = triu(toeplitz(EC'.*G))^n;

Error in spm_uc_RF (line 37)
    [P P p] = spm_P_RF(1,0,u,df,STAT,R,n);

Error in spm_uc (line 39)
u = spm_uc_RF(a,df,STAT,R,n);

Error in spm1d.rft1d.RFTCalculatorResels/isf (line 52)
            [u] = spm_uc(alpha, self.df, self.STAT, self.resels, self.n,
self.Q);

Error in spm1d.rft1d.chi2.isf_resels (line 44)
            u = calc.isf(alpha);

Error in spm1d.stats.spm.SPM/get_critical_threshold (line 157)
                    zstar = spm1d.rft1d.chi2.isf_resels(a, v(2), res,
'withBonf',withBonf, 'nNodes',n);

Error in spm1d.stats.spm.SPM/inference (line 90)
            zstar        = self.get_critical_threshold(pstar, withBonf);

Error in test10vRH_GlobalStride (line 430)
spmi2  = spm1d.stats.normality.ttest_paired(s2, s2).inference(alpha)

Regards,



Rudy

**Comment by 0todd0000** [comment]
I think the problem is that you've used `s2` twice in the command:

```octave
spmi2  = spm1d.stats.normality.ttest_paired(s2, s2).inference(alpha)
```

Using `s2` twice will cause all pairwise differences to be zero, and this is likely causing the error.

**Comment by rude10** [comment]
Hi Todd

Thanks I had spotted error earlier today
...was probably super exhausted. Question,  is there a minimum limit for
the number of participants in the trial to successfully run both the
normality and or t-tests using SPM?

Regards,

Rudy

**Comment by rude10** [comment]
Also,

I see there is some stuff about non-parametric tests. In the previous
email, you suggested doing the normality test within the ttest_paired
function. What about if the distribution is small (5 persons) with
continuous data (101 points).

So I use the new Shapiro-Wilk and then there is a separate non-parametric
option recommended if the distribution is not normal?

Regards,



Rudy

**Comment by 0todd0000** [comment]
Hello,
- I've routed your sample size question to a new issue: #154.  (Just for bookkeeping purposes, to separate issues and make information easier to find for other users.)
- Regarding nonparametric analyses, I think that #147 may address your question. If it doesn't, please create a new issue.

Todd
