### ISSUE TITLE
Plotting multiple graphs

### ISSUE THREAD

**Issue by MarkKramer** [0todd0000/spm1dmatlab#159]
Dear colleage,

I have made use of the Matlab version of SPM1d to complete a paired t-test and it works perfectly. I would however like to plot the spm1d results for both velocity, force, and power data, but I don't seem to be able to do this? 

The problem seems to come from the following code:

nexttile;
spmi.plot();
spmi.plot_threshold_label();
spmi.plot_p_values();
xlabel("Normalised Time [%]");
ylim([-9 5]);
box on;
title('Hypothesis test')

I would make use of this code for the results for the velocity data, but cannot seem to repeat this for the force and power data? Is there a way around this?

At the end I should have a figure consisting on 3 rows and 2 columns whereby the first column shows the data comparisons (mean and SD), and the second column shows the spm1d results.

I have included the relevant Matlab code (in a word document), the intended figure, as well as the relevant datafiles for reference.

Any help/advice would be greatly appreciated. Thank you kindly in advance.

Regards,

Mark

[Data_Force_3MT.csv](https://github.com/0todd0000/spm1dmatlab/files/7854521/Data_Force_3MT.csv)
[Data_Force_40m.csv](https://github.com/0todd0000/spm1dmatlab/files/7854523/Data_Force_40m.csv)
[Data_POWER_3MT.c
![FVPDataCombinedSPM1dV2](https://user-images.githubusercontent.com/17684291/149140943-8d57eec1-c194-4023-8e60-e4a765bb56e2.png)
sv](https://github.com/0todd0000/spm1dmatlab/files/7854524/Data_POWER_3MT.csv)
[Data_POWER_40m.csv](https://github.com/0todd0000/spm1dmatlab/files/7854525/Data_POWER_40m.csv)
[Data_sprint_3MT.csv](https://github.com/0todd0000/spm1dmatlab/files/7854526/Data_sprint_3MT.csv)
[Data_sprint_40m.csv](https://github.com/0todd0000/spm1dmatlab/files/7854527/Data_sprint_40m.csv)
[Paired T-Test SPM1d Analysis - Help Needed.docx](https://github.com/0todd0000/spm1dmatlab/files/7854545/Paired.T-Test.SPM1d.Analysis.-.Help.Needed.docx)

**Comment by 0todd0000** [comment]
Hello!  I think the problem is your inference calls, which appear like this:

```octave
spm       = spm1d.stats.ttest_paired(df_3MT, df_40m);
spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);

spm2      = spm1d.stats.ttest_paired(df_force_3MT, df_force_40m);
spmi2     = spm.inference(0.05, 'two_tailed', true, 'interp',true);

spm3      = spm1d.stats.ttest_paired(df_power_3MT, df_power_40m);
spmi3     = spm.inference(0.05, 'two_tailed', true, 'interp',true);
```

<br>

Notice that all `inference` commands operate on the `spm` variable, which corresponds only to the first dataset. So try updating the `inference` commands like this:

<br>

```octave
spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);    % no change
spmi2     = spm2.inference(0.05, 'two_tailed', true, 'interp',true);   % "spm" changed to "spm2"
spmi3     = spm3.inference(0.05, 'two_tailed', true, 'interp',true);   % "spm" changed to "spm3"
```

**Comment by MarkKramer** [comment]
Thank you this is exactly what I was looking for. It worked 100%.
