### ISSUE TITLE
bootstrapping for imbalanced data? 

### ISSUE THREAD

**Issue by kfheise** [0todd0000/spm1dmatlab#16]
Dear Todd, 
I am facing a decent amount of imbalance in my dataset, i.e. a different number of trials per condition and subject. My data consists of roughly 10.000 single trials of my kinematic outcome measured over 600 sampling points. The number of runs for each condition/subject varies between 5 and 35. 

I am therefore very reluctant to average across conditions/subjects neither would I arbitrarily exclude trials. I would rather chose a bootstrapping approach that makes use of all available data that I have. Unfortunately, I am interested in analysing the effect of 3 different factors on my outcome, i.e. running a rather complex 3-way ANOVA model would be the ideal case.
Has something like this already implemented in the latest developments of spm1d? 

I am very much appreciating any hint to solve this issue. 
Many thanks in advance.
Kirstin

**Comment by 0todd0000** [comment]
Hi Kirstin,

Thanks for your question.  I believe the current code only can deal with balanced data, but multiple trials per subject are fine, so if you could reduce the dataset to five or more trials for all conditions I think the **spm1d** results will be accurate.

Averaging across trials can indeed be problematic, but from what I understand those problems usually arise when within-subject variability is large with respect to between-subject variability.  In most Biomechanics datasets I've seen between-subject variability is much larger, so averaging is less of a problem.

The next major release of **spm1d** will support non-parametric inference (including bootstrapping), which should provide a robust way of handling all data.  We may eventually implement support for unbalanced designs as well, but I expect that non-parametric results will support the forced-balancing approach for many datasets.

In the meantime I wonder if it would be possible to export a particular value (e.g. value at time=50%) and then use another package like SPSS or R to:

- analyze the entire unbalanced dataset 
- re-analyze using a reduced balanced dataset 

If those two sets of results do not differ greatly, then that should give you some confidence in using the reduced dataset along with **spm1d**.

Todd

**Comment by kfheise** [comment]
Thank you, Todd. 
I definitely would appreciate if using all available data would be possible. In particular since my experimental condition might induce increased variance. But I will take a careful look into your suggestions.
