### ISSUE TITLE
two-sample t test using group means for between groups comparison. 

### ISSUE THREAD

**Issue by ArjS21** [0todd0000/spm1dmatlab#160]
Hi,

I'm assessing differences in gait biomechanics between different treatment groups at two separate timepoints using a GLM. I have this part sorted. I would also like to compare differences between groups in the amount of change occuring between timepoints. Due to the nature of the study, several participants were not able to attend both timepoints, only one or the other. So for each treatment group, I have calculated a mean change and std dev for the difference between sample means using the data from the two timepoint. 

I would like to conduct a two-sample t-test using these mean changes for each intervention group. How can I go about this? 

Thankyou very much,
A

**Comment by 0todd0000** [comment]
It sounds like this is a repeated measures (RM) design, where each participant performs in multiple measurement sessions, possibly on separate days. If this is correct, then it is probably a one-way RM-ANOVA ( `spm1d.stats.anova1rm` ) or possibly a paired t-test ( `spm1d.stats.ttest_paired` ) if there are just two sessions.

However, if some participants were not measured during all sessions, then there is missing data. In **spm1d**, RM analyses cannot be run with missing data, so the only way to proceed with **spm1d** would be to remove those participants.

**Comment by ArjS21** [comment]
A paired t-test would certainly be one approach which I had considered although I would have to remove participants within each treatment group that were not measured at all sessions. Alternatively, I had thought that given it is a between groups comparison, it would be valid to compare the means from each treatment group using an independent two-sample t-test. The problem is that both YA and YB (mean change for treatment A and treatment B) would be a [1x101] matrix and I'm unsure whether it would be possible to run this using SPM?
If it's not possible to compare the 2 group means with a two sample t-test then I'll have to use a paired t-test.

**Comment by 0todd0000** [comment]
Multiple observations are necessary for all statistical procedures, including SPM procedures, so if the data array is `[nx100]`, then `n` should generally be 5 or greater. If you have two `[nx100]` values --- one for each group --- then the only quantity that can be calculated is the difference between those two values.
