### ISSUE TITLE
Two Way ANOVA Post Hoc Interpretation

### ISSUE THREAD

**Issue by NicHunt** [0todd0000/spm1dmatlab#163]
Hi there,

I have designed a 2x3 [Group x Condition] two-way ANOVA with 24 subjects. Group A/B (Age) negotiating stairs under three conditions (Surfaces) with all data time-normalized to 100% of stance. 

I used spm1d.stats.anova2onerm(Y, A, B, SUBJ) to test between groups and conditions. The resulting figure looks as follows: 

![SPM SU Main Effect](https://user-images.githubusercontent.com/99830189/154330953-beb935aa-ba25-4f7d-b833-6d120125177f.png)

The two supra-threshold clusters make sense with the anticipated results for 'Main B' (conditions/surfaces). Following these results, I ran three post-hoc tests with alpha = 0.05 between each surface using the following code:

![image](https://user-images.githubusercontent.com/99830189/154330825-2d5c1b8c-b16c-4cbc-932b-b94520f84575.png)

This led to the following results:

![SPM SU Post Hoc](https://user-images.githubusercontent.com/99830189/154331128-f39214c7-1c29-4ac7-a1f5-21067f1343f7.png)

Interestingly, the post-hoc analysis does no support the main effect findings as there are no supra-threshold clusters in any of the post-hoc plots. My question is regarding why the post-hoc does not support the main effect findings. Is the implemented post-hoc design too simple or conservative to find significant differences between each specific condition? Is there an error in my design or implementation of this post-hoc method? Should I explore different post-hoc methods?

I am currently using this analysis for my master's thesis so any help or advice would be greatly appreciated. Thank you for the open source code and thorough documentation!

**Comment by 0todd0000** [comment]
I am not sure if this will solve the issue, but try **spm1d.stats.ttest_paired** instead of **ttest2**.  The **anova2onerm** procedure models the second factor (B) as repeated-measures (RM), so *post hoc* tests should also be RM (i.e., paired). Depending on how the data are organized, you may need to shuffle the rows of `Y1`, `Y2` and `Y3` to ensure that row `i` in each `Y` variable represents the same subject.

**Comment by NicHunt** [comment]
Running the paired t-test seemed to do the trick. Thank you so much for the quick response!
