### ISSUE TITLE
One-way RMANOVA post-hoc analysis

### ISSUE THREAD

**Issue by LaurenRWilliams** [0todd0000/spm1dmatlab#164]
I am conducting a one-way repeated measures anova for 4 conditions.  After completing the main analysis, I get the following image:
![Main_Analysis](https://user-images.githubusercontent.com/66333351/156256341-5823b908-98a6-4fc4-95f0-daabb5b7e4d4.png)

Now, I would like to perform the post-hoc analysis for this data. Here is the code I have used to do so:

Y0 = Y(A==0,:);
Y1 = Y(A==1,:);
Y2 = Y(A==2,:);
Y3 = Y(A==3,:);

t10 = spm1d.stats.ttest_paired(Y1,Y0);
t20 = spm1d.stats.ttest_paired(Y2,Y0);
t30 = spm1d.stats.ttest_paired(Y3,Y0);
t21 = spm1d.stats.ttest_paired(Y2,Y1);
t31 = spm1d.stats.ttest_paired(Y3,Y1);
t32 = spm1d.stats.ttest_paired(Y3,Y2);

%inference
alpha = 0.05;
nTests = 6;
p_critical = spm1d.util.p_critical_bonf(alpha, nTests);

t10i = t10.inference(p_critical,'two_tailed',true)
t20i = t20.inference(p_critical,'two_tailed',true)
t30i = t30.inference(p_critical,'two_tailed',true)
t21i = t21.inference(p_critical,'two_tailed',true)
t31i = t31.inference(p_critical,'two_tailed',true)
t32i = t32.inference(p_critical,'two_tailed',true)

Is this the correct way to conduct this post-hoc analysis? How can I visualize these results as I do for the main analysis? I want a figure for each comparison. 

Thank you for your help!

**Comment by 0todd0000** [comment]
Yes, this appears to be correct. Just note that the Bonferroni correction ( `p_critical_bonf` ) is usually a bit conservative, so the *post hoc* results might not exactly match the main test results. But the procedure itself is valid and the code also looks fine.

Visualizing the results can be as simple as:

```octave
t10i.plot();
```

You could alternatively create a custom multi-panel figure like this:

```octave
figure
subplot(231);  t10i.plot();
subplot(232);  t20i.plot();
subplot(233);  t30i.plot();
subplot(234);  t21i.plot();
subplot(235);  t31i.plot();
subplot(236);  t32i.plot();
```

**Comment by LaurenRWilliams** [comment]
Thank you for your reply! 

A follow-up question: do you have any options for a post-hoc analysis other than Bonferroni correction, such as a Holm correction? If we were to implement a Holm correction, how would you recommend handling a scenario where there are multiple p-values within one pair-wise comparsion such as this (see NoBrace vs Locked or Unlocked vs Locked):
![MTP_Power_Post_Hoc_6](https://user-images.githubusercontent.com/66333351/158431966-1e2c647b-cf4f-465a-9002-694266bb3dd9.jpg)

Should we treat them as separate p-values when ordering them for the Holm correction? Or should we average the two p-values that are within the same comparison, so that there is one p-value for each comparison?

**Comment by 0todd0000** [comment]
Brief reply: we recommend against a Holm correction.

As an extended reply, please consider the following:

- Bonferroni corrections, Holm corrections, and other corrections must be applied at the test level (not at the cluster level)
- The Bonferroni correction is easy to calculate because it depends only on the number of tests *m*
- The Holm correction depends on p-values, but these must be test-level p-values (not cluster-level p-values); one thus requires *m* p-values (i.e., one p-value per test)
- Test-level p-values for SPM analyses exist, but they cannot generally be applied in a straightforward Holm-type manner:
    - One cannot use cluster p-values because there can be multiple clusters for each test; there can also be no p-values if the test statistic does not cross the critical threshold
    - One cannot use the test's set-level p-value (i.e., the probably of observing *c* clusters, each with a size of at least *k*), because --- like cluster-level p-values --- set-level p-values are undefined when the test statistic fails to cross the critical threshold
    - The best candidate for a test-level p-value is the p-value associated with the maximum test statistic (e.g., maximum t-value). This can be readily calculated, and is indeed the probability that is used to calculate the critical threshold;  one sets this probability to alpha, then calculates the t-value that yields this p-value.  However, this p-value is valid only for relatively small p-values (less than about p=0.3) and is generally inaccurate for large p-values (p>0.5). It is thus valid and accurate to use this p-value for the typical case of alpha=0.05, but it is generally not valid to use this p-value for p>0.5. Therefore there is no general test-level p-value, so it is not possible to apply a simple Holm correction.

For these and other reasons, **spm1d** does not offer automated *post hoc* corrections. As a general strategy, we recommend either (a) applying a Bonferroni correction, and/or (b) regarding *post hoc* tests simply as qualifiers of the main test results. From this perspective, arbitrary *post hoc* analyses are fine, provided they do not disagree with the main test results.

**Comment by 17740150810** [comment]
Hi Todd, I am running a 4 condition ANOVA, the result  indicated there exists significance among these 4 groups, but the post hoc tests are negetive, is there anything wrong with my code or else? thank you.
![image](https://github.com/0todd0000/spm1dmatlab/assets/138347990/5ab7b428-ab53-46f7-937a-25f71da855ff)
![image](https://github.com/0todd0000/spm1dmatlab/assets/138347990/9b6bf3d2-0398-4e56-bd99-680bc4c3b1f5)
%(1) Conduct SPM analysis:
spm_bs    = spm1d.stats.anova1(Y, A);  %between-subjects model
spm       = spm1d.stats.anova1rm(Y, A, SUBJ);  %within-subjects model
spmi      = spm.inference(0.05);
disp(spmi)

%(2) Plot:
close all
spmi.plot();
spmi.plot_threshold_label();
spmi.plot_p_values();
hold on
plot(spm_bs.z, 'r')  %between-subjects model


%%% separate into groups:
Y1         = Y(A==1,:);
Y2         = Y(A==2,:);
Y3         = Y(A==3,:);
Y4         = Y(A==4,:);

%(1) Conduct SPM analysis:
t12 = spm1d.stats.ttest2(Y1,Y2);
t13 = spm1d.stats.ttest2(Y1,Y3);
t14 = spm1d.stats.ttest2(Y1,Y4);
t23 = spm1d.stats.ttest2(Y2,Y3);
t24 = spm1d.stats.ttest2(Y2,Y4);
t34 = spm1d.stats.ttest2(Y2,Y4);


% inference:
alpha      = 0.05;
nTests     = 6;
p_critical = spm1d.util.p_critical_bonf(alpha, nTests);
t12i       = t12.inference(p_critical, 'two_tailed',true);
t13i       = t13.inference(p_critical, 'two_tailed',true);
t14i       = t14.inference(p_critical, 'two_tailed',true);
t23i       = t23.inference(p_critical, 'two_tailed',true);
t24i       = t24.inference(p_critical, 'two_tailed',true);
t34i       = t34.inference(p_critical, 'two_tailed',true);

**Comment by 0todd0000** [comment]
It seems that the main results are the `anova1rm` results, and since `anova1rm` is a within-subjects (or repeated measures = RM design), it means that the post hoc analyses should also be within-subjects. Note that `ttest2` is between-subjects and that `ttest_paired` is within-subjects, so if you change `ttest2` to `ttest_paired` I'd expect closer agreement with the `anova1rm` results.

**Comment by 17740150810** [comment]
thank you! How could I forgot this, thanks again!



发自我的iPhone


------------------ Original ------------------
From: Todd Pataky ***@***.***&gt;
Date: Tue, Jul 4, 2023 7:47 PM
To: 0todd0000/spm1dmatlab ***@***.***&gt;
Cc: 17740150810 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [0todd0000/spm1dmatlab] One-way RMANOVA post-hoc analysis (Issue#164)





 
It seems that the main results are the anova1rm results, and since anova1rm is a within-subjects (or repeated measures = RM design), it means that the post hoc analyses should also be within-subjects. Note that ttest2 is between-subjects and that ttest_paired is within-subjects, so if you change ttest2 to ttest_paired I'd expect closer agreement with the anova1rm results.

**Comment by Lukasslovak** [comment]
Dear Todd, I hope you're well,

Thank you for your previous reply.

Should I please set the alpha level for the ANOVA RM post-hoc test (4 conditions) to 0.05/4=0.0125? 

Right now, the alpha level for the post-hoc is set to 0.05 - I'm just thinking that if I lower the alpha level to 0.0125, all the significant differences in the post-hoc would disappear!

**Importantly, significant differences at an alpha level of 0.05 in the RM ANOVA would then not match the post-hoc (where there will be no significant differences after adjusting for 0.0125).** That's what I'd like to understand.

![VGRF_POSTHOCS](https://github.com/0todd0000/spm1dmatlab/assets/114641062/2e2a029e-eb5e-4dc5-83a4-c37ac4654de5)
![VGRF_MAIN GRAPH](https://github.com/0todd0000/spm1dmatlab/assets/114641062/f86affd9-29f2-4397-a356-1b71fa3e4110)

Thank you very much for your time and work on the SPM approach!

**Comment by 0todd0000** [comment]
> Should I please set the alpha level for the ANOVA RM post-hoc test (4 conditions) to 0.05/4=0.0125?

Yes, this is a reasonable approximation. `spm1d.util.p_critical_bonf(0.05, 4)` is slightly more accurate but the differences will likely be negligible.

<br>
<br>

> Importantly, significant differences at an alpha level of 0.05 in the RM ANOVA would then not match the post-hoc (where there will be no significant differences after adjusting for 0.0125). That's what I'd like to understand.

As in the thread above, a simple correction like the Bonferroni correction is not expected to yield exact agreement between main and `post hoc` results, and I am unaware of any published SPM *post hoc* procedure that is expected to yield exact agreement. A good, general approach is to regard the ANOVA results as the main results and *post hoc* results as qualifying results. From this perspective you can do anything you like in *post hoc* analysis provided those results do not disagree with the main ANOVA results.

**Comment by Lukasslovak** [comment]
> > Should I please set the alpha level for the ANOVA RM post-hoc test (4 conditions) to 0.05/4=0.0125?
> 
> Yes, this is a reasonable approximation. `spm1d.util.p_critical_bonf(0.05, 4)` is slightly more accurate but the differences will likely be negligible.
> 
> 
> 
> > Importantly, significant differences at an alpha level of 0.05 in the RM ANOVA would then not match the post-hoc (where there will be no significant differences after adjusting for 0.0125). That's what I'd like to understand.
> 
> As in the thread above, a simple correction like the Bonferroni correction is not expected to yield exact agreement between main and `post hoc` results, and I am unaware of any published SPM _post hoc_ procedure that is expected to yield exact agreement. A good, general approach is to regard the ANOVA results as the main results and _post hoc_ results as qualifying results. From this perspective you can do anything you like in _post hoc_ analysis provided those results do not disagree with the main ANOVA results.

Dear Todd,

Thank you very much for your response and time. 

Have a nice day, Lukas
