### ISSUE TITLE
Unequal groups ANOVA (3 way, 2 rm) - not just warning, but no answers at all

### ISSUE THREAD

**Issue by freddybrown1984** [0todd0000/spm1dmatlab#176]
Thanks so much for all the help RE the 3waytworm ANOVA. I finally understood how to correct the matlab path, considering the “Unrecognized function or variable 'spm_uc'” error messagae

Can I confirm, though... will this three way ANOVA not work with groups of different sizes? And there’s no work-around? I can now get all of my desired outputs with the equal sized groups, but not when they differ by n = 1. 

Thanks - and again apologies if I've missed a previous instance of this question being answered 

Freddy

**Comment by freddybrown1984** [comment]
Great stuff. Thanks (again) Todd!

I think I've seen some mentions of adding a power analysis into the SPM outputs. Can "observed power" be calculated for my ANOVAs?

**Comment by 0todd0000** [comment]
Power can be calculated for arbitrary designs but for the 1D case there are several necessary considerations. Please see the [power1d site](https://spm1d.org/power1d) for a few descriptions of relevant considerations.

**Comment by freddybrown1984** [comment]
Brilliant. Thanks!
