### ISSUE TITLE
SPM1D 1-way rmANOVA with unequal variance between groups

### ISSUE THREAD

**Issue by cahelm** [0todd0000/spm1dmatlab#180]
Hello!

I am wondering how to run the SPM1D 1-way rmANOVA in MATLAB accounting for unequal variance between groups.

Thank you!

Best,
Cody

**Comment by 0todd0000** [comment]
As of the current main release (**spm1d** v0.4), corrections for non-sphericity (i.e., unequal group variances) are:
- limited to only the Python version of **spm1d**
- limited to one-way ANOVA 

So if you'd like to correct for unequal variance the easiest option may be to use the Python version with the command:

```python
spmi = spm1d.stats.anova1rm( Y, A, SUBJ, equal_var=False ).inference(alpha=0.05)
```
as demonstrated [here](https://spm1d.org/doc/Stats1D/anova.html#one-way-repeated-measures-anova).
