### ISSUE TITLE
One-way RM Anova Asymmetry Parameter

### ISSUE THREAD

**Issue by LindeRavenDepuydt** [0todd0000/spm1dmatlab#182]
Hello, 

We collected data of ACL reconstructed patients walking at 4 different speeds and want to investigate the effect of speed on the asymmetry between uninjured and injured limb. The asymmetry between limbs is calculated by subtracting the mean of 10 stance phases of the uninjured limb from the the mean of 10 stance phases of the injured limb. By calculating this parameter, we only have one observation for each subject per condition. 

I wondered if there is a way to add the separate stance phases in the ANOVA analysis (to estimate within subject variability) and only afterwards calculate the asymmetry parameter? Or are there other solutions to cope with this problem?

Kind regards,
Linde-Raven Depuydt
PhD Researcher Musculoskeletal Rehab KULeuven (BE)

**Comment by 0todd0000** [comment]
One way to focus on a specific domain portion or gait phase is to use region-of-interest (ROI) analysis. Here is an example using a two-sample test:

```octave
dataset    = spm1d.data.uv1d.t2.SimulatedTwoLocalMax();
[YA,YB]    = deal(dataset.YA, dataset.YB);
roi        = false( 1, size(YA,2) );
roi(16:35) = true;
spm        = spm1d.stats.ttest2(YA, YB, 'roi',roi);
spmi       = spm.inference(0.05, 'two_tailed',false, 'interp',true);
disp(spmi)
```

Here `roi` is a binary vector where `true` indicates the domain portions that should included in analysis.

Other examples can be found in the [ROI examples folder](https://github.com/0todd0000/spm1dmatlab/tree/master/examples/stats1d_roi)

If the whole domain is of empirical interest, then I'd recommend first conducting whole-domain analysis, and then optionally using ROI analysis as a type of *post hoc* consideration of the main whole-domain results.

**Comment by LindeRavenDepuydt** [comment]
Thank you for the quick response! However, I think my question wasn't very clear. I'm not interested in a specific domain or gait phase. I want to perform whole-domain analysis. 

I want to investigate the effect of walking speed in limb asymmetry. For this I calculated e.g. knee joint moment during stance for 10 walking trails with the injured limb and the uninjured limb at 4 different speeds. The asymmetry is calculated by substracting the mean (of 10 trials) injured knee joint moment (1d) from the mean uninjured knee joint moment (1d), resulting in a 1d parameter. However, when I use this parameter in the one way repeated measures anova, I get the warning concerning zero variance. 
My question if this workflow is wrong and if there is a way to integrate the original trial-variance in the analysis.

**Comment by 0todd0000** [comment]
> if this workflow is wrong 

I see no problem in terms of **spm1d**.

<br>
<br>

> if there is a way to integrate the original trial-variance in the analysis.

No, this is not possible. Variance is particular to a specific dependent variable (DV), so if you calculate a new DV you must use its variance. When a DV has zero variance it means that no statistical analyses can be conducted so you should try to find out what is causing the zero variance. Try plotting the standard deviation (SD) for your dependent variable. From the SD plot you should be able to identify what region(s) of the domain have zero variance.
