### ISSUE TITLE
RM MANOVA, Vectoranalysis

### ISSUE THREAD

**Issue by Athletikum** [0todd0000/spm1dmatlab#183]
Dear Todd, i just attended the Workshop in Antwerp and would love to go into "medias res".
We followed 87 ACL Patients and collected 3-D kinematics data 6 and 12 month after ACL-R.
Now i would like to compare kinematics of injured and non-injured limb 6 and 12 month post surgery.
MANOVA1 lets me do this for one timepoint by constructing a 174*100*3 double containing vectorflieddata from 87 injured and uninjured limbs. Is there already a solution within SPM1d for RM to also respect time?
Could GLM give me an solution as there is no RM MANOVA yet?
Thank you for your ideas on  this problem!

Regards

arthur

**Comment by 0todd0000** [comment]
Hi Arthur,

You can use **spm1d.stats.manova1** with 1D (time-series) data. The input data arrays must be 3D arrays with size `(J, Q, I)`, where:

- `J` = number of observations
- `Q` = number of time nodes
- `I` = number of vector components

The [ex1d_manova1.m](https://github.com/0todd0000/spm1dmatlab/blob/master/examples/stats1d/ex1d_manova1.m) script demonstrates use of one-way MANOVA using the Dorn et al. (2012) running/sprinting dataset.
