### ISSUE TITLE
Issue with test.inference at α=0.05

### ISSUE THREAD

**Issue by MenychtasDim** [0todd0000/spm1dmatlab#186]
_EDIT: Make sure your data type is double-precision. If for some reason you enter single-precision data, the function is more likely to reach infinity and the first part can't deal with it._ 

This is more like a PSA. 

In certain scenarios when using the test.inference with the level of significance at 0.05, the code enters an infinite loop. 
I tracked the issue in the spm_uc_RF.m file. Lines 33 to 52 read:

% approximate estimate using E{m}

%--------------------------------------------------------------------------
d     = 1;
while abs(d) > 1e-6
    [P P p] = spm_P_RF(1,0,u,df,STAT,R,n);
    [P P q] = spm_P_RF(1,0,u + du,df,STAT,R,n);
    d       = (a - p)/((q - p)/du);
    u       = u + d;
end

% refined estimate using 1 - exp(-E{m})
%--------------------------------------------------------------------------
d     = 1;
while abs(d) > 1e-6
    p       = spm_P_RF(1,0,u,df,STAT,R,n);
    q       = spm_P_RF(1,0,u + du,df,STAT,R,n);
    d       = (a - p)/((q - p)/du);
    u       = u + d;
    if isinf(u), u=+Inf; return; end
end

In the first part (% approximate estimate using E{m})  variable d can become inf and the loop never stops. The second part (% refined estimate using 1 - exp(-E{m})) is exactly the same but the last line will break the loop if d becomes infinite. 
Just make sure you comment/delete the part that can't handle infinity.

Cheers!

PS. I genuinely hope I am the last guy to learn it and everyone else has figured it out ages ago.

**Comment by 0todd0000** [comment]
Hello, thank you for posting this issue. I've not seen this issue before!  I have two questions:

1. Are you calling `spm_P_RF` directly, or are you calling it indirectly, through the `inference` method?
2. Can you please paste a full script that demonstrates the problem?  This will make it easier to find and solve the problem.

**Comment by MenychtasDim** [comment]
Hello Dr. Pataky,

1. I am calling it indirectly. My code is:

test=spm1d.stats.ttest2(T1,T2);
testi= test.inference(0.05, 'two_tailed',true, 'interp',true);

2. I found the problem, somewhere in my code the data type was changing from double-precision to single-precision, this caused the value to reach infinity before it became small enough to break the 'while' loop quite fast due to the very rough rounding. I have no idea why Matlab decided to change the precision, I was loading double-precision data and simply called .inference, didn't do anything in-between. I will edit my first post to avoid confusion since it's not an issue with the spm functions themselves. 

Sorry for the false alarm.

Cheers

**Comment by 0todd0000** [comment]
No problem! I'm glad that the issue is solved. It would be concerning if spm1d changed the data type, so if the single-double problem appears to be arising from spm1d then please re-post.
