### ISSUE TITLE
Error: Non-numeric data is not supported in 'Text'

### ISSUE THREAD

**Issue by vigneshrk29** [0todd0000/spm1dmatlab#188]
Hi,

1) I get the following error when I try to plot_p_values() during nonparameteric ttest_paired. It happened when I increased the number of iterations (though now it is happening even for lower number of iteration). 

I get the following graph. Since the shaded area is for the entire time duration, I assumed that was the entire cluster?

![iterations1000](https://github.com/0todd0000/spm1dmatlab/assets/84029062/e95775dd-ffe7-4bd4-84aa-34ae2cadee04)

2) I have compared parameteric and nonparameteric results and they are qualitatively similar. Normality tests are false. Do I report both the results or just the nonparameteric ones?

3) For number of iterations, if I use -1, I get the error : 

The total number of iterations (Inf) is very large and may cause computational problems. In the call
to "inference"...
(1) Set "iterations" to a number between 10 and 10,000, or
(2) set "force_iterations" to "true" to enable calculations for iterations > 10,000.

What is the minimum number of iterations necessary and how does it alter the result?

Thanks,
Vignesh

**Comment by 0todd0000** [comment]
For the first point, please attach code that produces the error.

For the second point, please refer to other issues in this forum by searching for "nonparametric". If you cannot find an answer then please post a new issue, as this issue is separate from the error.

Point 3 is also separate from the first error so has been routed to a new issue: #189

**Comment by vigneshrk29** [comment]
Please find attached data and code. I have commented out unecessary lines. The error is formed on lines 936, 945. 

Thanks


 
[Lamberto Analysis.zip](https://github.com/0todd0000/spm1dmatlab/files/13171083/Lamberto.Analysis.zip)

**Comment by 0todd0000** [comment]
Several issues: 
- `Line 32`  is `two_tailed = true;that`  '  ;  `that` should be removed from this statement
- I am unable to reproduce the error. After correcting Line 32 (see immediately above) the script runs without errors on my PC.
- There are only 61 lines in the script so I'm not sure "lines 936, 945" refers to
- Please simplify the script as much as possible to focus in on just the error:
    - If the error occurs at the post hoc stage then please only include post hoc analysis and only the post hoc analysis that produces an error.
    - Please remove `boxchart` as this is not an **spm1d** function.
    - Please remove Parallel Computing Toolbox (PCT) dependencies including `gpuArray`. **spm1d** is not designed to work with the PCT so PCT issues cannot be supported here.

**Comment by vigneshrk29** [comment]
Hi, sorry. The code works. I did not notice the "that".

Thanks a lot
