### ISSUE TITLE
GLM with 1D covariate?

### ISSUE THREAD

**Issue by danitrowell** [0todd0000/spm1dmatlab#193]
Hi Todd, 

I hope you are well!

We are investigating the effects of an intervention (pre v post) on 1D overground running biomechanics between two groups (intervention v control). We would like to control for differences in overground running speed between baseline and follow up testing.

Are any of the SPM1D packages suitable for this design? I trialled using a GLM but I don't believe it's possible to use a 1D variable as a covariate. Is my understanding correct? I.e., determine intervention-control difference on 1D biomechanics (e.g., ankle angle at follow-up) while accounting for two covariates: 1D biomechanics at baseline and the difference in running speed (post-pre speed). 

Kind regards,
Dani

**Comment by 0todd0000** [comment]
Correct. A 1D covariate would require a type of cross-correlation analysis that is called "connectivity analysis" in the SPM literature. This may be supported in a future version of **spm1d** but it is currently not a development priority. At the moment it is only possible to use 0D scalars as covariates via GLM.
