### ISSUE TITLE
Error in 'inference' Method: "The value of 'two_tailed' is invalid. It must satisfy the function: islogical. "

### ISSUE THREAD

**Issue by LCNbalgrist** [0todd0000/spm1dmatlab#195]
I tried to make a preliminary analysis of my preprocessed EEG data and have the same format and code as is shown in this tutorial video: https://youtu.be/nKyNpoU6-_I?feature=shared

However, Matlab returns an error after line 2, because it thinks that the argument for '_two_tailed_' is not logical, even though I just used the normal _true_ function. Alternatives like _1_ or _logical(1)_ return the same result. 

These are my commands:
```
spm              = spm1d.stats.ttest_paired(df_cond_sMAS, df_cond_mMAS);    % works fine
spmi             = spm.inference('alpha', 0.05, 'two_tailed', true);     % returns error
spm_plot      = spmi.plot();    % not executed
```

I appreciate any ideas as I find this is a rather strange error. 
Thanks and all the best,
  Leonard

**Comment by m-a-robinson** [comment]
Hello Leonard,

Perhaps try without the 'alpha' keyword.

spmi = spm.inference(0.05, 'two_tailed', true);

Regards
Mark

**Comment by LCNbalgrist** [comment]
Hello Mark,

thank you so much, for whatever reason it worked! So this was solved much faster and easier than feared.

> Hello Leonard,
> 
> Perhaps try without the 'alpha' keyword.
> 
> spmi = spm.inference(0.05, 'two_tailed', true);
> 
> Regards Mark
