### ISSUE TITLE
missing spm_uc function

### ISSUE THREAD

**Issue by petelamb** [0todd0000/spm1dmatlab#200]
I'm getting an error that `spm_uc` is missing in the last line of the following example.
```
clear;  clc
dataset    = spm1d.data.uv1d.anova2onerm.SPM1D_ANOVA2ONERM_2x2();
[Y,A,B,SUBJ] = deal(dataset.Y, dataset.A, dataset.B, dataset.SUBJ);
spmlist   = spm1d.stats.anova2onerm(Y, A, B, SUBJ);
spmilist  = spmlist.inference(0.05);
```
Unrecognized function or variable 'spm_uc'.

Error in spm1d.rft1d/RFTCalculatorResels/isf (line 52)
            [u] = spm_uc(alpha, self.df, self.STAT, self.resels, self.n, self.Q);

Error in spm1d.rft1d.f.isf_resels (line 46)
            u = calc.isf(alpha);

Error in spm1d.stats.spm.SPM/get_critical_threshold (line 159)
                    zstar = spm1d.rft1d.f.isf_resels(a, v, res, 'withBonf',withBonf, 'nNodes',n);

Error in spm1d.stats.spm.SPM/inference (line 90)
            zstar        = self.get_critical_threshold(pstar, withBonf);

Error in spm1d.stats.spm.SPMFList/inference (line 21)
               spmi = spm.inference(alpha);

Error in indexing (line 40)
                    spm = builtin('subsref', self, s);

Using spm1d version M.0.4.11 (2023.10.24), MATLAB R2022a on macOS 14.1.2 Apple M1

**Comment by 0todd0000** [comment]
Please confirm that the `spm_uc.m` file exists inside the [spm8 folder](https://github.com/0todd0000/spm1dmatlab/tree/master/spm8).

If it does exist, then the error means that the **spm8** folder is not on the MATLAB path.  In that case please ensure that you add all **spm1d** folders to the MATLAB path as described [here](https://spm1d.org/install/InstallationMatlab.html#label-installationmatlab)

**Comment by petelamb** [comment]
Thanks. Yes, problem was I didn't have the spm8 folder on my path (silly mistake!).
