### ISSUE TITLE
The interpretation of the paired t test results 

### ISSUE THREAD

**Issue by PJamali97** [0todd0000/spm1dmatlab#201]
Hi Todd,
I used the code below to investigate the difference between the two variables. I conducted this analysis two times for two different conditions. 
%(1) Conduct SPM analysis:
spm       = spm1d.stats.ttest_paired(ya, yb);
spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
disp(spmi)

The graphs below show the analysis for two conditions. 
1. Looking at the mean-SD graph in condition 1, it seems like ya and by data points are very similar. I want to know why SPM identifies significant differences for the entire trial while the values of ya and yb seem to match very well. 
2. The mean-SD graph in condition 2 is similar to the mean-SD graph in condition 1. I want to know why SPM identifies differences in condition 1 but it does not identify differences in condition 2 while the mean-SD curves between the two conditions are very similar. 

![walking](https://github.com/0todd0000/spm1dmatlab/assets/123198370/c88df7e2-9bf0-4842-b7be-baf24ec8eb24)
![OC cross](https://github.com/0todd0000/spm1dmatlab/assets/123198370/ea98118e-e603-440e-8cee-087c43227d3a)

Thank you in advance for your response!

**Comment by 0todd0000** [comment]
Instead of plotting mean curves try (1) calculating paired difference curves --- one difference curve per subject, then (2) plotting the difference curves and/or their mean + standard deviation. Paired t tests consider only paired differences, so the original unpaired mean curves can be misleading.

**Comment by 0todd0000** [comment]
Great, thank you for confirming!
