### ISSUE TITLE
SPM rm 1way ANOVA

### ISSUE THREAD

**Issue by gingerkongen** [0todd0000/spm1dmatlab#204]
**Hi,**

**I wish to conduct a SPM rm 1way ANOVA**

**However, when using the downloaded dataset:**
    

clear;  clc

%(0) Load data:
dataset    = spm1d.data.uv1d.anova1rm.SpeedGRFcategoricalRM();
[Y,A,SUBJ] = deal(dataset.Y, dataset.A, dataset.SUBJ);

%(1) Conduct SPM analysis:
spm_bs    = spm1d.stats.anova1(Y, A);  %between-subjects model
spm       = spm1d.stats.anova1rm(Y, A, SUBJ);  %within-subjects model
spmi      = spm.inference(0.05);
disp(spmi)

%(2) Plot:
close all
spmi.plot();
spmi.plot_threshold_label();
spmi.plot_p_values();
hold on
plot(spm_bs.z, 'r')  %between-subjects model

 **I get this warning message:**
Warning: Only one observation per subject found.  Residuals and
inference will be approximate. To avoid approximate residuals: (a)
Add multiple observations per subject and per condition, and (b)
ensure that all subjects and conditions have the same number of
observations. 

**Does anyone know if this is fixable, or if it even matters?**

**Comment by 0todd0000** [comment]
Please refer to [this post](https://github.com/0todd0000/spm1d/issues/43) for a description of this warning.

There are several other relevant discussions [here](https://github.com/0todd0000/spm1dmatlab/issues?q=%22Only+one+observation+per+subject%22+) and [here](https://github.com/0todd0000/spm1d/issues?q=%22Only+one+observation+per+subject%22+). If these do not explain things please follow-up in the most relevant Issue and/or please feel free to continue the conversation here in this Issue.

The warning will be fixed / made more understandable in the next major version of **spm1d** (version 0.5).
