### ISSUE TITLE
unexpected high values for z (one way anova)

### ISSUE THREAD

**Issue by Woollie98** [0todd0000/spm1dmatlab#205]
Hi, 
by rewriting the example file (ex1d_anova1.m) for trying to operate a one way anova spm analysis on time-normalized joint angle data, i stumbled across immensly high values for z (between +3x10^16 and -0.8x10^16) that i cant explain. I just changed A into a vector 3x1 A=[0;1;2] and put Y into a 3x100 double containing the normalized joint angle data, where the three different rows (y1, y2, y3) show 3 different measurement procedures. Nothing else was changed and the normalized joint angle data contains 'normal' values between roughly -40° and +50°.
I will pin the resulting plot and my code, if there is anyone that might know why this happens, I'd appreciate the help!
Kind regards

![Screenshot 2024-05-22 153723](https://github.com/0todd0000/spm1dmatlab/assets/170532953/241c7621-06d5-4c6e-9f8f-f43c82517d4b)
![Screenshot 2024-05-22 153900](https://github.com/0todd0000/spm1dmatlab/assets/170532953/cf8df583-1462-4498-b063-4cdb52331ccc)

**Comment by 0todd0000** [comment]
These high values occur because the sample size is too small, and because variance is zero or numerically very close to zero. With just three observations (one for each of three A conditions) there is no within-condition variance. Please use a bigger sample size, with preferably five or more observations for each condition.

**Comment by Woollie98** [comment]
Okay thanks for the answer now it makes totally sense. So i guess i've used the wrong example for my problem. Is there an alternate example script to analyze the given data? The aim of the spm analysis should be to compare 3 different measurement techniques for joint angle data (which represent the variables y1,y2 & y3).

**Comment by 0todd0000** [comment]
No there is unfortunately no other script. If you would like to conduct statistical testing of any kind you need more than one observation per group.
