### ISSUE TITLE
1D paired t-test

### ISSUE THREAD

**Issue by robertodimarco** [0todd0000/spm1dmatlab#21]
Hi everyone!

I'm having some problems using the 1D paired t-test with SPM1D.
In particular, I am applying a paired t-test to a set of curves of  human joint kinematics recorded in two different walking conditions. I have used this method before, and with the same data, but now MATLAB is returning an error and I wondered whether some of you could help me understanding it.

Briefly, my two inputs for the t-test are the matrices Y0 and Y1. Then:
t=spm1d.stats.ttest_paired(Y0,Y1);

Afterwards, I save the inference results for each joint (the hip for the following):
HIPti(1)=t.inference(0.05, 'two_tailed', true);

For some joints, I obtain the error in the attached picture. I understand the problem are the NaN obtained from the t=spm1d.stats.ttest_paired(Y0,Y1) line of code, but I really do not understand why I have those NaN and how I can solve this issue.

Does anyone know how to solve this?

Thank you very much!

Roberto
![problem](https://cloud.githubusercontent.com/assets/19834152/15923031/2eee6d34-2e2b-11e6-8fc1-865c4c881f82.PNG)

**Comment by 0todd0000** [comment]
Hi Roberto,

I'm not sure exactly what is causing the problem, but from the left hand side it would appear that there is something wrong with the data itself (because *fwhm* = NaN).  I've seen this type of problem for coding errors like attempting to use the same variable:

```matlab
>>  t = spm1d.stats.ttest_paired(Y0, Y0);  %instead of Y0, Y1
```

If that doesn't solve the problem, please send some more information, including preferably a figure which depicts the *Y0* and *Y1* variables.

Cheers,

Todd

**Comment by robertodimarco** [comment]
Hi Professor,

Unfortunately, I tried but without success. I am sorry but I still need to bother you.

The Y0 and Y1 are actually different and I attached a picture of both of them.
Do you need the two variables saved in a .mat file?

Cheers,
Roberto

![y0-y1](https://cloud.githubusercontent.com/assets/19834152/16005220/66b576a2-3166-11e6-92c8-fa315e5b8538.png)

**Comment by robertodimarco** [comment]
For some variables I solved the problem. Indeed I found some NaN in Y1, and I deleted the lines containing NaN both in Y0 and Y1.
But still, I obtain weird results. I attached the picture.
Could you help also with this?

Cheers
Roberto

![issue](https://cloud.githubusercontent.com/assets/19834152/16009896/efff57a8-317e-11e6-9ad1-488f54cce329.PNG)

**Comment by 0todd0000** [comment]
Hi Roberto,

There do not appear to be any obvious problems in *Y0* and *Y1*, but the SPM results suggest that something remains odd in these data.  If possible, please attach the *Y0* and *Y1* data in MAT format.

Regards,

Todd

**Comment by 0todd0000** [comment]
Hi Roberto,
Since there hasn't been any activity on this issue for a while I'm closing it, but please feel free to send the data and/or reply to this post if you're still having problems.
Todd
