### ISSUE TITLE
spm one-way ANOVA: invalid data type error

### ISSUE THREAD

**Issue by EugLam** [0todd0000/spm1dmatlab#212]
Dear,

I am performing the following spm one-way ANOVA in MATLAB: 

clear;  clc
load('HeadRotation_SPM_kopie.mat');
dataset1 = HeadRotationSPMkopie;
A = HeadRotationSPMkopie.Condition(2:end,1); %independent variable condition
Y = HeadRotationSPMkopie(2:end,4:end); %dependent variables head rotation angle
spm       = spm1d.stats.anova1(Y, A);
spmi      = spm.inference(0.05);
disp(spmi)
spmi.plot('plot_threshold_label',false, 'plot_p_values',true, 'autoset_ylim',true)

However, I keep getting the following error:
![MATLABerror](https://github.com/user-attachments/assets/53118924-19a4-4a65-b8d5-a1719e0c70a4)

Would anyone have an idea why this error occurs?
Thanks for helping me out!

**Comment by 0todd0000** [comment]
It looks like `HeadRotationSPMkopie` is a structure.  The inputs `Y` and `A` must both be numeric arrays.

**Comment by EugLam** [comment]
That solves the issue indeed. Thank you!
