### ISSUE TITLE
Inference:   "Improper assignment with rectangular empty matrix."

### ISSUE THREAD

**Issue by 0todd0000** [0todd0000/spm1dmatlab#3]
This follows from the end of Issue https://github.com/0todd0000/spm1dmatlab/issues/1

Ellen wrote:

```
I still get an error on some of my variables, but not all of them (although they are organized in exactly the same way):

Improper assignment with rectangular empty matrix.

Error in spm1d.geom.cluster_geom (line 9)
heights(i) = min( z(L==i) );

Error in spm1d.stats.spm.SPM/inference (line 64)
[extents,heights] = spm1d.geom.cluster_geom(self.z, zstar);

Error in spm1d.stats.spm.SPMList/inference (line 21)
spmi = spm.inference(alpha, varargin{:});

Error in ex_anova2onerm (line 22)
spmi = spm.inference(0.05);
```

**Comment by 0todd0000** [comment]
Hi Ellen,

I can't reproduce the error including the following cases:
* the whole F curve is above the threshold
* the whole F curve is below the threshold

Additionally, since the problem occurs for some dependent variables but not others I suspect that there is a problem in the actual data.  Possible problems include:  zero-variance, NaN values, inf values, etc.

To narrow-down the potential cause of the problem please try the following:

(1) Check for zero-variance nodes by calculating the standard deviation:
```
sd = std(Y, [], 1);
plot(sd)
```
Are any of the SD values zero?  If so statistical analysis is not possible.

(2) Plot the raw SPM (i.e. before inference):
```
spm.plot()
```
Does anything look strange (e.g. infinite values)?
Please attach the result.


(3) Check the raw SPM information:
```
disp(spm)
```
Please copy and paste the result into your reply.


(4) Check the original data:
```
plot(Y', 'k')
```
Does anything look strange?
Please attach the result.

Todd

**Comment by ellenmaas** [comment]
Hi Todd,

Everything looks pretty normal to me. 

(1) SD values are all above zero:
![sd](https://cloud.githubusercontent.com/assets/13256591/8637929/25652d7a-28aa-11e5-82ef-e22496c85ff1.png)

(2) the spm.plot() function does not work, I guess you mean to plot the z variable?
![z](https://cloud.githubusercontent.com/assets/13256591/8637951/df4a52ba-28aa-11e5-8a58-da40c14461c2.png)


(3)
  SPMList with properties:

    SPMs: {[1x1 spm1d.stats.spm.SPM]  [1x1 spm1d.stats.spm.SPM]  [1x1 spm1d.stats.spm.SPM]}
       n: 3
(4)
![y](https://cloud.githubusercontent.com/assets/13256591/8638044/3f694d16-28ad-11e5-9a98-050276086929.png)

Ellen

**Comment by 0todd0000** [comment]
Hi Ellen,
It looks like the first value might have a problem.
If the first node's SD value is OK then the figure will look like this:

![ex1](https://cloud.githubusercontent.com/assets/4276626/8639677/7c30e4d0-28d9-11e5-9770-6edb1f615ed7.png)

Note the left side:  the first value (at zero) is filled, so the curve touches the left vertical axis.

Now look what happens if the first value is NaN:

![ex2](https://cloud.githubusercontent.com/assets/4276626/8639681/a5424b8e-28d9-11e5-9934-616e4696c65e.png)

Note that the first value (at zero) no longer appears. This looks like the plots you sent, which leads me to believe that all values at time=zero are all zero.

So just as a sanity check, please try re-running these variables by ignoring the first time point:

```
Y = Y[:, 1:]
```

or an arbitrary sub-range of the data:

```
Y = Y[:, 5:60]
```

Todd

**Comment by 0todd0000** [comment]
Hi again Ellen,

I found the problem.  There was indeed a problem with the code. I’ve uploaded the changes to github, please download and use the most recent version.

Note:
The ANOVA design you're using is unbalanced (there are more subjects for A=1 than for A=2).  This is not a problem for ANOVA, in general, but I’ve not yet had a change to verify results for unbalanced designs, so please interpret the results with caution.

Todd

**Comment by 0todd0000** [comment]
Hi Ellen,  this is a brief follow-up:
The new version of the code (version 0.3.1, released today) now supports repeated-measures ANOVA with different numbers of subjects. This is applicable to the following designs:
* anova2onerm
* anova3onerm
* anova3tworm

For anova2rm and anova3rm the same number of subjects is still needed for all conditions.

Two new datasets can be used to test this out:

```
dataset = spm1d.data.uv0d.anova2onerm.Santa23UnequalSampleSizes();
dataset = spm1d.data.uv0d.anova2onerm.Southampton2onermUnequalSampleSizes();

[y,A,B,SUBJ] = deal(dataset.Y, dataset.A, dataset.B, dataset.SUBJ);
disp(dataset)

spm  = spm1d.stats.anova2onerm(y, A, B, SUBJ);
spmi = spm.inference(0.05);
disp_summ(spmi)
```

Cheers,
Todd
