### ISSUE TITLE
Error for normality in matlab

### ISSUE THREAD

**Issue by 0todd0000** [0todd0000/spm1dmatlab#30]
From Sina:

> Hey Todd,
> I just tried the new normality method and get the following error code (:
> 
> No appropriate method, property, or field residuals for class spm1d.stats.spm.SPM.
> Error in spm1d.stats.spm.SPMi (line 42)
> self.residuals = spm.residuals;
> 
> Error in spm1d.stats.spm.SPM/inference (line 88)
> spmi = spm1d.stats.spm.SPMi(self, alpha, zstar, p_set, p, two_tailed, clusters);
> 
> Error in ex1d_ttest2 (line 15)
> spmi = spm.inference(0.05);
> 
> Do you have any idea whats the problem?
> 
> Best regards,
> Sina

**Comment by 0todd0000** [comment]
Hi Sina,

Thank you for reporting this error. I can't seem to reproduce it, so please send some more details...

Are you running the example script: **./spm1d/examples/normality/1d/ex_ttest2.m** or are you using your own script?

If you're using your own script please copy it into your reply here.

Todd

**Comment by SinaDavid** [comment]
Hey Todd,
sorry for posting my request in the wrong forum. 
I run ./spm1d/examples/normality/1d/ex_ttest2.m with the included example data. I asked a colleague to do the same on his pc, and the same error occured. We are using Matlab 2014a, so probably its a problem due to versions...
Update: I also checked the script on Matlab 2014b and the same error occurs...

**Comment by 0todd0000** [comment]
Hi Sina,

It sounds like there's a path problem that is mixing versions 0.3.7 and 0.4.1.

Note this part of the error (from above):

> Error in spm1d.stats.spm.SPM/inference (line 88)
> spmi = spm1d.stats.spm.SPMi(self, alpha, zstar, p_set, p, two_tailed, clusters);

In version 0.3.7, Line 88 of **./+spm1d/+stats/+spm/SPM.m** is the same as cited in the error above:

```
spmi         = spm1d.stats.spm.SPMi(self, alpha, zstar, p_set, p, two_tailed, clusters);
```

but in version 0.4.1, Line 88 of the same file is:

```
pstar = alpha;
```

So it sounds like both versions 0.3.7 and 0.4.1 may be on the MATLAB path.

To solve the problem try one or both of the following:

* Delete all **spm1d** versions prior to 0.4.1 from your computer.

* Remove all **spm1d** references from the MATLAB path, then set the path for only 0.4.1.

Todd

**Comment by SinaDavid** [comment]
Hey Todd,
it works, I tried that already but must have missed something. 
Thanks for your help!!!
Sina

**Comment by 0todd0000** [comment]
Great, thanks for confirming.  I'll close this issue, but please feel free to write with a follow-up comment in this issue or create a new issue if anything else comes up.
Todd
