### ISSUE TITLE
p-Values

### ISSUE THREAD

**Issue by 0todd0000** [0todd0000/spm1dmatlab#31]
From Sina:

> Hey Todd,
> I just recognized something I can't explain:
> If I compare datasets via ttest2 in a two-tailed approach, I get an p_value of 0.021
> If I change die orientation of my datasets by simply multiplying them by -1 (need to do this for some figures), and than recalculate the p-value, it changes to 0.047. 
> In my opinion there shouldn't be a difference, but probably I'm wrong.
> Thanks in advance!
> Sina

**Comment by 0todd0000** [comment]
Hi Sina,

I agree with you, the results should be the same.  I can indeed replicate the error using the example two-sample t test script --- thank you so much for finding this bug!!

The bug applied only to version M.0.4 and should not affect versions M.0.3.X or previous versions.

Please find that I've fixed the bug and have updated the software at github.com as version M.0.4.1.   Please download the new version, and please let me know if that doesn't fix the problem.

Note:  only two files have been updated:

* ./spm1d/VERSION.txt
* ./spm1d/+spm1d/+geom/Cluster.m

The VERSION.txt file just indicates that the current version is now M.0.4.1.

In case you're interested the Cluster.m file (Line 110) contains the edits below:

Old version  (M.0.4):

```
self.h      = min(z);
```

New version (M.0.4.1):

```
if self.csign == -1
    self.h      = max(z);
elseif self.csign == 1
    self.h      = min(z);
end
```


Thanks again so much for spotting this bug, I'll be sure to implement automated checks for this in future releases.

Todd

**Comment by SinaDavid** [comment]
Hey!
Thanks a lot, it works. Btw, I was using Version M.0.3.7 when the p-value problem occurred, but I changed the cluster.m file there as well and now I got the same p-values for both analysis. 
Have a nice weekend!

**Comment by 0todd0000** [comment]
Good to know that it affected 0.3.7 as well.
Thanks again very much for reporting this bug!
Todd

**Comment by SinaDavid** [comment]
HI Todd, 

I think i found the same bug for the nonparametic testing. I tried to repair it on my own, but the ClusterNP.m looks too different. Maybe you can have a look at this problem.
Best regards,
Sina

**Comment by 0todd0000** [comment]
Hi Sina,
The non-parametric cluster class inherits from the parametric cluster class, so if the bug doesn't exist in the parametric version then the non-parametric version should be OK.
What version of spm1d are you using?
If possible, please send a script that replicates the problem.
Todd

**Comment by SinaDavid** [comment]
Hi,
I'm using Version M.0.4 (2016.10.01).

I used the ttest for nonparametric data:
If I'm using the 'variable' as input, I get 3 suprathreshold cluster, If I'm multiplying 'variable' with (-1), I only get one cluster.
Here are the results:
SnPM{t} inference (1D)
              z: [1x101 double]
    nPermUnique: 6.8490e+15
    nPermActual: 1000
          alpha: 0.0500
          zstar: 2.6908
       h0reject: 1
              p: [0.0020 0.0120 0.0070]
----------------------------------------------------------------
SnPM{t} inference (1D)
              z: [1x101 double]
    nPermUnique: 6.8490e+15
    nPermActual: 1000
          alpha: 0.0500
          zstar: 3.2956
       h0reject: 1
              p: 0.0070
----------------------------------------------------------
I used the following script and also attached the original data:

[hidx3.xlsx](https://github.com/0todd0000/spm1dmatlab/files/1218194/hidx3.xlsx)
[variable.xlsx](https://github.com/0todd0000/spm1dmatlab/files/1218191/variable.xlsx)

please let me know if you need anything else,
Thanks in advance,
Sina
-------------------------------------------------------------------------------
code:
Y=variable;
%Y=variable*(-1);

G1=Y(hidx3==1,:); 
G2=Y(hidx3==3,:);
%(1) Conduct non-parametric test:
rng(0)
alpha      = 0.05;
two_tailed = true;
iterations = 1000;
snpm       = spm1d.stats.nonparam.ttest2(G1, G2);
snpmi      = snpm.inference(alpha, 'two_tailed', true, 'iterations', iterations);
disp('Non-Parametric results')
disp( snpmi )

**Comment by 0todd0000** [comment]
Hi Sina,

Thank you very much for sending your data and code.  I see the problem now.  It is actually not a bug.  It is instead a consequence of asymmetry in the probability density function that naturally emerges from permutation-based non-parametric inference.

In general, two-tailed results for Y and -Y are equivalent only when all possible permutations are conducted. This is because the maximum of t(q) (i.e. the 1D t continuum) is generally not the same as the maximum of -t(q), so unless you perform all permutations the resulting distributions of t(q)_max will almost always be different for Y and -Y.

To see what I mean try reducing the number of observations to five for each group like in the code below, in which case there is small total number of permutations (here: 252).  You should see that the results for Y and -Y are the same.  To see a similar result for larger sample sizes you would have to conduct a very large number of permutations (e.g. 1 x 10^9). You should see that the critical thresholds for Y and -Y converge as the number of permutations increases.

```matlab
Y0 = variable;
for c = [1 -1]
    Y  = c * Y0;    %multiply by 1 then -1
    
    G1 = Y(hidx3==1,:);
    G2 = Y(hidx3==3,:);
    
    %use a small sample size to test
    G1 = G1(1:5,:);   
    G2 = G2(1:5,:);
    
    % Conduct non-parametric test:
    rng(0)
    alpha = 0.05;
    two_tailed = true;
    iterations = -1;   %use all permutations
    snpm = spm1d.stats.nonparam.ttest2(G1, G2);
    snpmi = snpm.inference(alpha, 'two_tailed', true, 'iterations', iterations);
    
    %the critical threshold is constant when iterations = -1
    disp( snpmi.zstar )
end
```

Todd

**Comment by SinaDavid** [comment]
Ok, so I only need to increase the number of permutations. Thanks again for helping!
Sina
