### ISSUE TITLE
"Warning: returning NaN for out of range arguments"

### ISSUE THREAD

**Issue by romainmartinez** [0todd0000/spm1dmatlab#38]
Hello Todd,
I’m doing a kinematic analysis between two groups (men and women), during a handling task.
After having formated the data in the SPM way, i.e:

```
Y = 1296 x 200 frames
A = 1 x 1296 trials (factor sex)
B = 1 x 1296 trials (factor weight)
C = 1 x 1296 trials (height of factors)
```
Then I run an ANOVA 3 factors with:

```
Spmlist = spm1d.stats.anova3 (Y, A, B, C);
Spmilist = spmlist.inference (0,05);
Disp_summ (spmilist)

```
But I get the following error:

`“Warning: returning NaN for out of range arguments”`

Any idea about where it came from?

thank you in advance,

—Romain

**Comment by 0todd0000** [comment]
Hi Romain,

From your description everything looks fine, and I can't see any obvious reason for the problem.  Please provide some more details:

- After which of those three commands does the error occur?
- Are you able to run the example anova3 script without errors?

To check whether there might be a problem in the variables, the following debugging might be useful:

- Confirm that there are no NaN values in Y, A, B and C.
- Confirm that A, B and C contain only integers (e.g. using "unique(A)")
- Compute group means for each level of A, B and C separately and check that there are no obvious problems. 

If that doesn't solve the problem please paste the full error message, which will indicate which part of the **spm1d** code is causing the problem.

Todd

**Comment by romainmartinez** [comment]
Hi Todd and thank you for your answer,

I found where the error came from: among the 1512 trials, one trial had one frame with NaN.

Thank you for your availability

**Comment by 0todd0000** [comment]
No problem, I'm glad the error is solved.  We're working on a data checking scheme which will return more meaningful error messages (e.g. "The data array contains NaN values".).  It should be available in the next release.
Thank you for reporting the problem.
Todd
