### ISSUE TITLE
ANOVA type (I, II, III)

### ISSUE THREAD

**Issue by NicolasFlores14** [0todd0000/spm1dmatlab#46]
Dear Todd,

I would like to know if you have programmed a certain type of ANOVA in the toolbox.

Indeed, I performed an ANOVA2rm with the factors A and B, and then I changed the order in the function as B and A. The SPM{F} curve is different in some locations resulting in a different number of clusters for a given factor.

If I am correct, the type I ANOVA is sensitive to the order of factors in the model,  and it is not the case for types II and III ANOVA.

Is it a possible explanation of my different results? Do you think to another reason?

Thanks a lot for your answers,
Best regards.

Nicolas Flores

**Comment by 0todd0000** [comment]
Hi Nicolas,

**spm1d** implements Type I sums-of-squares but also forces balanced designs (i.e. if the design is unbalanced an error will be produced).  For balanced designs the results should be identical irrespective of the order AB vs. BA.

I'm unable to reproduce this error using **spm1d**'s built-in datasets...
Could you attach figures showing the AB and BA results?

Todd

**Comment by NicolasFlores14** [comment]
Hello Todd,

Unfortunately, I can not reproduce my error in ordering AB or BA... I think you were correct in your previous answer.
 I had maybe changed another parameter in the script, or I had not cleared my workspace, but finally, I can not reproduce it. If I success to reproduce the error, I will open again this issue.

Sorry for the issue opened, and thanks therefore for your response about the ANOVA type used in the package.

Best regards.

Nicolas

**Comment by 0todd0000** [comment]
Hi Nicolas, no problem at all.  If you discover what caused the problem please do open a new issue, or re-open this one.  Even if it's not exactly a software bug, it would be good to add some documentation or warning messages to explain the issue.
Thank you!
Todd
