### ISSUE TITLE
Nonparam paired ttests: output Inf/NaN

### ISSUE THREAD

**Issue by antoinefalisse** [0todd0000/spm1dmatlab#48]
Hi,

I am trying to use non-parametric paired t-tests to compare the output of two models. However, in some cases, I obtain +/- Inf or NaN in the spm.z vector. I had a quick look in the code and it seems to occur when yA and yB are equal for several rows (+/- Inf) or all rows (NaN). The input (yA - yB) to spm1d.stats.nonparam.ttest(yA - yB, 0, varargin{:}); being then composed of many zeros.

I am a new spm user so any insights about this issue would be helpful.

Many thanks,

**Comment by 0todd0000** [comment]
Hi, thank you very much for reporting this problem!

If yA and yB are equal for all rows, then the difference:

```matlab
d = yA - yB;
```

is an array containing all zeros, is that correct?  If so, the NaN is returned because there is zero variance.  When variance is zero the t statistic blows up because it is defined basically as: mean / variance.

I'm not sure why the +/- Inf occurs...
How many of the rows are equal?
If possible, please plot the differences as below and attach to your reply.

```matlab
d = yA - yB;
plot( d' )
```

Cheers,
Todd

**Comment by antoinefalisse** [comment]
Thanks for the quick reply.
Here is the plot (top YA-YB, bottom plot resulting for matlab code below). I also attached the data.

    spm = spm1d.stats.nonparam.ttest_paired(YA, YB);
    spmi = spm.inference(0.05, 'two_tailed', true, 'interp', true, 'iterations',10000);
    spmi.plot();

![test](https://cloud.githubusercontent.com/assets/19328993/26821719/b2432708-4aa7-11e7-9aaa-bb47a7fd6cf2.png)

> When variance is zero the t statistic blows up because it is defined basically as: mean / variance.

Does that mean that the non-parametric test is not suitable in that case? Should I then go for the parametric one for which I do not see that problem or should I adapt the code so that 0 is returned instead of Inf/NaN?

Many thanks;
Antoine

[Data.zip](https://github.com/0todd0000/spm1dmatlab/files/1054346/Data.zip)

**Comment by 0todd0000** [comment]
Hi Antoine,

If there is no variance then the data can't be analyzed statistically (i.e. neither parametrically nor non-parametrically).  If you try to repeat the analysis using a parametric approach (**spm1d.stats.ttest**) you should find that the t statistic is exactly the same as for the non-parametric test.  The only differences between the parametric and non-parametric approaches (in **spm1d**) pertain to probability calculations (not to t statistic calculations).

In the data you sent there is clearly no variance in the measurements between positions 20% and 55%, and all values appear to be zero in this region.  Do you know if there is an experimental reason why all values are zero?

Todd

**Comment by antoinefalisse** [comment]
Thank you for this clear explanation. 

>  Do you know if there is an experimental reason why all values are zero?

The values can be zeros in both models and this actually makes sense that if one model outputs zero, the other one outputs zero too.

Many thanks for your help,
Antoine
