### ISSUE TITLE
0-indexed cluster

### ISSUE THREAD

**Issue by pariterre** [0todd0000/spm1dmatlab#50]
Dear programmer!

I am using this very well designed statical toolbox for my curves analysis since a few time now. I just came something surprising this morning. The clusters return by "clusters" when I perform spm1d.stats.ttest_paired; inference(0.05), seems to return indexes 0 indexed, instead of 1-index as it is in matlab. I have not tested with other tests.

The main problem is unless you hit an error as I did (having a difference at the first frame, giving you the "Subscript indices must eigher be real positive integers or logicals"), you will have your data one frame off relative to the statistics without being aware of that. 

Is this the normal behavior?

Thanks again for the toolbox!

**Comment by 0todd0000** [comment]
Hi pariterre,
Thank you for your feedback!

Your interpretation is indeed correct if you regard the results from the perspective of array indexing.  However, **spm1d** produces *continuum position* results, not *array index* results. The initial position in a continuum is usually zero and not one.  For example, if the 1D continuum represents time, then initial time is conventionally time=0 (and not time=1).

Another way to interpret the **spm1d** results is in the context of node-based vs. element-based sampling:

![basic-3](https://user-images.githubusercontent.com/4276626/27249466-3b1c15f6-5351-11e7-94b0-124ec72a0310.png)

**spm1d** uses node-based sampling by default, where the first node is zero.  The array indexing perspective is equivalent to an element-based sampling perspective.  So please regard the results as node-based continuum sampling results (and not array indexes) where the first node is zero by convention.

As you correctly note, the continuum positions are:

```matlab
>>  q = 0 : Q-1;
```
where *Q* is the total number of nodes.


Cheers,

Todd

**Comment by pariterre** [comment]
Make sense :)
Thanks for your fast answer!
