### ISSUE TITLE
No negative t value?

### ISSUE THREAD

**Issue by alexisbrierty** [0todd0000/spm1dmatlab#51]
I used the paired t-test to analyse my pre/post data, and the spm graph displayed the dotted line at t*=2.624. If my understanding is correct, should this t line also appear at the negative axis? With any value <-2.624 having p<0.05?

If so, what do I need to alter in the code to display this negative t line? In my notes from the workshop I attended at ISB, this should be automatic? I am happy to attach the output from the code if I haven't explained clearly.

Thanks in advance,
Alexis

**Comment by 0todd0000** [comment]
Hi Alexis,

The code below demonstrates how two- vs. one-tailed inference can be controlled in **spm1d**.  When "two_tailed" is "true" both upper and lower thresholds should be displayed. When "two_tailed" is "false" only an upper threshold will appear.  By default "two_tailed" is true.

```matlab
spm       = spm1d.stats.ttest_paired(yA, yB);

spmi1      = spm.inference(0.05, 'two_tailed', false);
spmi2      = spm.inference(0.05, 'two_tailed', true);
```

Here is a link to relevant documentation at **spm1d.org**:
http://www.spm1d.org/doc/Theory/twotailed.html

Best,
Todd

**Comment by alexisbrierty** [comment]
Hi Todd,
Sorry for the late response. This was exactly what I needed. Thanks so much!
