### ISSUE TITLE
Effect size and Power Calculations

### ISSUE THREAD

**Issue by gillianweir** [0todd0000/spm1dmatlab#54]
Hi Todd,

Hope you are well! 
We have a PhD student here who is writing his dissertation proposal is thinking about using SPM in his analyses. Before he proposes it I just wanted to see how far off you guys are from having effect size calculations in the code?
Also do you have a power calculation method that you currently use/are developing for SPM? He is doing OSim and will be recruiting 10 male participants to compare different walking strategies (DVs: GRFs, lower limb kinematics).  He also wanted to compares this to 3 chimpanzees but going off the feed with Johannes would you recommend to not do this analysis with SPM?

Many thanks in advance.

Gill

**Comment by 0todd0000** [comment]
Hi Gill!

>  Before he proposes it I just wanted to see how far off you guys are from having effect size calculations in the code?

The code should be available later this year or early in 2018.

> Also do you have a power calculation method that you currently use/are developing for SPM? 

Yes, there is a Python package available here:
www.spm1d.org/power1d/
and a MATLAB version will be available by early 2018.
The package is described in the following article:
https://peerj.com/articles/cs-125/

> ...would you recommend to not do this analysis with SPM?

It depends what the goal is.  If the goal is population-level inference then three individuals is likely too few. But that limitation is not specific to SPM. I don't know of any technique that can make solid population-level inferences from just three individuals.  If you send more details like the goal of the study and the type of test he intends to use I'll try to answer a bit more clearly...

Todd

**Comment by gillianweir** [comment]
Hi Todd,

Thanks so much for that. Very excited for those new packages!

I certainly agree with that last point, however due to limitations with the lab that we had set up to collect chimp data n=3 is the current sample. The goal is to compare different walking postures (normal and different crouched postures) in 10 human participants. The second part is to compare those 4 postures in humans (n=10) to chimpanzee walking postures (n=3). I imagine the 10 human subjects comparing the 4 postures will be fine but humans vs chimps must use a descriptive approach. 

Thanks again,

Gill

**Comment by 0todd0000** [comment]
Hi Gill,
I agree that a descriptive approach might be best with a sample size of three.  You can try making statistical inferences as well, but the critical threshold will be quite high due to small sample size, so the effects would need to be quite large to yield significance.  If inference doesn't yield significance it may actually be a Type II error, so to avoid that it may indeed be best to conduct power analysis before conducting hypothesis testing to determine how powerfully the current sample sizes can detect a particular effect.
Todd

**Comment by gillianweir** [comment]
Todd many thanks again for your always valuable insight.

**Comment by burniel** [comment]
Hi, I have just been reading through the thread and was wondering if the effect size calculations code been realized yet?

**Comment by 0todd0000** [comment]
Not yet unfortunately.  Effect size calculations for simple experiments are complete but they're not yet ready for release. General effect size calculations for arbitrary experiments are still in development. If you have a particular design in mind (e.g. two-sample t test) I'd be happy to copy some code here.

As another option, the **power1d** package (www.spm1d.org/power1d/) cited above can be used to systematically explore arbitrary effects in arbitrary experiments, and in particular to calculate the probabilities of observing specific true effects.

**Comment by burniel** [comment]
Hi Todd,

I am using paired t-tests (for joint moments and angles) and Hoteling’s paired T2 tests (for crank forces). So if you have matlab code available for those cases that would be great.

Thanks

Louise
