### ISSUE TITLE
Time Normalization (Registration) for Foot Pressure data  

### ISSUE THREAD

**Issue by depakroshanblu** [0todd0000/spm1dmatlab#57]
Hi all, 

Thanks Todd, Jos and Mark for the workshop at ISB17. I have started to explore SPM for one of the work here. 

I have vertical GRF measured as a function of time and i want to compare two subjects against each other. I want to know in this case, which method is suitable to time normalise this data.  

Generally does time normalization methods depends upon the data ? 

Thanks for the reply.

**Comment by 0todd0000** [comment]
Hi, thank you very much for your feedback!

I'd say that the appropriate normalization method depends more on the hypothesis than on the data.  If you use linear registration then all 'morphological' (i.e. relative timing) information is retained. If you use piecewise-linear registration or another nonlinear registration technique the relative timing information becomes distorted.  So if your hypothesis pertains test both amplitudes and relative timing you should use linear registration.  If your hypothesis pertains only or primarily to amplitude differences then nonlinear registration may be appropriate.

Another strategy would be to conduct both linear and nonlinear registration and then compare the results.  Differences that emerge are likely attributable to relative timing.

Todd
