### ISSUE TITLE
Multiple trials and Normality

### ISSUE THREAD

**Issue by 1LNE** [0todd0000/spm1dmatlab#59]
Hi 

I am conducting both independent samples t-tests and paired samples t-tests with some data I have collected. I first wanted to clarify- I have 3 trials for each participant do I average these or put them into matlab as individual trials? 

Secondly I have run normality tests and have found for very small portions of the data that the data is not normally distributed. Would there be a problem with using a parametric test in this instance as for 0d data I have read this to be more statistically powerful?

Thanks in advance for your help with this

**Comment by 0todd0000** [comment]
Hello!

>  I have 3 trials for each participant do I average these or put them into matlab as individual trials?

If your hypothesis pertains to the population from which the subjects were randomly drawn, then use within-subject averages.  If your hypothesis pertains to the population of trials from which trials were randomly drawn then use all measured trials, and run separate tests for each subject (and correct for multiple comparisons across subjects).

> Secondly I have run normality tests and have found for very small portions of the data that the data is not normally distributed. Would there be a problem with using a parametric test in this instance as for 0d data I have read this to be more statistically powerful?

First note that the results do not necessarily imply that the data are not normally distributed;  the results instead mean that normally distributed data would produce a similar result relatively rarely.  Thus the results do not strictly suggest that non-parametric procedures should be used.  Instead I'd recommend trying both parametric and non-parametric tests.  If the results do not differ qualitatively it would suggest that the parametric approach's assumption of normality is a reasonable one.

A similar issue was recently raised here:
Issue #56.

Regarding power:  parametric procedures are indeed often more powerful than non-parametric procedures for 0D data, but the same is not necessarily true for 1D data, nor is it necessarily true for the permutation tests that **spm1d** employs.  When comparing parametric and non-parametric critical thresholds over a number of datasets you'll likely find that the non-parametric threshold is often lower than the parametric threshold, implying that the non-parametric approach may be more powerful.

With regards,
Todd
