### ISSUE TITLE
Problem with SPM example under Matlab R2011b

### ISSUE THREAD

**Issue by fmoissenet** [0todd0000/spm1dmatlab#6]
Hi,

I an trying to install SPM1D for clinical motion analysis data.
I am using Matlab R2011b.

I followed the recommandations for a "correct" installation, but when I try any example, I receive the message:

Error using spm1d.stats.spm.SPM
The specified super-class 'matlab.mixin.CustomDisplay' contains a
parse error or cannot be found on MATLAB's search path, possibly
shadowed by another file with the same name.

Error in spm1d.stats.glm (line 20)
    SPM      = spm1d.stats.spm.SPM('T', t', [1 df], fwhm, resels, b,
    eij, sigma2);

Error in spm1d.stats.ttest (line 9)
[SPM]         = spm1d.stats.glm(Y, X, c); 

It is due to the Matlab version? or something else? I am working on a desktop with Windows 7 pro.

Thank you,
Florent.

**Comment by 0todd0000** [comment]
Hi Florent,
Yes, the problem is the MATLAB version.  **spm1d** requires R2014b or newer:
http://www.spm1d.org/install/InstallationMatlab.html
It might work on R2014a and the 2013 versions, but it will likely not work on earlier versions than that because it uses recent MATLAB features. 
Todd

**Comment by fmoissenet** [comment]
Thank you!
Florent.
