### ISSUE TITLE
Running an example 

### ISSUE THREAD

**Issue by depakroshanblu** [0todd0000/spm1dmatlab#60]
Running an example results in the following error

Message Key ArgumentFailedValidation was not found in the catalog MATLAB:InputParser

What this error possibly means ?
Thanks

**Comment by 0todd0000** [comment]
Hello,
I'd be happy to help but require additional information.
-- What example are you trying to run?
-- What version of Matlab are you using?
Todd

**Comment by depakroshanblu** [comment]
I have tried multiple examples. So i suppose its a geenral technical error i suppose!
For example SPM1D
ex1d_ttest.m

.. I am using Matlab R2017a ... I tried it in R2016a also. I get the same error.
Thanks for your help.

**Comment by depakroshanblu** [comment]
I have tried multiple examples. So i suppose its a general technical error!
For example SPM1D
ex1d_ttest.m

.. I am using Matlab R2017a ... I tried it in R2016a also. I get the same error.
Thanks for your help.

**Comment by 0todd0000** [comment]
I'm also using R2017a but I cannot reproduce that error.  Please try the following...

1.  Please send the entire error message.
(I searched the internet for "ArgumentFailedValidation" but can't find any information about it, so additional information about the error might help.)

2. Try entering the following command in the Command Window:
```
spm = spm1d.stats.ttest(0);  #a zero as the input value
```
Does that also generate an error?

**Comment by depakroshanblu** [comment]
Hi Todd, 

I am really sorry. Apparently i figured it out there was a bug when i ran it through the institute server. 
Thanks for your help!

**Comment by 0todd0000** [comment]
No problem, I'm glad it's working!
