### ISSUE TITLE
spm1d on mesh (3D)

### ISSUE THREAD

**Issue by romainmartinez** [0todd0000/spm1dmatlab#61]
Hi Todd, 

In the paper below, you talk about 3D datasets (_Simulation B, for example_) and perform two-sample t-tests on them. 

> Pataky, T. C. (2010). Generalized n-dimensional biomechanical field analysis using statistical parametric mapping. Journal of biomechanics, 43(10), 1976-1982.

In my current analysis, I have 2D mesh models for 6 conditions: 

6 times the following mesh for each participant:

| variables    | dimensions |
|--------------|------------|
| angle (X)    | 1, 21      |
| velocity (Y) | 1, 21      |
| torque  (Z)  | 21, 21     |

Note that angle and velocity (_X and Y_) are independent variable (_constant across the conditions and the participants_) while torque (_Z_) is the dependent variable.

On matlab, the following line of code results in the image attached

```matlab
mesh(angle, velocity, torque)
```
![mesh](https://user-images.githubusercontent.com/17710617/31780141-dcfded18-b4c2-11e7-827f-f01c267a3d53.jpg)

I want to perform a one-way repeated measures ANOVA to test whether the position has an effect on the mesh.

It seems to me that datasets > 1D are not mentioned in the `spm1d` documentation.

Does the spm1d `spm1d.stats.anova1rm` API works for 3D inputs matrix?

Thank you for the spm1d package.

*-- Romain Martinez.*

**Comment by 0todd0000** [comment]
Hi Romain,

**spm1d** directly supports analysis of only one-dimensional continua. You can think of this type of data as "1D-*n*D", where 1 is the dimensionality of the continuum and where *n* is the dimensionality of the dependent variable.

The data you describe sound like 2D-1D.  That is, there is a scalar value (torque) which varies over a 2D continuum (defined by angle and velocity).  If that interpretation is correct then you can indeed use SPM to analyze these  data.

However, you are correct to note that **spm1d** documentation does not mention *m*D-*nD* continua for *m* > 1.  **spm1d** directly supports both parametric and non-parametric inference, but only for 1D-*n*D data.  It also indirectly supports non-parametric inference for *m*D-*n*D data.  To non-parametrically analyze 2D-1D data, for example, just flatten all of the 2D continua into 1D vectors, then use **spm1d** to run non-parametric analysis to compute a critical threshold. Afterwards you can reshape the 1D test-statistic continuum (or, conventionally, the 1D "statistical parametric map") back into its original 2D form, and then visualize regions of the 2D continuum that survive the critical threshold.  One caveat is that this pertains only to continuum-level inference (i.e. a critical threshold).  For 1D-*n*D continua **spm1d** also computes cluster-level and set-level probabilities.  **spm1d** is currently unable compute cluster-level and set-level inferences for *m*D continua where *m* > 1.

Another option is to use a different software package like SPM12:
http://www.fil.ion.ucl.ac.uk/spm/software/spm12/
SPM12 is designed primarily to analyze 3D-*n*D and 4D-*n*D continua, but you can also use it to analyze 2D-*n*D continua and 1D-*n*D continua. SPM12 conducts continuum-level, cluster-level and set-level inference for arbitrarily dimensioned data (up to 4D-*n*D, I believe) and you can even use SPM12 to analyze 0D-*n*D data.  However, analyzing 0D data is much easier with standard software packages like R, MATLAB, SPSS, etc.  Incidentally, **spm1d** also supports 0D-*n*D analyses. **spm1d** is really just a light-weight version of SPM12, with a small fraction of its functionality, but optimized in many senses for the analysis of 1D-*n*D continua.

There are currently no publically-released software packages of which I am aware that are focussed on 2D-*n*D data.

Todd

**Comment by romainmartinez** [comment]
Hi Todd and thank you very much for the detailed response.

I tried what you suggest to non-parametrically analyze 2D-1D data on a subset of data (2 participants):

> note: the following code is in Python

1. reshape my 2D-matrix (`torque.shape = (21, 21)`) with `np.flatten()` which result to a `(1, 441)` vector for each observation

2. run the non-parametric anova with the following variables

| variables | dimesions |
|--------------|---------------|
| `y`             | `(12, 441)` |
| `participants` | `(12,)` |
| `positions` | `(12,)` |

```python
alpha = 0.05
spm = spm1d.stats.nonparam.anova1rm(y, positions, participants)
spmi = spm.inference(alpha, iterations=10000)
print(spmi)

spmi.plot()
spmi.plot_p_values()
spmi.plot_threshold_label()
plt.show()
```

```
SnPM{F} inference field
   SPM.effect         :  Main A
   SPM.z              :  (1x441) raw test stat field
   SnPM.nPermUnique   :  4.79e+08 permutations possible
Inference:
   SPM.alpha          :  0.050
   SPM.zstar          :  20.80736
   SPM.h0reject       :  False
   SPM.p              :  ()
```
![foo](https://user-images.githubusercontent.com/17710617/31832459-18d4daa4-b595-11e7-893e-e272fa8226fe.png)

Is this is the procedure you suggested?

Thank you very much,

*-- Romain Martinez.*

**Comment by 0todd0000** [comment]
Hi Romain,

Yes, that is the procedure, but to visualize the results in their original 2D context you need to reshape the test statistic (SnPM{F}), which is now a 1D continuum.

First retrieve the test statistic and critical value from the SPM structure like this:

```matlab
z = spmi.z;   %F statistic
zstar = spmi.zstar;   %critical F statistic
```

Then reshape, threshold and plot like this:

```matlab
z = reshape(z, [21 21]);
z(z<zstar) = nan;  %hide all values less than critical threshold
pcolor(z)
```

In the results you attached you'll see that no point in the continuum survives the threshold, so the thresholding step above (```z(z<zstar) = nan```) will create a blank 2D continuum.  One reason may be:  too few subjects.

Todd

**Comment by romainmartinez** [comment]
Thank you Todd, I close the issue.

**Comment by 0todd0000** [comment]
Preliminary support for 2D data analysis has been added to **spm1d**!
[Example 2D analysis (Python)](http://www.spm1d.org/doc/Stats2D/ex2d.html)
[Example 2D analysis (MATLAB)](http://www.spm1d.org/doc/Stats2D/ex2d_matlab.html)

**Comment by Little-Foot-Shapes** [comment]
Hi Todd, 

I was wondering if I could use the above principle for 3D point clouds\triangulated surfaces, where I have data for each point\vertex. The point clouds are registered. Can I simply flatten out my 3D data and perform ANOVA on the points?

Thank you.

Best Regards
Mat

**Comment by 0todd0000** [comment]
Redirecting to #119
