### ISSUE TITLE
Hotellings (paired)test - to compare crank forces in two conditions

### ISSUE THREAD

**Issue by burniel** [0todd0000/spm1dmatlab#64]
Hello

I have used Hotellings T2 (paired)  test to compare crank forces for riders pedaling in two different conditions (on the track and in the lab). I have prepared the variables for input into SPM where the rows are the number of participants, columns - the number of field nodes - 101, and the 3rd dimension the number of force vectors which in this case has two components (effective and ineffective crank force). Is this the correct way to input 2D forces? I have attached a plot of the crank forces and my SPM output. Also it possible to plot the SPM results against crank angle so 0 to 360 degrees instead of % of crank cycle as in cycling research this is the most common way to present data.
Thanks
Louise
[Hotellings paired test SPM.docx](https://github.com/0todd0000/spm1dmatlab/files/1565939/Hotellings.paired.test.SPM.docx)

**Comment by 0todd0000** [comment]
Hi Louise,

A good question!  This is something that really should be implemented in **spm1d** but is not yet available.  I hope to have it ready for the next main release.  In the meantime there are three options I can think of:

1.  Manually change the x tick labels:
https://uk.mathworks.com/help/matlab/ref/xticklabels.html

2.  Resample from [0, 100] to [0, 360] using one of MATLAB's interpolation functions like this one:
https://uk.mathworks.com/help/matlab/ref/interp1.html

3.  Manually construct the plot by accessing fields of the the SPM object.  The test statistic and critical threshold, for example, can be accessed in the "SPM.z" and "SPM.zstar" fields, respectively, like this:
```matlab
>>  spm  = spm1d.stats.ttest2(YA, YB);
>>  spmi = spm.inference(0.05, 'two_tailed',true, 'interp',true);

>>  crank_angle = linspace(0, 360, 101);
>>  plot(crank_angle, spmi.z);
>>  plot(crank_angle, spmi.zstar * ones(1,101));
```


An unrelated side-issue:
Option 2 would be an interesting exercise to demonstrate the consistency of the SPM approach:  if you resample the data to 360 nodes (or 3600 or 3.6 million for that matter), the SPM results should be qualitatively stable.  There might be small numerical changes in the critical thresholds and probability values, but there should be no qualitative changes in the overall results.  This exercise would emphasize that SPM results are driven by continuum smoothness with respect to the total continuum size, irrespective of the number of nodes (i.e. sampling frequency) used to characterize the underlying continua.  SPM results should be stable to all sampling frequencies provided they are above the Nyquist criterion (i.e. sufficiently high to avoid aliasing). 

Todd
