### ISSUE TITLE
ANOVA debugging (one-way repeated measures).

### ISSUE THREAD

**Issue by 0todd0000** [0todd0000/spm1dmatlab#7]
(This opens the end of issue #1 as a new issue).

Lotte wrote:

__________________________________________________

Hy Todd, Thanks for all your work. I have a question though:
I try to do the spm.inference (0.05) while using the following script:

Y = Datamis.KnieG; (27x101)
A = Convmis; (27x1)
SUBJ = PPvmis; (27x1)

F = spm1d.stats.anova1rm( Y, A, SUBJ);
Fi = F.inference(0.05)
Fi.plot()

However I get the following error when trying tor run F.inference(0.05):

In an assignment A(:) = B, the number of elements in A and B must be the same.

Error in spm1d.stats.spm.SPM/get_p_values (line 108)
p(i) = self.get_p_value(kk(i), uu(i), two_tailed);

Error in spm1d.stats.spm.SPM/inference (line 72)
p = self.get_p_values(extentsR, heights, two_tailed);

I tried some thing already but nothing works ou. Could u please help me?

Best regards
Lotte

__________________________________________________

**Comment by 0todd0000** [comment]
Hi Lotte,

Everything looks OK in your description.  To help debugging, please follow these steps:

First, please check that you're using the most recent version: M.0.3.1 (2015.08.28).

Next, please tell me if the 0D and 1D example files run:
./examples/stats0d/ex_anova1rm.m
./examples/stats1d/ex1d_anova1rm.m

Last, if you can run those files without any errors then there is likely a problem in the variable contents. Please copy the contents of A and SUBJ into your reply.

Cheers,

Todd

**Comment by Lilalol** [comment]
HyTod,
Thank you for your quick respons. I do have the right version. The ./examples/stats0d/ex_anova1rm.m seems to work, but for the example file './examples/stats1d/ex1d_anova1rm.m' I get the same error as when I run my own script.

So the content of my SUBJ vector is: 
SUBJ = [1 2 4 5 6 7 8 9 10 1 2 4 5 6 7 8 9 10 1 2 4 5 6 7 8 9 10]';

And the content of my SUBJ vector is: 
A = [1 1 1 1 1 1 1 1 1 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5]'

Hope u can help me!

kind regards
Lotte

**Comment by 0todd0000** [comment]
Hi Lotte,

If the example script produces an error then there must be a problem with installation.

What version of MATLAB are you using?
If it is older than R2014b please try updating to R2015b.

Do you have any other versions of spm1d installed?
If so please delete all of them except the most recent version.

Next, please try running some of the other example scripts, especially the t test, regression and one-way ANOVA:
* ./examples/stats1d/ex1d_regression.m
* ./examples/stats1d/ex1d_ttest_onesample.m
* ./examples/stats1d/ex1d_ttest_paired.m
* ./examples/stats1d/ex1d_ttest.m
* ./examples/stats1d/ex1d_ttest2.m
* ./examples/stats1d/ex1d_anova1.m

Does the error occur for any of these files?

Regards,
Todd

**Comment by Lilalol** [comment]
Hi Todd,

Sorry for my late reply. I am using matlab 2015b and I download the latest version of your program. However I did it twice may that give trouble?
All the examples you mention are working, except for the ex1d_anova1. I get the same error :(.

I will deinstal your program and download it again. Let you know whether that will work out.

greetz lotte

**Comment by 0todd0000** [comment]
Hi Lotte,

Thank you for the updates.  This problem is strange, and I confess that I have no idea what is causing it.

If there are multiple copies of the software then it may indeed cause a problem, depending on how you've saved them on your computer and how you've specified the MATLAB path.


In your next reply can you please copy and paste:
* The entire error.
* The entire script (i.e. all commands executed before the error is generated)
* The result of the command: "whos" (i.e. please type "whos" then ENTER in the MATLAB command window and copy the results).
* The results of the command: "path",

This will be a lot of information but it might help us get to the source of the problem.

Apologies for these problems, I hope we can solve them soon.

Todd

**Comment by 0todd0000** [comment]
Hi Lotte,
I'll assume that the error has resolved itself and am closing this issue.  Please feel free to reply or open a new issue if you're still having problems.
Cheers,
Todd

**Comment by Lilalol** [comment]
Hi Tod

I am sorry, I forgot to come back to you. I solved the problem…. Not sure anymore how I solved it though…I think I reinstalled everything and than it worked.

Thanks a lot for your help!
Kind regards
Lotte
