### ISSUE TITLE
Two-way ANOVA RM within subjects

### ISSUE THREAD

**Issue by gillianweir** [0todd0000/spm1dmatlab#70]
Hi Todd,

I have data for 5 time points over the course of a run and two sessions. I want to run a two way RM ANOVA with both factors within-subjects and just wanted to check that I am correct in interpreting that the anova2rm would be the correct code for this and anova2onerm would be between x within. 

Thanks,

Gill

**Comment by 0todd0000** [comment]
Hi Gill,
**anova2rm** is indeed within-within, and **anova2onerm** is between-within.  So that sounds right, I think the former is what you want.
Todd
