### ISSUE TITLE
Comparison of means dependend groups but no varianz homogenity

### ISSUE THREAD

**Issue by SinaDavid** [0todd0000/spm1dmatlab#72]
Dear Todd,

We are working on a comparison of different motion capture systems (IMU and optical) and are facing serious statistical problems.
We want to compare the angular output of one subject, with 10 trials and we have 3 different measurement conditions (Myomotion, Myomotion calc and Vicon, see graph) as we have the same trials in all conditions, we need to use a paired design. However, the problem is, that the Myomotion calc (green) has really high standard deviations  compared to the two other conditions (red and black). therefore there is no homogenity of variances. And of course, the results are counter-
![graph](https://user-images.githubusercontent.com/9551718/36849193-a698084e-1d63-11e8-8f87-8d3adcd7fa66.PNG)
arguementing the visible differences in the progression of the curves.
Do you have any suggestions, what we should do? We really want to continue with spm, but I think there is no test that fits our needs...I think in descrete data we would use Welsch's test...
Thank you for your thoughts!

Best regards,
Sina

**Comment by 0todd0000** [comment]
Hi Sina,

One option is a non-parametric permutation test:

```matlab
snpm  = spm1d.stats.nonparam.anova1rm(y, A, SUBJ);
snpmi = snpm.inference(alpha, 'iterations', 10000);
```

This test does not assume sphericity so is valid even when groups have large variance differences.

Todd

**Comment by SinaDavid** [comment]
Hi Todd!

Thanks a lot!

Best regards,
Sina
