### ISSUE TITLE
multilevel mixed -effects linear regression

### ISSUE THREAD

**Issue by SiskaBossuyt** [0todd0000/spm1dmatlab#73]
When doing preliminary SPM analyses with force data before and after fatigue, I observed that different individuals have different changes (either an increase, a reduction or no change). So far, I used a two-tailed paired t-test but would there be a way to control for between subject variability within the analysis or is it possible already to conduct a multilevel mixed -effects linear regression with SPM? 
Many thanks in advance!
Siska

**Comment by 0todd0000** [comment]
Hi Siska,
If I understand your analysis correctly, a paired t test does consider the different changes of different individuals. It tests the hypothesis that the mean change is zero. If most subjects show an increase (or a decrease) the test will likely reach significance, even if some subjects show the opposite trend.
Todd

**Comment by SiskaBossuyt** [comment]
Hi Todd,
Many thanks for your quick reply and clarification, I really appreciate it. This is indeed what I meant. Does it also mean that if we do a linear regression with SPM it will also take into account the individual changes?
Many thanks again and wishing you a nice day,
Siska

**Comment by 0todd0000** [comment]
Hi Siska,

It depends what the dependent variable "y" is.  If "y" is within-subject force change, then linear regression will test the hypothesis of no correlation between those changes and an independent variable "x".

Todd
