### ISSUE TITLE
Post-hoc analysis with different sample size among groups

### ISSUE THREAD

**Issue by robertodimarco** [0todd0000/spm1dmatlab#74]
Good morning,

I am running a 1D-ANOVA on a dataset of patients and control subjects and, since the test gave significant differences, I need to run a post-hoc analysis.
The problem is: groups have no equal number of subjects (the Y0 and Y1 matrices have different number of rows), and the 1D post-hoc is not running in Matlab. Am I doing something wrong, or is there an intermediate step I am ignoring?

Thank you very much for all the time you will be able to spend for helping.

Best wishes,
Roberto

**Comment by 0todd0000** [comment]
Hello Roberto,
If Y0 and Y1 have different numbers of rows, then a two-sample t test (**spm1d.stats.ttest2**) should be possible but a paired t test (**spm1d.stats.ttest_paired**) is not be possible because the rows must be paired.
If this does not solve the problem, please copy-and-paste the error message here.
Thanks!
Todd

**Comment by robertodimarco** [comment]
Hello Todd,
thank you. I am using the two-sample t-test this way:
**t_mf_s=spm1d.stats.ttest2(MF,S);
ti_mf_s=t.inference(alpha_corrected,'two_tailed',true,'interp',true)**;

where dim{MF}=101x15 and dim{S}=101x7, but I get this error:

**Error using vertcat
Dimensions of matrices being
concatenated are not
consistent.

Error in spm1d.stats.ttest2
(line 8)
Y             = [yA; yB];**

I suppose I am doing mistakes calling the function.
Thank you again,
Roberto

**Comment by 0todd0000** [comment]
Hi Roberto,
The data arrays must be (*J* x *Q*), where *J* is the number of 1D observations and where *Q* is the number of continuum nodes.  So if you transpose the data arrays like below it should work.

```matlab
MF = MF';
S = S';
t_mf_s=spm1d.stats.ttest2(MF, S);
```

**Comment by robertodimarco** [comment]
Hi Todd,
yes, the script is now working properly.
Thank you,
Roberto
