### ISSUE TITLE
Linear regression (J x Q) arrays

### ISSUE THREAD

**Issue by HannahWyatt68** [0todd0000/spm1dmatlab#76]
Hi Todd,

We are looking to use spm1d to investigate the influence of biomechanical measures in one phase (preparatory phase) on the same measures in another phase (foot contact). Essentially, as the independent and dependent variables will be the same measure, they will have the same units. 

Having read your feedback on a previous issue that was raised (Linear regression analysis. #40), I think I'm correct in concluding that given the conditions as stated above, it is possible to run a linear regression on two data sets each with (J x Q) arrays. I was therefore wondering if any code has been developed for this or if you have any suggestions on how we can modify the current code to alter the independent variable from its current state as a J scalar.

Any advice you can offer will be much appreciated.

Kind regards,

Hannah

**Comment by 0todd0000** [comment]
Hi Hannah,

There may already be suitable code available, but please let me ask if my interpretation is correct. I'm picturing independent variables (IVs) and the dependent variable (DV) organized into a (J x Q+2) table like this:

```
IV1        IV2         DV
----------------------------------------------------
1          x1          y11, y12, ... y1Q
1          x2          y21, y22, ... y2Q
...
1          xJ          yJ1, yJ2, ... yJQ
----------------------------------------------------
2          x(J+1)      y(J+1)1, y(J+1)2, ... y(J+1)Q
2          x(J+2)      y(J+2)1, y(J+2)2, ... y(J+2)Q
...
2          x(J+J)      y(J+J)1, y(J+J)2, ... y(J+J)Q
```

where IV1 is "phase" and where IV2 is a continuous variable.

Is this interpretation correct?
And are you interested in effects associated with IV1 or IV2, or both?

Todd

**Comment by HannahWyatt68** [comment]
Hi Todd,

Thanks for getting back to me so quickly. Your interpretation is exactly right. We're interested in the influence of IV2 on DV. 

Please let me know if there is any further information you need.

Many thanks,

Hannah

**Comment by 0todd0000** [comment]
Thank you for confirming. This could be simple, or it could be quite complex depending on a few additional details...

* Was IV2 measured independently from DV?

* Repeated measures?  Did all subjects performed both Phase 1 and Phase 2?

* If repeated measures, is IV2 the same for Phases 1 & 2?  i.e. x1=x(J+1), x2=x(J+2), ...

**Comment by HannahWyatt68** [comment]
Thanks for your follow-up message.

IV2 is not independent from DV which is something I had previously overlooked in relation to linear regression assumptions violation. Would it be an option to use a correlation on this data set rather than a regression? 

All subjects performed phases 1 and 2 (they are distinct phases within the same skill) and IV2 is the same for phases 1 and 2. 

To hopefully build a better picture, the data set consists of:
-	Two groups (male and female – to be analysed separately)
-	One skill from which two distinct phases exist (preparatory and stance)
-	A number of biomechanical variables (to be analysed independently)

Our interest is looking at the extent to which preparatory phase mechanics influence stance phase mechanics for male and female athletes.

Thanks again for your help with this.

Hannah

**Comment by 0todd0000** [comment]
Hi Hannah,
The non-independence between IV2 and DV plus the repeated-measures nature of the design make it quite complex, and **spm1d** cannot currently handle those complexities. I'd recommend trying to find the correct solution for a single scalar DV (e.g. value at time=50%) in a package like SPSS or R. If you can find the correct solution please let me know what it is and I'll check to see if we could modify some existing **spm1d** functions to allow you to extend the model for analyses of 1D DVs.
Todd

**Comment by HannahWyatt68** [comment]
Thanks Todd. I'll have a look into it and will let you know when I find the statistical solution,

Hannah
