### ISSUE TITLE
spm1 statistical mentoring

### ISSUE THREAD

**Issue by PatricioUQ** [0todd0000/spm1dmatlab#80]
Hi Todd,
I would like to compare the effect of 2 different interventions on hip kinematics at 3 time points: before, after 4 weeks and after 12 weeks. The goal is to see which of these interventions affects more the ROM of the joint on a 1D continua. I have 2 groups of patients (G1 = 11 subjects; G2 = 12 subjects) each group received 1 intervention. I thought in the following for the analysis using spm1:

•	Two sample Hotellings T2 test to compare between groups at each time point (to see the co-variability of the 3 planes)
•	One way repeated measures ANOVA to see in each group the longitudinal differences between time points of the 1 plane that I am more interested

Here are my questions:

1) The new thing is the use of spm1 to compare the repercussion of these interventions on hip kinematics. The goal is to highlight that maybe we are missing something comparing these groups just with 0d statistics (which has been done before). Are the 1d statistics proposed appropriate to achieve these goals? Can you think in another approach or complimentary test that may help? Maybe reporting 0d statistics as well?

2) Maybe sample size is too small, but in this kind of population samples are usually small. I thought in some sample size calculations for spm1 but, I read some of the examples of the power package in python and these analyses exceed my capabilities. How can I justify what it looks a small sample size for a 1D analyses?

Regards
Patricio

**Comment by 0todd0000** [comment]
Hi Patricio,

Your suggest analyses ideas sound fine for the current version of **spm1d**, but the experimental design actually sounds like a two-way RM-MANOVA:

- Independent variables:  two groups x three time points
- Dependent variable: multivariate 1D  (3D hip angles in 1D time)

Unfortunately RM-MANOVA is not yet supported in **spm1d**.

Regarding 0D vs 1D analysis: this choice can be guided by the experiment's *a priori* hypothesis.  If there are specific 0D values in which you were interested before conducting the experiment, then 0D analysis is appropriate.  If instead you measured 1D data with the intent of analyzing the whole 1D dataset, then 1D analyses are probably appropriate.

Regarding sample size:  you only need to justify sample size when reporting non-effects. If an experiment detects an effect, then by definition the sample size was sufficient to detect that effect.  If, however, the experiment fails to detect an effect, then it may be important to clarify whether the sample size was sufficiently large to detect the effect you were hoping to detect. To do this requires a specific *a priori* effect definition.  For complex designs like this it's possible to calculate sample sizes through simulation, like in the power package you mention.  I'm unaware of any software package that supports sample size calculations for relatively complex designs like two-way RM-MANOVA. 

Todd

**Comment by PatricioUQ** [comment]
Hi Todd,

Thank you for your reply. I agree, a two-way MANOVA might be the logical statistical approach. I designed the proposed statistical test according to what is available in the current version of smp1. Do you think that this statistical analysis (Hottelings + ANOVA) designed with what we have still justifiable? I think that maybe presenting both 1D and 0D data is a good idea. Can you justify 1D power from 0D sample size calculations? 

Cheers

Patricio

**Comment by 0todd0000** [comment]
Hi Patricio,

> Do you think that this statistical analysis (Hottelings + ANOVA) designed with what we have still justifiable?

This should be fine provided that you clarify that these analyses are *post hoc* analysis and that the current version of **spm1d** cannot yet handle full two-way MANOVA.

> Can you justify 1D power from 0D sample size calculations?

This may be justifiable, especially when the 0D effect corresponds to the maximum 1D effect.
However, there are a few complications. One problem is that variance is usually not constant across time in 1D datasets, which means that a constant mean 1D difference does not correspond to a constant 1D effect. Another problem is that 0D effects have no temporal component, but usually the 1D effect one wishes to detect has temporal structure (e.g. e.g. maximum effect expected in vicinity of maximum flexion). A final problem is clarifying whether you'd like to look for effects in multiple 1D regions. So it's not possible to state that 0D sample size calculations are always suitable for 1D analyses, but in general they will be approximately correct if the 0D effect corresponds to the maximum 1D effect, and if no other large effects exist .

Todd
