### ISSUE TITLE
SPM 1D

### ISSUE THREAD

**Issue by anapsalazar** [0todd0000/spm1dmatlab#82]
Dear Dr Pataky,

I am trying to figure out how can I analyze some upper limb reaching kinematic angles on SPM1D, and I have some questions:

1- Can I use SPM 1D with SPM12 instead SPM8?

2- Can I import my data in txt or I need another extension?

3- Is there some tutorial to help in this first contact with the spm 1D software?

Thank you,

**Comment by romainmartinez** [comment]
Cannot tell for question 1 (I do not think it's possible) -- but the `spm1d` [documentation](http://www.spm1d.org/Documentation.html) answers questions 2 & 3.

**Comment by anapsalazar** [comment]
Thank you.
