### ISSUE TITLE
SPM1d for load-deformation curves?

### ISSUE THREAD

**Issue by DiesbouT** [0todd0000/spm1dmatlab#83]
Hi there,

Is it possible to use the SPM1d ANOVA analysis for curves that are not created by a variable over time/sample, but rather by two variables plotted against each other (ex: load-deformation curves with angle on the x-axis and torque on the y-axis)? The data have all be time-normalized, so every sample of angle corresponds directly to the torque in the same position.

So far, I have been successful at running the SPM ANOVA for Angle and Torque separately by entering an (n x Q) array where n = number of subjects (in this case, 30) and Q = number of samples (in this case, 200) for each variable across three different groups of subjects.

Any thoughts on how I can  compare my three angle-torque curves using SPM1d ANOVA and how to alter the Matlab script accordingly?

Thank you!
Tara

**Comment by 0todd0000** [comment]
Hi Tara,

The continuum variable can be anything (time, space, or an arbitrary variable). The only caveat is that there must be just one measured value (scalar or vector) at each point *q* in the continuum.  So SPM can be used to analyse loading or unloading curves, but not loading-unloading curves like this:

![elastic_hysteresis svg](https://user-images.githubusercontent.com/4276626/41878952-535d97b0-7912-11e8-90c6-6f3b71b94cb3.png)

(image from https://en.wikipedia.org/wiki/Hysteresis)

As long as you arrange the data into an (n x Q) array the ANOVA example code should be fine.

Todd

**Comment by DiesbouT** [comment]
Hi Todd,

Thank you for your reply. I am only looking at the loading phase, so that is not an issue. In the above example, how would I enter the data for both the extension and the force into the ANOVA function? Would I combine them into one single variable (ie: extension/force) at each point q?

I appreciate the insight!
Tara

**Comment by 0todd0000** [comment]
Each column of the (n x Q) data array should represent a single extension value, and each row should represent a single loading curve.  The columns should represent monotonically increasing values from zero to maximum extension.  Thus "extension" (from 0 to 100%) replaces the usual "time" variable.
