### ISSUE TITLE
Non parametric Hotelling's T2 Test

### ISSUE THREAD

**Issue by Enrica2018** [0todd0000/spm1dmatlab#85]
I need to run a non parametric hotelling t test. For doing so I added  'nonparam' to my parametric code :
spm       = spm1d.stats.nonparam.hotellings2(YA1, YB1);
spmi      = spm.inference(0.05);

however Matlab gives me the following error:
Error using spm1d.stats.nonparam.permuters.APermuter/check_iterations (line 62)

The total number of iterations (137846528820) is very large and may cause computational problems. In the call to "inference"...
(1) Set "iterations" to a number between 10 and 10,000, or
(2) set "force_iterations" to "true" to enable calculations for iterations > 10,000.
NOTE: Setting "force_iterations" to "true" may require substantial computational resources and may cause crashes. USE WITH CAUTION.

Error in spm1d.stats.nonparam.snpm.ASnPM1D/inference (line 50)
           self.permuter.check_iterations(alpha, iterations, force_iterations)

Error in spm_hotelling (line 20)
spmi      = spm.inference(0.05);

How can I solve this?

thanks for the help,
ENrica

**Comment by Enrica2018** [comment]
Thanks Mark for your quick  reply and clarification.

How do I know how many iterations I should run? Is 10000 the recommended number?

Also in my parametric code I create figures but the code is freezing every time I try to do so with non-parametric functions. What should I used instead of this:
spmi.plot();
spmi.plot_threshold_label();
spmi.plot_p_values();

thanks
Enrica

**Comment by Enrica2018** [comment]
I now got the figure function working but still unsure about the number of iterations.

thanks 
Enrica

**Comment by m-a-robinson** [comment]
Hello Enrica,

Glad you sorted the visualisation problem.

The number of iterations is discussed a number of times on the forum so hopefully you forgive me directing you to previous answers.
https://github.com/0todd0000/spm1dmatlab/issues/53#issuecomment-322811000 
https://github.com/0todd0000/spm1dmatlab/issues/69#issuecomment-361143060

One consequence from using a low number of iterations, is that many of the p-values generated are identical. For SnPM, p values mean the following: p percent of permutations produced at least one cluster at least as large as the given cluster. If there are N permutations then the minimum possible p value is 1/N. Even if clusters are vastly different sizes they will have the same p value. Increasing the number of iterations will solve this problem hence the recommendation. 
This is also discussed here https://github.com/0todd0000/spm1dmatlab/issues/45#issuecomment-299595107

Regards
Mark

**Comment by Enrica2018** [comment]
Great thank you. I will read those posts carefully.

Thanks for your help,
Enrica
