### ISSUE TITLE
Test-retest statistics for time series data

### ISSUE THREAD

**Issue by burniel** [0todd0000/spm1dmatlab#87]
I am doing a test-retest study measuring biomechanical variables (joint angles, moments etc) a week apart. I can use SPM to compare changes in the mean for the time series data. However are there any statistics that than can be used to compare similarity of time series between sessions? I can select discrete points (such as peak moment) and calculate ICC, CV or SEM for these points. However as I am using time series analyse for all my later studies it would be useful if I could use time series test-retest statistics.

**Comment by 0todd0000** [comment]
All statistics including the ICC, CV and SEM can be computed at the continuum (time series) level. However, **spm1d** does not currently support their computation directly, so you'll have to write a custom script to compute them.  We are currently working on a reliability module that will facilitate ICC computation, and I hope it will be ready in about one year.  

I've added ICC, CV and SEM to the list of **spm1d** feature requests here: 
https://github.com/0todd0000/spm1d/issues/45
Sorry that they're not yet available!

**Comment by m-a-robinson** [comment]
Hello,
Although again outside of the **spm1d** package, These methods may be of interest if you have not already come across them.

Schwartz MH, Trost JP, Wervey RA. Measurement and management of errors in
quantitative gait data. Gait Posture 2004;20:196–203.

Also the CMC approach e.g. 
Ferrari, A.,Cutti,A.G.,Cappello,A.,2010. A new formulation of the coefficient of multiple correlation to assess the similarity of waveforms measured synchronously by different motion analysis protocols. Gait and Posture31(4), 540–542.

**Comment by burniel** [comment]
Thank you, I have read Kadaba, 1989 paper on CMC, but I hadn't seen the Ferrari et al, 2010 update.

**Comment by Antoine-Cht** [comment]
Dear @0todd0000 

I am wondering if the ICC, CV, and SEM are currently available in the new release of the toolbox?
Otherwise we will implement a custom-made function to plot the ICC according our time-series. 

Thank you for your assistance.
Best
Antoine C

**Comment by 0todd0000** [comment]
Unfortunately these are still not supported in spm1d v0.4, apologies.
