### ISSUE TITLE
One way repeated measures ANOVA

### ISSUE THREAD

**Issue by burniel** [0todd0000/spm1dmatlab#88]
Hi,

I am trying to run a one way repeated measures within subject ANOVA. When I run the example and also when I try inputting my data into the anova1rm I get this warning message in MATLAB:
Warning: Only one observation per subject found.  Residuals and inference will be approximate. To avoid approximate
residuals: (a) Add multiple observations per subject and per condition, and (b) ensure that all subjects and
conditions have the same number of observations. 
> In spm1d.stats.anova.designs.ANOVA1rm/check_for_single_responses (line 33)
  In spm1d.stats.anova1rm (line 13)

[ANOVA inputs.xlsx](https://github.com/0todd0000/spm1dmatlab/files/2468461/ANOVA.inputs.xlsx)

I have 13 participants, three trials for each and then joint angle data for 101 time points for each trial (I have attached an excel spreadsheet with these (a worksheet for each variable formatted as in matlab) as I couldn't attached a matlab variable). Have I misunderstood how this works and I am I doing something wrong?

**Comment by m-a-robinson** [comment]
Hello,
The text below is copied from a previous reply to this question. I think this answers your query.
Note this is just a warning and the ANOVA output should still be generated.
Mark 

_This warning means only that there is one observation per participant and per condition, which in turn implies that the model residuals are null. In other words, repeated-measures ANOVA models contain terms for each participant and each condition, and after fitting all of those terms to the data there is no residual variability remaining. SPM uses residuals to estimate one-dimensional smoothness, so the warning indicates that smoothness will be estimated using pseudo-residuals, which are computed for each subject and averaged across subjects. Please see related discussions in spm1d's Python forum here:_
0todd0000/spm1d#43
0todd0000/spm1d#49

**Comment by burniel** [comment]
Thank you, this makes sense now. I assume I could remove the error by instead of inputting the trial mean for each subject, I include each individual crank revolution for the trial (the mean is the average of 6 revolutions)?

**Comment by m-a-robinson** [comment]
Yes including the individual trials would cause this error to disappear
