### ISSUE TITLE
Multivariate (vector) analysis - 3 trials

### ISSUE THREAD

**Issue by burniel** [0todd0000/spm1dmatlab#89]
Hi, sorry for another question. If I have a vector (Crank force which is made up of two components: effective and ineffective crank force) I can use Hotellings T2 test to compare two conditions. However I have 3 trials per participant is here a multivariate vector analysis version of the One-way repeated measures ANOVA I run for univariate data?

**Comment by 0todd0000** [comment]
No problem at all, thank you for your questions!

One-way RM-MANOVA is indeed possible in SPM but is not yet implemented in **spm1d**.

However, in this case it sounds like it may be possible to compute means for each participant and condition, then compare the two conditions using a paired Hotelling's T2 test.  That is, one-way RM-MANOVA is equivalent to a paired Hotelling's T2 test when there are only two conditions (provided you include just one observation -- the mean -- for each participant).
