### ISSUE TITLE
One way repeated measures ANOVA - interaction?

### ISSUE THREAD

**Issue by crisinma** [0todd0000/spm1dmatlab#91]
Hi Todd and SPM1d users, 

I am currently analyzing the effects of an intervention where we evaluated upper limb movement patterns in 3 time points (pre, post and follow up). The sample was divided in two groups according to the treatment received (i.e. placebo or experimental). If I am not mistaken, I should use a one-way repeated measures ANOVA to evaluate differences between groups over time. I see that the current example in the SPM1d toolbox evaluates the mian effect of 'group' (Main A), but only plots the main effect of 'time' (repeated measures). Is this like this or am I missing something? 
The other question that I had is that I am also interested in investigating whether there is an interaction effect between group and time (i.e. does the experimental group improve more than the placebo?). Is there a way to add the interaction term to the model or should I then use another code? 

Thank you very much in advance! 
Regards, 
Cristina

**Comment by 0todd0000** [comment]
Hi Christina,
It sounds like this is a two-way design (factor 1: TREATMENT, factor 2: TIME POINT), and that the appropriate function is **spm1d.stats.anova2onerm**: two-way ANOVA with one repeated measures (RM) factor. Here the RM factor is TIME POINT.  With this design an interaction effect will be returned. Please see the example script:  ./spm1d/examples/stats1d/ex1d_anova2onerm.m
Todd

**Comment by crisinma** [comment]
That makes sense, I was also playing with that one before and thebn I got somwhow confused. But now it is very clear. Thank you very much for the quick reply! 

Regards, 
Cristina
