### ISSUE TITLE
Adjusted p-value for repeated t-test

### ISSUE THREAD

**Issue by meteor77** [0todd0000/spm1dmatlab#92]
Hi Todd,

Normally when we are using repeated t-test we tend to adjust the p-value by a Bonferroni correction or other similar methods. Is there a function in the Matlab package so that I can implement this, or should I just take the largest p-value calculated by SPM and adjust the p-value?

Best,
Shahab

**Comment by 0todd0000** [comment]
Hi Shahab,

Two relevant functions in **spm1d** are:

* spm1d.util.p_critical_bonf
* spm1d.util.p_corrected_bonf

Examples:

```MATLAB
alpha = 0.05;  %Type I error rate
n     = 6;     %Number of independent tests
p_critical = spm1d.util.p_critical_bonf(alpha, n)   %Result: 0.008512
```

```MATLAB
p = 0.0081;  %Example cluster-level p value from inference results which use p_critical
n = 6;       %Number of independent tests
p_corrected = spm1d.util.p_corrected_bonf(p, n);   %Result: %0.0476
```

Note that the maximum possible cluster-level p value is *p_critical* by definition, so the maximum possible corrected p value is *alpha*.

Todd

**Comment by meteor77** [comment]
Thanks Todd,

It was really helpful.
