### ISSUE TITLE
SPM1D ttest_paired limit number subject ?

### ISSUE THREAD

**Issue by andriacapai** [0todd0000/spm1dmatlab#94]
Hello,

I encountered a problem after using  the function spm1d.stats.normality.ttest_paired with the function spm.inference(0.05); . 

Here is the error :
"Error using  ~ 
Operands must be real."

Here is my two matrix YA and YB : 
- YA (200*200 NxM  with N=[100 stride of the subject 1 and 100 strides of the subject 2] for the condition A
- YB (200*200 NxM  with N=[100 stride of the subject 1  and 100 strides of the subject 2] for the condition B
Subject 1 and 2 did both condition. 

I tried to use only 75 strides for each subject (Matrix YA and YB = 150x200) and it works ...
Do you have any idea about how to unlock the limit number ? Or in case the problem is not about the number could you advise me what is the best test according to my data set ?

Thank you.

Best,

Andria

**Comment by 0todd0000** [comment]
Hi Andria, there is no limit on N, so I suspect that there is a problem in data.

Can you please copy and send the full error?  The full error will give information about what function and what line of code is causing the problem, and this will help me figure out what's going on.

Also, can you please copy and send the output of:

```matlab
t = spm1d.stats.ttest_paired(YA, YB);
disp(t)
```

Thanks!

**Comment by andriacapai** [comment]
Hello Todd,

Here is the entire error message :
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Error using  ~
Operands must be real.

Error in spm_P_RF (line 94)
if     ~k || ~D

Error in spm_P (line 51)
[P,p,Em,En,EN] = spm_P_RF(c,k,Z,df,STAT,R,n);

Error in spm1d.rft1d.RFTProbability/cluster (line 15)
           p = spm_P(1, k, u, c.df, c.STAT, c.resels, c.n, c.Q);

Error in spm1d.rft1d.chi2.p_cluster_resels (line 50)
            p = calc.p.cluster(k, u);

Error in spm1d.geom.Cluster/inference (line 55)
                    p = spm1d.rft1d.chi2.p_cluster_resels(k, u, df(2), resels, 'withBonf',withBonf, 'nNodes',nNodes);

Error in spm1d.stats.spm.SPM/cluster_inference (line 124)
                    clusters{i} = clusters{i}.inference(self.STAT, self.df, self.fwhm, self.resels, two_tailed, withBonf,
                    self.nNodes);

Error in spm1d.stats.spm.SPM/inference (line 92)
            [clusters,p] = self.cluster_inference(clusters, two_tailed, withBonf);

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


And here is the  the output of:

t = spm1d.stats.ttest_paired(YA, YB);
disp(t)

SPM{t}
         z: [1x200 double]
        df: [1 199]
      fwhm: 78.5959
    resels: [1 2.5319]


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

And the last picture that I send you (attached to this email) is the result about :

spm1d.stats.normality.ttest_paired(YA,YB);


Thank you so much for your responsiveness.


Best regards,


Andria Capai


________________________________
De : Todd Pataky <notifications@github.com>
Envoyé : mardi 11 décembre 2018 14:53:37
À : 0todd0000/spm1dmatlab
Cc : CAPAI Andria; Author
Objet : Re: [0todd0000/spm1dmatlab] SPM1D ttest_paired limit number subject ? (#94)


Hi Andria, there is no limit on N, so I suspect that there is a problem in data.

Can you please copy and send the full error? The full error will give information about what function and what line of code is causing the problem, and this will help me figure out what's going on.

Also, can you please copy and send the output of:

t = spm1d.stats.ttest_paired(YA, YB);
disp(t)

Thanks!

**Comment by 0todd0000** [comment]
Thank you for the details.  I'm not yet sure what the problem is, but I think if we can figure out what the values are in for *k* and *u* as inputs to **spm1d.rft1d.chi2.p_cluster_resels**, then we will solve the problem.  The **p_clister_resels** function accepts the following arguments:

* k
* u
* df
* resels

From the **disp(t)** output you copied above, there is no problem with *df* or *resels*, so the problem must be with *k* or *u*.  The easiest way to get these values will be to edit the source code in the file:

./+spm1d/+rft1d/chi2.m

Please open this chi2.m file in Matlab.  On Line 47 you should see:  "function [p] = p_cluster_resels(k, u, df, resels, varargin)"

Immediately after this line, please add two new lines:

```matlab
disp(k)
disp(u)
```

Then re-run your analysis.  At the top of the error message you should see two printed values (one for *k* and one for *u*).  Please tell me what these values are, then please delete the two lines you added above.

**Comment by andriacapai** [comment]
Hello Todd,


I followed your instructions and here is the output of :

 - disp(k)
0.0289 + 0.0020i

- disp(u)
    9.5925

I guess it's about the complex number ?

Thank you,

Andria CAPAI


________________________________
De : Todd Pataky <notifications@github.com>
Envoyé : mercredi 12 décembre 2018 19:19:55
À : 0todd0000/spm1dmatlab
Cc : CAPAI Andria; Author
Objet : Re: [0todd0000/spm1dmatlab] SPM1D ttest_paired limit number subject ? (#94)


Thank you for the details. I'm not yet sure what the problem is, but I think if we can figure out what the values are in for k and u as inputs to spm1d.rft1d.chi2.p_cluster_resels, then we will solve the problem. The p_clister_resels function accepts the following arguments:

  *   k
  *   u
  *   df
  *   resels

From the disp(t) output you copied above, there is no problem with df or resels, so the problem must be with k or u. The easiest way to get these values will be to edit the source code in the file:

./+spm1d/+rft1d/chi2.m

Please open this chi2.m file in Matlab. On Line 47 you should see: "function [p] = p_cluster_resels(k, u, df, resels, varargin)"

Immediately after this line, please add two new lines:

disp(k)
disp(u)

Then re-run your analysis. At the top of the error message you should see two printed values (one for k and one for u). Please tell me what these values are, then please delete the two lines you added above.

**Comment by 0todd0000** [comment]
Yes, the complex number is causing the problem. This is a curious bug!  I have no idea how a complex number can be generated. There must be some problem in YA and/or YB, but I'm not sure what it is. To figure out the problem, here are some questions / requests:

* Are there any complex numbers in YA or YB?

* Please plot the means and standard deviations of YA and YB as indicated below, then save as a JPG or PNG, then attach to your reply (please use the "attach" functionality in the GitHub forum)

```
spm1d.plot.plot_meanSD(YA, 'color','k');
hold on
spm1d.plot.plot_meanSD(YB, 'color','r');
```

* Please also plot the test statistic as indicated below, then attach it to your reply.

```
t = spm1d.stats.ttest_paired(YA, YB);
t.plot()
```

**Comment by andriacapai** [comment]
Hi Todd,

I followed your instruction and I did 2 other things (see below) , then here are results and figure attached in this message :
- isreal(YA) gives output : 1 
- isreal(YB) gives output : 1

-spm1d.plot.plot_meanSD(YA, 'color','k');
hold on
spm1d.plot.plot_meanSD(YB, 'color','r'); (See Figure : ![meanstd_ya_yb](https://user-images.githubusercontent.com/45765175/50003200-2af12900-ffa3-11e8-8674-d5d83f9a6835.png))

-t = spm1d.stats.ttest_paired(YA, YB);
t.plot()  (See figure ![results_ttest_pairesyayb](https://user-images.githubusercontent.com/45765175/50003201-2af12900-ffa3-11e8-93bb-5d1042df395f.png))

Thanks

Best,
Andria

**Comment by 0todd0000** [comment]
Thank you for these details. Everything looks OK in these figures, so I'm still not sure what the problem is... Here are two more questions:

* What version of Matlab are you using?
* What version of spm1d are you using?

**Comment by 0todd0000** [comment]
One more request:
Are you able to share the YA and YB data?  If yes, please either attach a data file to this issue, or send the file to me privately at pataky.todd.2m at kyoto-u.ac.jp
(Without the data it might be difficult to find the source of the problem.)
Todd

**Comment by andriacapai** [comment]
Hello Todd,

Here are the answers :
- Matlab version : R2016a
- Spm version : spm1d version M.0.4.5 (2017.06.22)

And I sent you data by email. 

Andria

**Comment by 0todd0000** [comment]
Hi Andria,
I tried analyses in Python, and analysis executes without any errors. I don't have access to Matlab right now, but Mark or Jos will test things out in Matlab then reply to this forum issue.
Todd

**Comment by m-a-robinson** [comment]
Hello Andria, Todd,

Well...to deepen the mystery further I am able to reproduce this error in Matlab (2018a).
I have checked the data, plotted it and when running the normality test it stops working when the following data is included

` spm       = spm1d.stats.normality.ttest_paired(yB(1:164,:), yA(1:164,:));`

Specifically the spm.z variable is a 1 x 200 complex double
Further investigation seems to indicate it is the last number that is the issue -4.690928480235349e+04 + 6.849996087265469e+04i, which is confirmed as the below code executes fine.

`spm       = spm1d.stats.normality.ttest_paired(yB(1:164,1:199), yA(1:164,1:199));`

Further inspection of the spm object gives no other clues to the origin of this number in any of the other data so I had a look in the **ttest_paired** function in the **+normality** folder and then ran the code in the k2residuals.m file.

Unsurprisingly it was this code that generated the complex number

```
    for i = 1:Q
        k2(i) = spm1d.stats.normality.k2_single_node( x(:,i) );
    end

```

A few data points from k2 are copied below. Which seems to show complex numbers across the array and not just the last value. 

825.629173732941 + 0.00000000000000i	565.388411199511 + 0.00000000000000i	2296.44269873964 + 0.00000000000000i	-4042.17882702022 + 3566.56394302302i	3974.46963820205 + 0.00000000000000i	1354.62841700969 + 0.00000000000000i	1040.73472716385 + 0.00000000000000i	783.079057243054 + 0.00000000000000i	597.873608650287 + 0.00000000000000i	388.363503781647 + 0.00000000000000i	234.540107676453 + 0.00000000000000i	159.773702440789 + 0.00000000000000i	136.943013109852 + 0.00000000000000i	143.051717524228 + 0.00000000000000i	167.034382931555 + 0.00000000000000i	194.088406195736 + 0.00000000000000i	223.130863954024 + 0.00000000000000i	283.234806765852 + 0.00000000000000i	456.478039071591 + 0.00000000000000i	1143.97818683881 + 0.00000000000000i	-2958.90847559263 + 2282.17818717165i	-1387.85415154322 + 638.339209455237i	-1201.10289464189 + 472.686282882775i	-1219.92830418537 + 489.011330343929i	-1337.57043336625 + 593.010723950451i	-1517.04206911690 + 758.417078752748i	-1913.63297595630 + 1147.65801262948i	-4900.53929221056 + 4636.37574504929i	1426.78845666040 + 0.00000000000000i	580.690356908692 + 0.00000000000000i	

So it looks like something in the  **k2_single_node** function but I'm stuck here for the time being.

Regards
Mark

**Comment by 0todd0000** [comment]
How bizarre. I think I've found the source of the problem, but not yet a solution.

I think the problem is a coding error in DagosPtest.m, which is available on the MathWorks File Exchange at the link below. **spm1d** uses a modified version of this code in its normality calculations.
https://www.mathworks.com/matlabcentral/fileexchange/3954-dagosptest

First, to test this bug, I suggest we use the sample data file at the link below, which is the fourth column of Andria's data, and which produces numerical problems. If you plot a histogram of these data you'll find a bimodal distribution. Clearly these data are non-normal and should yield a large value for the K2 statistic.
[sample_data.txt](https://github.com/0todd0000/spm1dmatlab/files/2699220/x.txt)

![hist](https://user-images.githubusercontent.com/4276626/50291213-f4505e00-043b-11e9-8a8d-21d65f84a934.png)



I think the coding problem stems from the kurtosis “Zg2” calculation on Line 125 in DagosPtest.m:

```matlab
Zg2 = (1-(2/(9*K))-L^(1/3))/sqrt(2/(9*K));
```

The numerical problem is that a negative L value produces a complex number or NaN. I verified that the sample data above produces a negative L value, and thus disrupts this kurtosis calculation.

Thus the L value (computed on Line 124) must contain an error, but the error could be propagated from previous lines.

Consider  Eqn. 5 in [Anscombe & Glynn (1983)](https://www.jstor.org/stable/pdf/2335960.pdf?casa_token=XK2aBmgrmuAAAAAA:QTAZopuYo3SZKYT8uyzJ7Os4ZDEDYl89k_0ahzv-hySPhtnM_8yPd1HF9n-JfdqzYd92rFLrbRmZI3mxAbgfAAB3p8ZXyoxlEfFYzjlB0oAgY8ev3Q), which represents “Zg2”. It would appear that the DagosPtest.m implementation of this equation is correct, where L represents the contents of the [square brackets].  The symbol translations are:

Anscombe & Glynn (1983) | DagosPtest.m
---------------|------------------
Eqn (5) | Zg2
[square brackets in Eqn (5)] | L
A | K
x | H

I think that Zg2, L and K calculations are correct, but I'm not sure about H. It's difficult for me to go much farther than this without access to Matlab.

If we can't figure it out relatively quickly I suggest we write to the author of DagosPtest.m to report the bug.

**Comment by andriacapai** [comment]
Hello Mark and Todd,


Thank you for yours answers and details you gave us !

Hope we will find the problem


Best,


[1505403877901_ISM][1505404771538_Aix]


Andria CAPAI - Ingénieur d'études
UMR 7287.Sc. du Mouvement (EJ Marey)
Institut des Sciences du Mouvement - 163 Avenue de Luminy - 13009 Marseille
Tél: +33(0)6 38 23 96 09<tel:+33%206%2038%2023%2096%2009>


________________________________
De : Mark Robinson <notifications@github.com>
Envoyé : mercredi 19 décembre 2018 23:47:42
À : 0todd0000/spm1dmatlab
Cc : CAPAI Andria; Author
Objet : Re: [0todd0000/spm1dmatlab] SPM1D ttest_paired limit number subject ? (#94)


Hello Andria, Todd,

Well...to deepen the mystery further I am able to reproduce this error in Matlab (2018a).
I have checked the data, plotted it and when running the normality test it stops working when the following data is included

spm = spm1d.stats.normality.ttest_paired(yB(1:164,:), yA(1:164,:));

Specifically the spm.z variable is a 1 x 200 complex double
Further investigation seems to indicate it is the last number that is the issue -4.690928480235349e+04 + 6.849996087265469e+04i, which is confirmed as the below code executes fine.

spm = spm1d.stats.normality.ttest_paired(yB(1:164,1:199), yA(1:164,1:199));

Further inspection of the spm object gives no other clues to the origin of this number in any of the other data so I had a look in the ttest_paired function in the +normality folder and then ran the code in the k2residuals.m file.

Unsurprisingly it was this code that generated the complex number

    for i = 1:Q
        k2(i) = spm1d.stats.normality.k2_single_node( x(:,i) );
    end



A few data points from k2 are copied below. Which seems to show complex numbers across the array and not just the last value.

825.629173732941 + 0.00000000000000i 565.388411199511 + 0.00000000000000i 2296.44269873964 + 0.00000000000000i -4042.17882702022 + 3566.56394302302i 3974.46963820205 + 0.00000000000000i 1354.62841700969 + 0.00000000000000i 1040.73472716385 + 0.00000000000000i 783.079057243054 + 0.00000000000000i 597.873608650287 + 0.00000000000000i 388.363503781647 + 0.00000000000000i 234.540107676453 + 0.00000000000000i 159.773702440789 + 0.00000000000000i 136.943013109852 + 0.00000000000000i 143.051717524228 + 0.00000000000000i 167.034382931555 + 0.00000000000000i 194.088406195736 + 0.00000000000000i 223.130863954024 + 0.00000000000000i 283.234806765852 + 0.00000000000000i 456.478039071591 + 0.00000000000000i 1143.97818683881 + 0.00000000000000i -2958.90847559263 + 2282.17818717165i -1387.85415154322 + 638.339209455237i -1201.10289464189 + 472.686282882775i -1219.92830418537 + 489.011330343929i -1337.57043336625 + 593.010723950451i -1517.04206911690 + 758.417078752748i -1913.63297595630 + 1147.65801262948i -4900.53929221056 + 4636.37574504929i 1426.78845666040 + 0.00000000000000i 580.690356908692 + 0.00000000000000i

So it looks like something in the k2_single_node function but I'm stuck here for the time being.

Regards
Mark

**Comment by m-a-robinson** [comment]
Hi both,

Thanks @0todd0000 for continuing down the Rabbit hole. I ran the code in k2_single_node.m and was able to replicate the negative L. 

H was -4.3844 and the final k2 statistic was a complex number -4.04..e+03 + 3.56..e+03i

I had a look at the calculation and the original paper but couldn't get to the bottom of this quickly so it might be worth emailing the author as you suggest.

Cheers
Mark

**Comment by 0todd0000** [comment]
I just posted a bug report to the MathWorks File Exchange:
https://www.mathworks.com/matlabcentral/fileexchange/3954-dagosptest

**Comment by andriacapai** [comment]
Thanks a lot for that



Andria


[1505403877901_ISM][1505404771538_Aix]


Andria CAPAI - Ingénieur d'études
UMR 7287.Sc. du Mouvement (EJ Marey)
Institut des Sciences du Mouvement - 163 Avenue de Luminy - 13009 Marseille
Tél: +33(0)6 38 23 96 09<tel:+33%206%2038%2023%2096%2009>


________________________________
De : Todd Pataky <notifications@github.com>
Envoyé : vendredi 21 décembre 2018 00:59:44
À : 0todd0000/spm1dmatlab
Cc : CAPAI Andria; Author
Objet : Re: [0todd0000/spm1dmatlab] SPM1D ttest_paired limit number subject ? (#94)


I just posted a bug report to the MathWorks File Exchange:
https://www.mathworks.com/matlabcentral/fileexchange/3954-dagosptest
