### ISSUE TITLE
Pressure InsIole

### ISSUE THREAD

**Issue by SinaDavid** [0todd0000/spm1dmatlab#96]
Hi Todd!

I started analyzing pressure insole data and have a question about the organisation of my dataset.
As I have the same shoe size for all my participants, I don't need to normalize the different shoe sizes. So far I have done the following steps to prepare my dataset:

1) summed the values of each sensor over the whole stancephase, to generate a 54x18 datapoint matrix.
2) mirrored all matrices to correct for left and right sight .

As I want to compare these matrices between shoe conditions in 10 subjects, my matrix for each shoe condition is 54x18x10.
I tried to conduct the paired ttest, but I think the organisation of my dataset is wrong (at least I do not understand the result).
Can you help my by explaining how I should organize my datasets?

Thanks in advance and happy new year!

Sina

**Comment by 0todd0000** [comment]
Hi Sina,

Pressure data are two-dimensional, but **spm1d** only directly supports analysis of one-dimensional data. **spm1d** can still be used to analyze 2D data, but only non-parametrically. Please see issues #61 and #77 for descriptions of 2D and 3D data analysis using **spm1d**.

The meaning of dimensionality from an SPM perspective is described in:
https://github.com/0todd0000/spm1d/issues/73
(See the entry near the bottom regarding continuum dimensionality and dependent variable dimensionality)

Happy New Year!
Todd

**Comment by 0todd0000** [comment]
Preliminary support for 2D data analysis has been added to **spm1d**!
[Example 2D analysis (Python)](http://www.spm1d.org/doc/Stats2D/ex2d.html)
[Example 2D analysis (MATLAB)](http://www.spm1d.org/doc/Stats2D/ex2d_matlab.html)
