### ISSUE TITLE
How to apply a 1D multi-component analysis with smp1d?

### ISSUE THREAD

**Issue by BDumphart** [0todd0000/spm1dmatlab#97]
Hello Todd,

we have been using spm1d to analyze GRF data between different groups of patients. We compared the z-component of normal walkers with the z-component of different patient groups (roughly 200 patients per group) and so on (with all GRF components).
This worked just fine but we asked our selves if it is possible to compare ALL 3 GRF vectors (x,y,z) of the normal walking patients at the same time against the different patient groups (Multicomponent vector, 3 components)? And if this step holds any more / any less information then comparing the GRF components 1-by-1? And how would this be done in MATLAB smp1d? Any code snippets? 

Thank you for your answer,

Bernhard

**Comment by m-a-robinson** [comment]
Hello Bernhard,

The analysis you suggest comparing "normal" GRF XYZ vs "patient" GRF xyz is indeed possible. It is known as a vector-field analysis as you analyse all GRF components (a vector field) in one statistical test. For your analysis it seems like it is a two-sample design and so you would use a two-sample Hotellings T2 test. This analysis more accounts for the co-variance amongst the GRF components which can have potentially important effects on the results. See [Todd's 2013 paper ](https://www.sciencedirect.com/science/article/pii/S0021929013003564).

In Matlab the function you need is spm1d.stats.hotellings2. The code below would have YA as normal and YB as patients.

```
spm       = spm1d.stats.hotellings2(YA, YB);
spmi      = spm.inference(0.05);
disp(spmi)
```
Note that YA and YB need to be 3-dimensional arrays following the JxQxI strcture where J = number of participants, Q = number of nodes e.g. 101, I = number of GRF components e.g. 3.
So YA might be 200x101x3 

In Matlab the concatentate function might be helpful to create the data variable like this as an example...
```
x = ones(101,10);
y = ones(101,10);
z = ones(101,10);
xyz = cat(3,x,y,z);
```
Regards
Mark

**Comment by BDumphart** [comment]
Thank you very much @m-a-robinson it worked for me! :)

Is there somehow a way to plot this like the normal t-test with the mean-SD and the p-values and threshold? Or is it not possible due to the 3 dimensional vector?

Regards,
Bernhard

**Comment by m-a-robinson** [comment]
Hello Bernhard,
Plotting the data is not easily possible due to the data dimensionality and also the time dimension - so 4D in total..
If you want to plot the test output just use 
`spmi.plot()`
Regards
Mark

**Comment by BDumphart** [comment]
Thank you very much!

**Comment by adrianrivadulla** [comment]
Hi Mark,

I'm in a similar but slightly different situation:

We have two groups that completed pre, post, retention and transfer tests each and we've collected bar trajectories. We'd like to test for an interaction effect of Group x Session on BARxy. What test would be analogous to an ANOVA2onerm for our 2-component case? Or should we use just a MANOVA? If MANOVA is there a MANOVA2onerm? Is it possible in spm1dmatlab?

Thank you for attention.

Kind regards,

Adrian
